### ISSUE TITLE
Evaluate Impact of Changing Equihash Parameters

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#2715] opened 2017-11-09 22:18 UTC
We may wish to change equihash parameters to achieve various goals with the Zcash mining ecosystem. We have no concrete proposals, nor even clear goals here, yet, but I'm filing this early so that miners and others can follow along.

TODO:

- specify possible goals
    * note: specifying a goal well doesn't imply Zcash devs have *adopted and committed* to a goal. To even do so, we must first specify it and evaluate it carefully.
- evaluate how given proposed parameter changes fulfill different goals *along with their tradeoffs*.

**Comment by zookozcash** [comment] 2019-01-03 17:09
moved to https://github.com/zcash/zcash/issues/3672

**Comment by zookozcash** [comment] 2019-01-03 17:10
This should be closed.

**Comment by zookozcash** [comment] 2019-01-03 17:10
(But I can't close this ticket.)

**Comment by daira** [comment] 2019-01-09 00:46
This is not a duplicate of #3672. It asks to evaluate the impact of changing the Equihash parameters, which is an important subproblem of the Harmony mining design, but certainly deserves its own ticket.

**Comment by str4d** [comment] 2020-08-18 14:49
At this point, we are more likely to move to an alternative PoW or PoS design, than simply altering the Equihash parameters. @daira notes that the current Equihash parameters are impractical to verify in a circuit, but the problematic part is the presence of BLAKE2b hash, rather than the parameters per-se (which defines the quantity of hashes).

**Closed by str4d** 2020-08-18 14:49 UTC
Labels: A-consensus, A-pow, M-requires-nu, NU2-blossom-adjacent, feature selection meeting agenda
