### ISSUE TITLE
Negative balance on account

### ISSUE THREAD

**Issue by nfedoseev** [zcash/zcash#2713] opened 2017-11-09 11:37 UTC
Hi, some days ago i made transaction, but on destination account i did found my amount, but saw negative transperent balance on Zchain viewer.

But by wallet, transaction have 3640 confirmations:
![default](https://user-images.githubusercontent.com/4405149/32603628-7767e6da-c55b-11e7-9d36-c90af51222de.png)

Account: https://explorer.zcha.in/accounts/t1aDWp2qjG68xJ2RjBmuY932bGWCccKNP2j
Transaction (unable to view): https://explorer.zcha.in/transactions/34c83b098749c26187381c2da3925f6fc73a9577fb6393c8c869192fbabd9a63

**Comment by daira** [comment] 2017-11-09 11:47
The only way the balance of an address can appear negative on a block explorer is of the explorer is not taking into account all transactions that paid into the address. This is known to happen sometimes with the zcha.in explorer. I suggest checking with another explorer, such as zcashnetwork.info; for that address, it reports a zero balance: http://zcashnetwork.info/address/t1aDWp2qjG68xJ2RjBmuY932bGWCccKNP2j

**Comment by daira** [comment] 2017-11-09 11:50
(The "invalid" label just indicates that this is not a bug in the Zcash software maintained in this repository.)

**Comment by ioptio** [comment] 2017-11-13 18:18
Closing this ticket. Something for @lustro to check out.

**Closed by ioptio** 2017-11-13 18:18 UTC
Labels: invalid
