### ISSUE TITLE
11-day delay in mining a transaction with 498 transparent inputs

### ISSUE THREAD

**Issue by BLESSED90** [zcash/zcash#3167] opened 2018-04-12 08:41 UTC
Hello, how to deal with this problem. How can you conduct a transaction, or what is its fate? Why wait?
Here is the link: https://explorer.zcha.in/transactions/6aaa9a9e1545163113227f50645bcc73cd273928a49d951d017e17083cf011d7
I ask for help.

**Comment by ioptio** [comment] 2018-04-16 18:47
As you've noted, the problem here is miners blocking transactions above a certain number of inputs. 

We have an upcoming feature in Overwinter called transaction expiry which will address these issues (https://github.com/zcash/zips/blob/master/zip-0203.rst). Once Overwinter is activated at block 247500, any Sapling formatted transactions not yet confirmed become invalid and the new Overwinter formatted transactions include the above feature which default expires transactions after 20 blocks if they haven't been confirmed.

In the meantime, the community has figured out some ways to attempt to get around a stalled transaction such as: https://forum.z.cash/t/cancel-unconfirmed-transaction/18912/4

We always recommend you backup your wallet: https://github.com/zcash/zcash/blob/master/doc/wallet-backup.md

You might also just want to wait for a miner which doesn't have input limits set to accept your transaction.

So, in essence, this ticket is already addressed but only available after the upcoming Overwinter activation. Let us know how you proceed or if your transaction gets confirmed.

**Comment by garethtdavies** [comment] 2018-04-16 19:43
This seems to be a recurring issue lately (another one this morning on the forums). Obviously, Overwinter fixes this but it is still a long time horizon for someone in this position. I'm curious about this proposed solution on the forums and understanding why it works - more, could this be resolved in a more straightforward manner such as clearing the local mempool?

**Comment by ioptio** [comment] 2018-08-13 18:13
Closing this because Overwinter fixes issues like this. Feel free to reopen if it's still a problem.

**Closed by ioptio** 2018-08-13 18:13 UTC
Labels: tx propagation/mining latency, usi
