### ISSUE TITLE
Update release process doc to ensure we create a github release with notes.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#2262] opened 2017-04-14 02:20 UTC
While releasing 1.0.8-1 I noticed we're missing the github release for 1.0.8.

Also only some subset of our releases are called 'verified' by github, so figure that out and update `release-process.md` accordingly.

**Comment by daira** [comment] 2017-07-26 00:50
^ marked #2487 as a duplicate of this.

**Closed** 2017-09-13 21:41 UTC
Labels: dev infrastructure, dev policy, documentation, release, retrospective meeting agenda
