### ISSUE TITLE
ERROR: AcceptToMemoryPool: inputs already spent

### ISSUE THREAD

**Issue by pinootto** [zcash/zcash#1916] opened 2016-12-05 12:07 UTC
In the debug.log file there are many errors such as:

2016-12-05 11:36:07 CreateNewBlock(): total size 1451
2016-12-05 11:36:07 Running ZcashMiner with 3 transactions in block (725 bytes)
2016-12-05 11:36:07 CreateNewBlock(): total size 1451
2016-12-05 11:36:07 Running ZcashMiner with 3 transactions in block (725 bytes)
2016-12-05 11:36:07 CreateNewBlock(): total size 1451
2016-12-05 11:36:07 Running ZcashMiner with 3 transactions in block (725 bytes)
2016-12-05 11:36:07 CreateNewBlock(): total size 1451
2016-12-05 11:36:07 Running ZcashMiner with 3 transactions in block (725 bytes)
2016-12-05 11:36:09 CreateNewBlock(): total size 1451
2016-12-05 11:36:09 Running ZcashMiner with 3 transactions in block (725 bytes)
2016-12-05 11:36:11 **ERROR: AcceptToMemoryPool: inputs already spent**
2016-12-05 11:36:13 UpdateTip: new best=000000008e819054d607a80fac390ed28b196b8d847f25ae1842f7e328eb3e2d  height=22228  log2_work=46.058998  tx=145103  date=2016-12-05 11:36:09 progress=0.999998  cache=38.7MiB(2206tx)
2016-12-05 11:36:14 CreateNewBlock(): total size 19843
2016-12-05 11:36:14 Running ZcashMiner with 2 transactions in block (19117 bytes)
2016-12-05 11:36:14 CreateNewBlock(): total size 19843
2016-12-05 11:36:14 Running ZcashMiner with 2 transactions in block (19117 bytes)
2016-12-05 11:36:14 CreateNewBlock(): total size 19843
2016-12-05 11:36:14 Running ZcashMiner with 2 transactions in block (19117 bytes)

This is my conf file:

$ cat ~/.zcash/zcash.conf 
addnode=mainnet.z.cash
rpcuser=xxxxx
rpcpassword=xxxxx
gen=1
genproclimit=8
equihashsolver=tromp

After 1 day of running, there are no transactions and the balance is zero:

$ ./src/zcash-cli getinfo
{
    "version" : 1000350,
    "protocolversion" : 170002,
    "walletversion" : 60000,
    "balance" : 0.00000000,
    "blocks" : 22242,
    "timeoffset" : 6,
    "connections" : 8,
    "proxy" : "",
    "difficulty" : 850087.15782182,
    "testnet" : false,
    "keypoololdest" : 1480851390,
    "keypoolsize" : 101,
    "paytxfee" : 0.00000000,
    "relayfee" : 0.00001000,
    "errors" : ""
}

What am I doing wrong?

**Comment by ebfull** [comment] 2016-12-05 18:45
This isn't too scary; basically, you're seeing transactions that you can't verify because someone is making a transaction that uses a more recent block. Your node will continue to verify new blocks but if a new block appears that you aren't aware of yet, you may see those kinds of errors occasionally. You will also very commonly see those errors when syncing with the blockchain from scratch.

**Comment by pinootto** [comment] 2016-12-07 15:24
OK, thanks.

**Comment by str4d** [comment] 2017-01-04 16:09
I think the next step for this issue is figuring out whether we can reduce the scariness of that log message. Are there cases in which we would want users to care that this had occurred, that currently don't have a different more-visible error associated with them?

**Comment by ioptio** [comment] 2017-06-20 17:46
Closing this ticket in lieu of a more general ticket on improving logging error reporting.

**Closed by ioptio** 2017-06-20 17:46 UTC
Labels: logging, question, usability, user support

**Comment by schadokar** [comment] 2020-04-17 10:18
I am running the zcash node in docker container. Whenever this error occurs, the docker container stops. Is it possible to sync only the blocks which are confirmed in all nodes? Or sync the node 50-100blocks behind the mainnet? Is there any flag which stops syncing? like noconnect in bitcoin.
