### ISSUE TITLE
Create basic "wallet" with scripts

### ISSUE THREAD

**Issue by str4d** [zcash/zcash#770] opened 2016-03-09 22:59 UTC
A number of people in the forum have had problems following the Public Alpha Guide. We should write some Bash scripts to automate the necessary steps, so that people can more easily play with Zcash before we have proper wallets.

**Comment by ebfull** [comment] 2016-03-09 23:06
Closing as a duplicate of #502 (and I assigned you to that ticket).

**Closed by ebfull** 2016-03-09 23:06 UTC
Labels: testing, usability, wallet
