### ISSUE TITLE
Compilation problem in ./src/wallet/rpcwallet.cpp

### ISSUE THREAD

**Issue by JanKalin** [zcash/zcash#838] opened 2016-04-06 12:16 UTC
Compilation on Debian fails with
`wallet/rpcwallet.cpp:2561:28: error: no matching function for call to "CPourTx::CPourTx(libzerocash::ZerocashParams&, CScript&, uint256&, <brace-enclosed initializer list>, <brace-enclosed initializer list>, CAmount&, CAmount&)"`
because of
`./primitives/transaction.h:79:5: note:   no known conversion for argument 4 from "<brace-enclosed initializer list>â to âconst boost::array<libzerocash::PourInput, 2ul>&"`

The solution is to replace
`CPourTx pourtx(*pzerocashParams,
                   scriptPubKey,
                   anchor,
                   {vpourin[0], vpourin[1]},
                   {vpourout[0], vpourout[1]},
                   vpub_old,
                   vpub_new);
`
with
`CPourTx pourtx(*pzerocashParams,
                   scriptPubKey,
                   anchor,
                   { {vpourin[0], vpourin[1]} },
                   { {vpourout[0], vpourout[1]} },
                   vpub_old,
                   vpub_new);
`

**Comment by JanKalin** [comment] 2016-04-15 15:45
In v0.11.2.z2  the same problem is introduced in src/zcbenchmarks.cpp in lines 85..91

**Comment by ebfull** [comment] 2016-04-15 16:34
This is confusing, what toolchains require this kind of syntax?

**Comment by nathan-at-least** [comment] 2016-04-19 00:19
@JanKalin which gcc version are you using? Do you build with ``./zcutil/build.sh``?

I don't see that problem with:

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux testing (stretch)
Release:        testing
Codename:       stretch

$ g++ --version
g++ (Debian 5.2.1-23) 5.2.1 20151028
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by JanKalin** [comment] 2016-04-19 06:44
Yes, i used `./zcutil/build.sh`. The versions are:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 7.10 (wheezy)
Release:        7.10
Codename:       wheezy

$ g++ --version
g++ (Debian 4.7.2-5) 4.7.2
Copyright (C) 2012 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by JanKalin** [comment] 2016-04-19 10:05
Apparently this is related to an old version of compiler. I just installed a fresh copy in a virtual machine and it compiles just fine.

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 8.4 (jessie)
Release:        8.4
Codename:       jessie

$ g++ --version
g++ (Debian 4.9.2-10) 4.9.2
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by JanKalin** [comment] 2016-05-17 21:39
Same problem in wheezy (and not in jessie) in files

test/sighash_tests.cpp, lines 133 and 134

gtest/test_joinsplit.cpp, line 226

A different pre C++11 problem in wheezy (and not in jessie):
`src/gadgetlib2/constraint.hpp:157:23: error: â<::â cannot begin a template-argument list [-fpermissive]`

Explanation here: https://stackoverflow.com/questions/3952648/cannot-begin-a-template-argument-list

BTW, should I keep reporting these errors, as they are relevant for a relatively old Debian release and possibly not relevant to the public at large?

**Comment by nathan-at-least** [comment] 2016-07-25 21:04
We're not going to focus on build issues with toolchains different than our developer tool set right now, but we'll look at it for our Beta release.

**Comment by daira** [comment] 2016-08-26 12:31
We should specify a minimum GCC version.

**Comment by ebfull** [comment] 2016-08-30 18:13
@daira What version should we target?

**Comment by daira** [comment] 2016-08-30 18:21
Assigning to myself to look at the gcc release notes.

**Comment by nathan-at-least** [comment] 2016-09-20 20:48
We're not certain this issue applies to our recent software, so we're deprioritizing it. @JanKalin can you reproduce this issue on our recent Beta 1 (or newer) release?

**Comment by nathan-at-least** [comment] 2016-09-20 20:49
@daira: We deprioritized this from Beta 2 since we suspect it may no longer apply. If it does, it's a lower priority because our 'official distribution' will be binaries we build. After launch we'll work on supporting a broader ecosystem of user dev setups.

**Comment by daira** [comment] 2016-09-20 22:35
We still do need to decide on which gcc to build the official distribution with, but that probably belongs in #1034.

**Comment by JanKalin** [comment] 2016-09-21 13:21
Yes, the compilation issues are still there. In fact the number of them has increased. I'm enclosing output from "git diff > zcash_diff.txt". These are the steps (from history) needed to compile on my machine:

 1877  git clone https://github.com/zcash/zcash.git
 1878  cd zcash/
 1879  git checkout  v1.0.0-beta1
 1880  ./zcutil/fetch-params.sh
 1881  vim src/crypto/equihash.h
 1882  vim src/gtest/test_joinsplit.cpp
 1883  vim src/uint256.h
 1884  vim src/wallet/rpcwallet.cpp
 1885  vim src/zcbenchmarks.cpp
 1886  vim zcutil/build.sh
 1887  ./zcutil/build.sh -j$(nproc)
 1888  find . -name "assert_except.hpp"
 1889  vim ./depends/work/build/x86_64-unknown-linux-gnu/libsnark/0.1-39e04c3826a/src/common/assert_except.hpp
 1890  ./zcutil/build.sh -j$(nproc)

assert_except.hpp, IIRC, is missing <stdexcept>
[zcash_diff.txt](https://github.com/zcash/zcash/files/485090/zcash_diff.txt)

**Comment by Zenitur** [comment] 2016-10-30 00:36
@JanKalin thank you! You made a huge work! The only one change in src/uint256.h:

`# if __GNUC__ > 4 || __GNUC__ == 4 && __GNUC_MINOR__ >= 8`
`alignas(uint32_t) uint8_t data[WIDTH];`
`#else`
`__attribute__((aligned(4))) uint8_t data[WIDTH];`
`#endif`

**Comment by daira** [comment] 2016-10-30 00:43
We should define an ``alignas_uint32_t`` macro rather than including the above conditional at all uses, even if there is currently only one.

**Comment by daira** [comment] 2017-04-20 12:32
We're now requiring gcc/g++ 4.9 or later (and the User Guide documents that), so I think this can be closed.

**Closed by daira** 2017-04-20 12:32 UTC
Labels: build, Zcash Core codebase
