### ISSUE TITLE
z to multiple t addresses remain unconfirmed for hours

### ISSUE THREAD

**Issue by etherchain-org** [zcash/zcash#1871] opened 2016-11-17 13:36 UTC
On my payment node more and more z to multiple t addresses (max 250 recipients) are not getting mined.

Here is a list of the affected transactions:
Relaying wtx 84cd823474f78d856b2f2ac7d0472d0a2111bbc5d08a6f597cc84c40fb34f795
Relaying wtx 5c6cc1b6f403dd4bc1a8535655e1d9f55e591d398f7036eb66fae11d7f5bc7d4
Relaying wtx 06dab466369ca9a39b3d053ecd487848ca8a1060ad1e62ae29c8bb76f7687cca
Relaying wtx 8e9a6c4e4dd8bf0a599f85d5f4e36ab570c579b2b46212b4a91ee75d63ae7d68
Relaying wtx c452a5b8483ffbe0da2c6f42260b88014c38ef94cb35d5ca9c7a52d76e03ff92
Relaying wtx 9b6261604302de2d57ab3ae9917cab521a8ecf13aed2e77e1a7edb41be85b6bd
Relaying wtx f6fc8fc7fbe1565208d02cfa40c46a0ea7cd45e6e314a00a0950d5e02be7695e
Relaying wtx 0fd32ca3a1b6d09c15bc8b72e645d78c64842226cc2a3979481afbc8ff48c248
Relaying wtx 5ade1ff00cbcfb81f4e7e09b076ac157864aca447c12b77957988e7f702c0d69
Relaying wtx 2c0759526e803097685adad7b36e50191b761f6cd50908cf4caa52a3583d6f81
Relaying wtx 4685ab447b01098d037182919f0fa3734ff7f8e473627798102003e6011035a5
Relaying wtx ce1814520620921cbe5559127ce8043bba6728a35e113d4cce63997850698e0b
Relaying wtx 2313e39f8a37262323c906c01104bd8ec9474eb284f3b5a27bca6682a85b4585
Relaying wtx 65d6601ff968f2491bb0ad083008fee6cb940979e19f22694582e46e1be11650
Relaying wtx 75c9afcc2c51a9794368ae853f65dd14dc289af48725c29e6a63a295abc70f48
Relaying wtx 945bc161b6971070b70a99cc05d3707ecc0d8cb7ab9429a1f21054eb90046c87
Relaying wtx 26f19d6c85ae1fe2d3a341f3b8f671debd3ea95e55672d98e6e9411fcde57b6c

The transactions are properly relayed to the network as I can see them in the mempool of my other nodes. But for whatever reason they are not getting mined.

Edit: The tx were mined after ~2,5 hours.

**Comment by daira** [comment] 2016-11-19 02:29
Please tell us if this still happens with 1.0.3.

**Comment by bitcartel** [comment] 2016-11-19 06:49
We could add an option in the RPC call to let the caller specify a custom ee for z_sendmany tx to help prioritise the transaction.

**Comment by str4d** [comment] 2016-11-23 20:04
Likely also caused by those transactions having zero priority (#1857), which #1895 will fix.

**Comment by ioptio** [comment] 2016-12-06 21:38
Closing this since #1857 exists and @etherchain-org hasn't responded. Feel free to re-open if problem persists.

**Closed by ioptio** 2016-12-06 21:38 UTC
Labels: tx propagation/mining latency, usability, user support
