### ISSUE TITLE
Change the measure for multithreaded solveequihash to solutions per second

### ISSUE THREAD

**Issue by ampyx** [zcash/zcash#1430] opened 2016-09-22 15:57 UTC
I believe it would be a nice feature if the equihash benchmark utility would put out an average solutions per second instead of a running time per thread.

The time to run the algorithm per thread does not give a clear indication on how many solutions are found at all. People on the forum calculate this by compensating with a factor two (according to the paper there are two solutions found on each run) or they give another weird measure "h/s" for their solver runs. In my eyes, it would be good to have a benchmark with a clear measure in averaged solutions / second instead, this would give the community a better way to measure their performance.

This could be simply implemented by keeping track of the number solutions found per trial and the time it took do do one trial. An average over many trials gives a good averaged solutions per second. In a simple formula, it would be something like

![image](https://cloud.githubusercontent.com/assets/6241437/18755745/9d7f300c-80ed-11e6-90ce-8ca662d05ca1.png)

Also, the solver could output a standard deviation of the above defined average. This would give direct information on how "stable" the solver is producing the above defined rate.

**Comment by tromp** [comment] 2016-09-22 16:26
I agree with the above except for the formula, which is an average of rates and thus can be quite misleading. For instance if half the trials find 10 solutions in 10 seconds and the other half find 10 solutions in 1 second. Then the overal rate is 20 in 110 is ~1.8, while the average of rates 1 and 10 is 5.5
So I prefer the simpler (total number of solutions) / (total time), that being the overall rate.

**Comment by daira** [comment] 2016-09-22 17:28
Duplicate of part of #1191. Please feel free to comment on that ticket!

> The time to run the algorithm per thread does not give a clear indication on how many solutions are found at all. People on the forum calculate this by compensating with a factor two (according to the paper there are two solutions found on each run) or they give another weird measure "h/s" for their solver runs. In my eyes, it would be good to have a benchmark with a clear measure in averaged solutions / second instead, this would give the community a better way to measure their performance.

Agreed. I intend this to be implemented by adding a new throughput benchmark, not by changing the existing benchmark beyond the improvement implemented in #1376, because it's important to maintain continuity of the benchmark history.

The throughput benchmark is likely to work by running multiple threads for a specified (fairly long, e.g. 10 minutes) period and counting how many solutions are produced. It would be possible to compensate for the unused work toward the next solution for each thread at the end of the period, but remember that in practice, runs will normally be interrupted by another miner finding the next block, so not compensating for that might actually be more realistic.

**Closed by daira** 2016-09-22 17:28 UTC
