### ISSUE TITLE
Nodes hanging (block count is not getting updated)

### ISSUE THREAD

**Issue by artlav** [zcash/zcash#1397] opened 2016-09-14 21:15 UTC
I would occasionally find that one or the other machine in the mining cluster shows an old block count (i.e. in getinfo).
Trying to stop or sigterm it makes it just sit there, sometimes consuming 100% of one CPU core, sometimes doing nothing at all.
Nothing short of kill -9 helps. Looks almost as if it went into some sort of infinite loop/deadlock inside.
Once restarted, it keeps working as if nothing happened.

One time it happened on Intel(R) Celeron(R) CPU G1620 @ 2.70GHz, 2 Gb RAM, mining on one core.
Another time was on Intel(R) Core(TM) i7 CPU 920 @ 2.67GHz, 12 Gb RAM, mining on 4 cores.

So there doesn't seem to be any HW dependence.

**Comment by daira** [comment] 2016-09-15 11:59
Please attach your ~.zcash/debug.log file. Also if you can reproduce with ``zcashd -debug=1`` and post that debug.log, that would be even more helpful.

**Comment by artlav** [comment] 2016-09-15 13:17
Here are the logs.
On 1 it was found hung and stopped on 14th, 10:25
On 2 it was on 13th, at 12:24 and 21:55, i think i waited for a while before killing it the first time.
On 3 it was on 13th, at 19:25

I've started several nodes with zcashd -daemon -debug=1, will post if one happens to hang.

[cnode_1.log.gz](https://github.com/zcash/zcash/files/474674/cnode_1.log.gz)
[cnode_2.log.gz](https://github.com/zcash/zcash/files/474675/cnode_2.log.gz)
[cnode_3.log.gz](https://github.com/zcash/zcash/files/474676/cnode_3.log.gz)

**Comment by daira** [comment] 2016-09-15 22:05
Here's the relevant part of the first log:
```
2016-09-14 04:28:35 UpdateTip: new best=0008d8d66bce5843727546b758974bd1d00dfd99dadc59360567fcaff4cf422a  height=2762  log2_work=20.78403  tx=3320  date=2016-09-14 04:27:17 progress=1.000000  cache=0.2MiB(472tx)
2016-09-14 04:29:08 CreateNewBlock(): total size 1000
2016-09-14 04:29:08 Running ZcashMiner with 1 transactions in block (274 bytes)
2016-09-14 04:47:22 socket sending timeout: 1201s
2016-09-14 04:47:32 socket sending timeout: 1201s
2016-09-14 04:47:41 socket sending timeout: 1201s
2016-09-14 04:48:05 connect() to 139.59.149.88:18233 failed after select(): Connection refused (111)
2016-09-14 04:48:14 socket sending timeout: 1201s
2016-09-14 04:48:16 socket sending timeout: 1201s
2016-09-14 04:48:25 connect() to 78.47.196.146:18233 failed after select(): Connection refused (111)
2016-09-14 04:48:31 connect() to 104.155.177.182:18233 failed after select(): Connection refused (111)
2016-09-14 04:48:36 socket sending timeout: 1201s
2016-09-14 05:07:38 socket sending timeout: 1201s
2016-09-14 05:08:07 connect() to [2002:4bbe:21bc:1234:d978:556e:b608:e31f]:18233 failed: Network is unreachable (101)
2016-09-14 05:27:38 connect() to [2002:4bbe:21bc:1234:78f4:861f:7662:856a]:18233 failed: Network is unreachable (101)
2016-09-14 05:28:38 connect() to 115.192.223.244:18233 failed after select(): Connection refused (111)
2016-09-14 05:28:46 connect() to 183.16.188.121:18233 failed after select(): Connection refused (111)
2016-09-14 05:47:39 socket sending timeout: 1201s
2016-09-14 06:08:48 connect() to 180.72.234.249:18233 failed after select(): Connection refused (111)
2016-09-14 06:08:49 connect() to 81.110.169.126:18233 failed after select(): Connection refused (111)
2016-09-14 06:28:59 socket sending timeout: 1201s
2016-09-14 06:48:54 connect() to [2002:4bbe:21bc:1234:99f2:cf50:6dc1:c0c2]:18233 failed: Network is unreachable (101)
2016-09-14 06:48:55 connect() to 117.89.135.141:18233 failed after select(): Connection refused (111)
2016-09-14 06:48:56 socket sending timeout: 1201s
2016-09-14 06:49:35 connect() to [2002:4bbe:21bc:1234:1da8:31c2:6bf9:27e9]:18233 failed: Network is unreachable (101)
2016-09-14 06:49:35 connect() to [fec0::6038:996b:7e95:5415]:18233 failed: Network is unreachable (101)
2016-09-14 07:08:31 connect() to [2a02:582:19b7:400:20c:29ff:feb8:3958]:18233 failed: Network is unreachable (101)
2016-09-14 07:09:09 connect() to 87.159.229.190:18233 failed after select(): No route to host (113)
2016-09-14 07:09:09 connect() to 93.159.121.155:18233 failed after select(): No route to host (113)
2016-09-14 07:29:41 socket sending timeout: 1201s
2016-09-14 07:29:42 socket sending timeout: 1201s
2016-09-14 07:29:59 connect() to 139.59.149.88:18233 failed after select(): Connection refused (111)
2016-09-14 07:30:06 connect() to [2604:2000:f20e:b900:1c0:eba4:7697:679e]:18233 failed: Network is unreachable (101)
2016-09-14 07:50:06 socket sending timeout: 1201s
2016-09-14 07:50:27 socket sending timeout: 1201s
2016-09-14 08:09:22 socket sending timeout: 1201s
2016-09-14 08:10:39 connect() to 104.194.255.242:18233 failed after select(): Connection refused (111)
2016-09-14 08:10:40 connect() to 117.89.135.141:18233 failed after select(): Connection refused (111)
2016-09-14 08:10:52 connect() to 58.83.197.248:18233 failed after select(): No route to host (113)
2016-09-14 08:11:07 connect() to 83.160.76.197:18233 failed after select(): No route to host (113)
2016-09-14 08:30:06 socket sending timeout: 1201s
2016-09-14 08:30:12 connect() to 87.211.143.232:18233 failed after select(): Connection refused (111)
2016-09-14 08:30:59 socket sending timeout: 1201s
2016-09-14 08:31:15 socket sending timeout: 1201s
2016-09-14 08:48:41 socket sending timeout: 1201s
2016-09-14 08:48:42 connect() to 183.16.188.121:18233 failed after select(): Connection refused (111)
2016-09-14 08:48:59 connect() to 93.159.121.155:18233 failed after select(): No route to host (113)
2016-09-14 08:49:28 socket sending timeout: 1201s
2016-09-14 08:50:27 socket sending timeout: 1201s
2016-09-14 08:50:34 socket sending timeout: 1201s
2016-09-14 09:09:27 connect() to [2a02:582:19b7:400:20c:29ff:feb8:3958]:18233 failed: Network is unreachable (101)
2016-09-14 09:10:42 socket sending timeout: 1201s
2016-09-14 09:10:51 connect() to 217.168.76.86:18233 failed after select(): Connection refused (111)
2016-09-14 09:31:36 connect() to 117.89.135.141:18233 failed after select(): Connection refused (111)
2016-09-14 09:49:36 socket sending timeout: 1201s
2016-09-14 09:49:43 connect() to 184.152.56.210:18233 failed after select(): No route to host (113)
2016-09-14 09:50:08 socket sending timeout: 1201s
2016-09-14 09:51:09 socket sending timeout: 1201s
2016-09-14 09:51:09 socket sending timeout: 1201s
2016-09-14 09:51:38 socket sending timeout: 1201s
2016-09-14 10:00:19 keypool reserve 10
2016-09-14 10:00:19 keypool return 10
2016-09-14 10:01:10 keypool reserve 10
2016-09-14 10:01:10 keypool return 10
2016-09-14 10:06:21 keypool reserve 10
2016-09-14 10:06:21 keypool return 10
2016-09-14 10:11:28 socket sending timeout: 1201s
2016-09-14 10:11:48 connect() to [2002:4bbe:21bc:1234:8c0:112f:674a:7ba8]:18233 failed: Network is unreachable (101)
2016-09-14 10:25:04 keypool reserve 10
2016-09-14 10:25:04 keypool return 10
2016-09-14 10:25:57 addcon thread interrupt
2016-09-14 10:25:57 opencon thread interrupt
2016-09-14 10:25:57 scheduler thread interrupt
2016-09-14 10:25:57 net thread interrupt
2016-09-14 10:36:23 

2016-09-14 10:36:23 Bitcoin version v1.0.0-beta1 (2016-09-09 00:41:41 -0600)
[continues with normal node startup]
```

Similarly in the second log:
```
2016-09-13 11:30:06 UpdateTip: new best=00336da04993abb869f5f17749050e13de85894b994d6bfadbf2d84026d4d2d4  height=2353  log2_work=20.464112  tx=2785  date=2016-09-13 11:28:26 progress=1.000000  cache=0.1MiB(390tx)
2016-09-13 11:49:01 connect() to 79.35.201.29:18233 failed after select(): Connection refused (111)
2016-09-13 11:49:07 socket sending timeout: 1201s
2016-09-13 11:49:08 socket sending timeout: 1201s
2016-09-13 11:49:15 socket sending timeout: 1201s
2016-09-13 11:49:15 socket sending timeout: 1201s
2016-09-13 11:49:19 socket sending timeout: 1201s
2016-09-13 11:49:27 socket sending timeout: 1201s
2016-09-13 11:49:36 connect() to 219.234.147.131:18233 failed after select(): Connection refused (111)
2016-09-13 11:50:06 socket sending timeout: 1201s
2016-09-13 11:50:06 connect() to 58.83.197.248:18233 failed after select(): No route to host (113)
2016-09-13 11:59:49 ZcashMiner started
2016-09-13 11:59:49 keypool reserve 3
2016-09-13 11:59:49 CreateNewBlock(): total size 1000
2016-09-13 11:59:49 Running ZcashMiner with 1 transactions in block (274 bytes)
2016-09-13 12:10:37 connect() to 81.110.169.126:18233 failed after select(): Connection refused (111)
2016-09-13 12:23:33 keypool reserve 4
2016-09-13 12:23:33 keypool return 4
2016-09-13 12:24:13 addcon thread interrupt
2016-09-13 12:24:13 opencon thread interrupt
2016-09-13 12:24:13 scheduler thread interrupt
2016-09-13 12:24:13 net thread interrupt
2016-09-13 12:31:35 
```

So it looks like a network-related problem.

**Comment by artlav** [comment] 2016-09-15 23:34
I'm fairly confident there were no network interruptions that long, they would have been noticed. Also, only one node is affected at a time.

It couldn't have been an internal network interruption for one node in particular, since the controller could reach them all the time.

Finally, after seeing the logs i already tried pulling the wires at random intervals and durations, which failed to reproduce the issue.

**Comment by nathan-at-least** [comment] 2016-10-03 22:08
@artlav, we don't have time to look into this before our launch. If this re-appears for you after launch, can you let us know here? If not, can you comment here so we know it's ok to close this.

**Comment by ioptio** [comment] 2017-07-03 17:28
Closing this ticket since it was filed before launch and user hasn't responded. Feel free to re-open if it's still an issue.

**Closed by ioptio** 2017-07-03 17:28 UTC
Labels: Denial of Service
