### ISSUE TITLE
zcashd: wallet/wallet.cpp:653: void CWallet::IncrementNoteWitnesses(const CBlockIndex*, const CBlock*, ZCIncrementalMerkleTree&): Assertion `(nd->witnessHeight == -1) || (nd->witnessHeight == pindex->nHeight - 1)' failed.

### ISSUE THREAD

**Issue by ucwong** [zcash/zcash#1853] opened 2016-11-14 03:01 UTC
zcashd: wallet/wallet.cpp:653: void CWallet::IncrementNoteWitnesses(const CBlockIndex*, const CBlock*, ZCIncrementalMerkleTree&): Assertion `(nd->witnessHeight == -1) || (nd->witnessHeight == pindex->nHeight - 1)' failed.

**Comment by str4d** [comment] 2016-11-15 01:10
Duplicate of #1715.

**Closed by str4d** 2016-11-15 01:10 UTC
