### ISSUE TITLE
Add buildbot waterfall column for upstream libsnark.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#428] opened 2015-11-12 19:08 UTC
Let's add a waterfall column to our buildbot (http://ci.leastauthority.com:8010/waterfall) for ``libsnark``. Even though we do not own that repository we can set up a polling build config. Later the ``libsnark`` owners can set up a webhook and/or github PR status updates on their repository if they like our service.

This would also allow us to close #78.

**Comment by daira** [comment] 2016-10-24 15:36
This is now a duplicate of #521.

**Closed by daira** 2016-10-24 15:36 UTC
Labels: Continuous Integration, libsnark, special to Nathan, testing
