### ISSUE TITLE
Make "@zkbot try" work

### ISSUE THREAD

**Issue by daira** [zcash/zcash#1287] opened 2016-08-22 08:29 UTC
See https://github.com/zcash/zcash/pull/1268 for an example of it causing problems. I don't understand the exact issue, maybe @ebfull or @defuse can explain.

**Comment by defuse** [comment] 2016-08-24 22:58
It would be super nice if @zkbot try worked, but I'm not sure what the problem is.

**Comment by defuse** [comment] 2016-08-24 23:00
Maybe this is something we should have @arcalinea or @ageis look at?

**Comment by ageis** [comment] 2016-09-06 04:03
The problem is that nobody has been granted "try" rights, only reviewer rights.
```
# who has r+ rights?
reviewers = ["ebfull","nathan-at-least","daira","str4d","bitcartel"]
# who has 'try' rights? (try, retry, force, clean, prioritization)
try_users = []
```
Is it okay to copy the same list to `try_users`?

**Comment by ageis** [comment] 2016-09-07 03:15
This should be set. Can someone initiate a **try** to verify and let me know whether it worked out?

**Comment by ageis** [comment] 2016-09-25 07:09
I see no reason why this shouldn't be working, so I'm closing this issue.

**Closed by ageis** 2016-09-25 07:09 UTC
Labels: Continuous Integration, dev infrastructure
