### ISSUE TITLE
Zcash v4.3.0 build regression

### ISSUE THREAD

**Issue by gituser** [zcash/zcash#5031] opened 2021-03-09 13:15 UTC
Hi! 

I've been building zcash using depends system for a quite a while without any issues but with version `v4.3.0` it seems something is broken:

```
install: installing component 'rust-docs'

    Rust is ready to roll.

Postprocessing native_rust...
Caching native_rust...
Extracting native_b2...
/home/build/zcash/source/depends/sources/boost_1_74_0.tar.bz2: OK
Preprocessing native_b2...
Configuring native_b2...
Building native_b2...

###
###
### Using 'gcc' toolset.
###
###

> g++ --version
g++ (Debian 4.9.2-10+deb8u1) 4.9.2
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


###
###

> g++ -x c++ -std=c++11 -O2 -s -DNDEBUG builtins.cpp class.cpp command.cpp compile.cpp constants.cpp cwd.cpp debug.cpp debugger.cpp execcmd.cpp filesys.cpp frames.cpp function.cpp glob.cpp hash.cpp hcache.cpp hdrmacro.cpp headers.cpp jam.cpp jamgram.cpp lists.cpp make.cpp make1.cpp md5.cpp mem.cpp modules.cpp native.cpp object.cpp option.cpp output.cpp parse.cpp pathsys.cpp regexp.cpp rules.cpp scan.cpp search.cpp jam_strings.cpp startup.cpp subst.cpp sysinfo.cpp timestamp.cpp variable.cpp w32_getreg.cpp modules/order.cpp modules/path.cpp modules/property-set.cpp modules/regex.cpp modules/sequence.cpp modules/set.cpp execunix.cpp fileunix.cpp pathunix.cpp -o b2
> cp b2 bjam
Staging native_b2...
Postprocessing native_b2...
Caching native_b2...
Extracting libcxx...
Preprocessing libcxx...
Configuring libcxx...
Building libcxx...
Staging libcxx...
Postprocessing libcxx...
Caching libcxx...
Building boost...
/bin/sh: 1: b2: not found
funcs.mk:246: recipe for target '/home/build/zcash/source/depends/work/build/x86_64-pc-linux-gnu/boost/1_74_0-a10c17f46ee/./.stamp_built' failed
make: *** [/home/build/zcash/source/depends/work/build/x86_64-pc-linux-gnu/boost/1_74_0-a10c17f46ee/./.stamp_built] Error 127
make: Leaving directory '/home/build/zcash/source/depends'
Configure failed
```

I'm simply using `./zcutil/build.sh -j8` script to build zcash using depends system, `v4.2.0` built successfully on the same platform.

**Comment by gituser** [comment] 2021-03-12 12:02
ping @str4d

**Comment by daira** [comment] 2021-03-25 14:38
Can you post the full build log with `./zcutil/build.sh V=1`, please? (No `-j` option.)

Also, if you have time can you try intermediate commits between 4.2.0 and 4.3.0?

**Comment by daira** [comment] 2021-03-25 14:41
Another thing you could try is to upgrade that fairly old gcc. (gcc is only used for native builds, but it seems like the `native_b2` build is the problem here.)

**Comment by gituser** [comment] 2021-03-25 15:19
@daira I'm using toolchain bundled with depends system it shouldn't be an issue for building as it's more recent than my stock gcc.


>Can you post the full build log with ./zcutil/build.sh V=1, please? (No -j option.)
```
$ ./zcutil/build.sh V=1
+ eval make --version
++ make --version
GNU Make 4.0
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
+ as --version
GNU assembler (GNU Binutils for Debian) 2.25
Copyright (C) 2014 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or later.
This program has absolutely no warranty.
This assembler was configured for a target of `x86_64-linux-gnu'.
+ ENABLE_DEBUG_REGEX='^(.*\s)?--enable-debug(\s.*)?$'
+ [[ '' =~ ^(.*\s)?--enable-debug(\s.*)?$ ]]
+ DEBUG=
+ HOST=x86_64-pc-linux-gnu
+ BUILD=x86_64-pc-linux-gnu
+ make V=1 -C ./depends/ DEBUG=
make: Entering directory '/home/build/zcash/source/depends'
echo Building boost...
Building boost...
mkdir -p /home/build/zcash/source/depends/work/build/x86_64-pc-linux-gnu/boost/1_74_0-a10c17f46ee/.
cd /home/build/zcash/source/depends/work/build/x86_64-pc-linux-gnu/boost/1_74_0-a10c17f46ee/.; PATH="/home/build/zcash/source/depends/x86_64-pc-linux-gnu/native/bin:/home/build/.cargo/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/home/build/go/bin:/home/build/go/go/bin:/home/build/go/bin"   b2 -d2 -j2 -d1 --prefix=/home/build/zcash/source/depends/work/staging/x86_64-pc-linux-gnu/boost/1_74_0-a10c17f46ee/home/build/zcash/source/depends/x86_64-pc-linux-gnu --layout=system --user-config=user-config.jam threading=multi link=static -sNO_COMPRESSION=1 variant=release architecture=x86 address-model=64  target-os=linux threadapi=pthread runtime-link=shared    toolset=clang stage
/bin/sh: 1: b2: not found
funcs.mk:246: recipe for target '/home/build/zcash/source/depends/work/build/x86_64-pc-linux-gnu/boost/1_74_0-a10c17f46ee/./.stamp_built' failed
make: *** [/home/build/zcash/source/depends/work/build/x86_64-pc-linux-gnu/boost/1_74_0-a10c17f46ee/./.stamp_built] Error 127
make: Leaving directory '/home/build/zcash/source/depends'
```

>Also, if you have time can you try intermediate commits between 4.2.0 and 4.3.0?
There seems to be a lot of commits, I'll try to build each one of them and update this issue.

But it's definitely a regression as v4.2.0 builds just fine on the same configuration.

**Comment by gituser** [comment] 2021-03-27 13:35
@daira 

So I checked all commits between v4.2.0 and v4.3.0 and the last successful commit which builds fine is: a0158ce837cff66107126204a0d24d5c5ce22ac9

after this commit, zcash no longer builds.

**Comment by daira** [comment] 2021-03-28 13:44
Thankyou, that's very helpful.

**Comment by gituser** [comment] 2021-04-10 22:54
@daira, any update on this issue?

**Comment by str4d** [comment] 2021-04-13 01:36
If a0158ce837cff66107126204a0d24d5c5ce22ac9 builds fine, then the problem is due to the next PR merged, i.e. the migration to Clang 11 in #4951.

**Comment by str4d** [comment] 2021-04-13 03:39
@gituser could you please confirm that 2de905ce87e7de273d1c4c0884d2ffb7858f3655 does not build for you, but a0158ce837cff66107126204a0d24d5c5ce22ac9 does?

**Comment by gituser** [comment] 2021-04-13 06:56
@str4d 

This is NOT building - 2de905ce87e7de273d1c4c0884d2ffb7858f3655

results in:
```
> g++ -x c++ -std=c++11 -O2 -s -DNDEBUG builtins.cpp class.cpp command.cpp compile.cpp constants.cpp cwd.cpp debug.cpp debugger.cpp execcmd.cpp filesys.cpp frames.cpp function.cpp glob.cpp hash.cpp hcache.cpp hdrmacro.cpp headers.cpp jam.cpp jamgram.cpp lists.cpp make.cpp make1.cpp md5.cpp mem.cpp modules.cpp native.cpp object.cpp option.cpp output.cpp parse.cpp pathsys.cpp regexp.cpp rules.cpp scan.cpp search.cpp jam_strings.cpp startup.cpp subst.cpp sysinfo.cpp timestamp.cpp variable.cpp w32_getreg.cpp modules/order.cpp modules/path.cpp modules/property-set.cpp modules/regex.cpp modules/sequence.cpp modules/set.cpp execunix.cpp fileunix.cpp pathunix.cpp -o b2
> cp b2 bjam
Staging native_b2...
Postprocessing native_b2...
Caching native_b2...
Extracting libcxx...
Preprocessing libcxx...
Configuring libcxx...
Building libcxx...
Staging libcxx...
Postprocessing libcxx...
Caching libcxx...
Building boost...
/bin/sh: 1: b2: not found
funcs.mk:245: recipe for target '/home/build/zcash/source/depends/work/build/x86_64-pc-linux-gnu/boost/1_75_0-1f4fae45849/./.stamp_built' failed
make: *** [/home/build/zcash/source/depends/work/build/x86_64-pc-linux-gnu/boost/1_75_0-1f4fae45849/./.stamp_built] Error 127
make: Leaving directory '/home/build/zcash/source/depends'
Configure failed
```

This builds fine - a0158ce837cff66107126204a0d24d5c5ce22ac9

**Comment by str4d** [comment] 2021-04-14 00:25
@gituser great, thanks.

I was trying to create a patch to check the build environment, and rediscovered an edge case in the depends system: the build environment is only applied to the first command. So e.g. with
```
define $(package)_build_cmds
    printenv && printenv
endef
```
The first `printenv` will show a `PATH` modified to include the native binaries from the depends system (including `b2` in the case of Boost), while the second `printenv` will show the unmodified `PATH`. I wonder if something similar is happening here?

@gituser could you try building with the following patch and returning its output:
```
diff --git a/depends/packages/boost.mk b/depends/packages/boost.mk
index 080c1e9b9..770490afa 100644
--- a/depends/packages/boost.mk
+++ b/depends/packages/boost.mk
@@ -53,6 +53,7 @@ define $(package)_config_cmds
 endef
 
 define $(package)_build_cmds
+  printenv && && printenv && \
   b2 -d2 -j2 -d1 --prefix=$($(package)_staging_prefix_dir) $($(package)_config_opts) toolset=$($(package)_toolset_$(host_os)) stage
 endef

```

**Comment by daira** [comment] 2022-01-09 15:12
@gituser did you get the chance to test @str4d's suggestion?

**Comment by gituser** [comment] 2022-01-09 18:58
@daira, sorry no I didn't get to it.

I've resolved this issue by upgrading to `Debian Stretch`.

**Closed** 2022-04-20 19:07 UTC
Labels: A-build
