### ISSUE TITLE
libsodium 1.0.15 deprecated

### ISSUE THREAD

**Issue by ca333** [zcash/zcash#4238] opened 2019-11-25 12:23 UTC
https://github.com/zcash/zcash/blob/f859ae0067b2703d83376c4a53e8ced9152d026c/depends/packages/libsodium.mk#L3

results in a 404 error - "fixed" by using the `unsupported` URL path
might as well look into using 1.0.18

**Comment by ca333** [comment] 2019-11-25 15:10
Changed https://github.com/zcash/zcash/pull/4239 to update libsodium to v1.0.18

**Comment by daira** [comment] 2019-11-27 11:23
Duplicate of #2872.

**Closed by daira** 2019-11-27 11:23 UTC
Labels: consensus protocol, duplicate
