### ISSUE TITLE
Comment says evict preovewinter nodes, but code evicts according to Sapling activation height

### ISSUE THREAD

**Issue by arielgabizon** [zcash/zcash#3409] opened 2018-07-20 20:37 UTC
https://github.com/zcash/zcash/blob/cd0484e023cdb4f1ba8e6ed284a0a0232ca9a4cf/src/net.cpp#L829
https://github.com/zcash/zcash/blob/cd0484e023cdb4f1ba8e6ed284a0a0232ca9a4cf/src/net.cpp#L831

also wondering if it was supposed to be overwinter in this line
https://github.com/zcash/zcash/blob/master/src/net.cpp#L823

**Comment by daira** [comment] 2018-07-21 06:07
Duplicate of #3338.

**Closed by daira** 2018-07-21 06:07 UTC
Labels: duplicate
