### ISSUE TITLE
Test writing to testnet3 folder?

### ISSUE THREAD

**Issue by bitcartel** [zcash/zcash#1583] opened 2016-10-20 21:58 UTC
Maybe related to ticket #1506 

Ping @str4d I just found a debug.log file on recent newly installed computer.  I don't know what specific test caused this.  From timestamp, the log file was created two days ago.
```
WriteWitnessCache(): Couldn't start atomic write
WriteWitnessCache(): Failed to write CWalletTx, aborting atomic write
WriteWitnessCache(): Unexpected error during atomic write:
Boom
WriteWitnessCache(): Failed to write nWitnessCacheSize, aborting atomic write
WriteWitnessCache(): Unexpected error during atomic write:
Boom
WriteWitnessCache(): Couldn't commit atomic write
```

**Comment by str4d** [comment] 2016-10-20 22:14
That will be caused by `wallet_tests.WriteWitnessCache` in `wallet/gtest/test_wallet.cpp`.

**Comment by daira** [comment] 2016-10-20 23:37
Even though it was written 2 days ago, could it have been written by a version from before #1506 was merged?

**Comment by bitcartel** [comment] 2016-10-20 23:44
I fixed it.  Pushing a PR now.

**Closed** 2016-10-21 07:52 UTC
Labels: has PR, testing
