### ISSUE TITLE
Assertion `uResultHeight == rewindHeight` failed

### ISSUE THREAD

**Issue by defuse** [zcash/zcash#5958] opened 2022-05-13 17:39 UTC
I was trying to run the smoke tests and I somehow managed to get its wallet into a bad state that triggers the following assertion failure. I have a copy of the `.zcash` directory that reproduces this reliably, but unfortunately I can't reproduce it from scratch. 

```
$ ZCASHD=./src/zcashd ZCASHCLI=./src/zcash-cli ./qa/zcash/smoke_tests.py --wallet=wallet.smoketest.dat "$HOME/.zcash" --automate --use-faucet
Start time: 2022-05-13 11:31:03.438752
Starting zcashd...
zcashd: wallet/wallet.cpp:4413: int CWallet::ScanForWalletTransactions(CBlockIndex *, bool, bool): Assertion `uResultHeight == rewindHeight' failed.
^CTraceback (most recent call last):
  File "/home/firexware/zcash/zcash/./qa/zcash/smoke_tests.py", line 735, in <module>
    main()
  File "/home/firexware/zcash/zcash/./qa/zcash/smoke_tests.py", line 691, in main
    zcash.start()
  File "/home/firexware/zcash/zcash/./qa/zcash/smoke_tests.py", line 610, in start
    subprocess.check_call(cli_args, stdout=devnull)
  File "/usr/lib/python3.10/subprocess.py", line 364, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.10/subprocess.py", line 347, in call
    return p.wait(timeout=timeout)
  File "/usr/lib/python3.10/subprocess.py", line 1204, in wait
    return self._wait(timeout=timeout)
  File "/usr/lib/python3.10/subprocess.py", line 1938, in _wait
    (pid, sts) = self._try_wait(0)
  File "/usr/lib/python3.10/subprocess.py", line 1896, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt
```

I'm not sure what I did that might have caused it originally, I definitely re-ran and ctrl+c'd the smoke tests quite a bit it's also possible another node tried to access the same .zcash directory or something.

**Comment by str4d** [comment] 2022-08-01 12:56
#6107 is likely a duplicate of this, which means others outside ECC are also encountering this state.

The crash is occurring during the handling of Orchard rewinds:
https://github.com/zcash/zcash/blob/92b21576e09e2d6a6f7665dfca4ef7fd447e78ec/src/wallet/wallet.cpp#L4694-L4718

Specifically, `orchardWallet.Rewind()` is returning `true`, but is _not_ rewinding to the specified height.

**Comment by docblocxxx** [comment] 2022-08-01 13:31
Today I updated the OS, as well as all the components.
correctly reinstalled via apt
again *removed* all files except zcash.conf with additional parameters
txindex=1
experimentalfeatures=1
insightexplorer=1

After reaching a height of 17*****

and periodic call (5-10 minutes)
zcash-cli stop
sleep..
zcashd -daemon

I stumbled upon it again.

```
2022-08-01T13:00:01.361220Z  INFO main: tor: Thread interrupt
2022-08-01T13:00:01.361254Z  INFO main: torcontrol thread exit
2022-08-01T13:00:01.375764Z  INFO main: addcon thread interrupt
2022-08-01T13:00:01.375764Z  INFO main: scheduler thread interrupt
2022-08-01T13:00:01.375769Z  INFO main: opencon thread interrupt
2022-08-01T13:00:02.643133Z  INFO ProcessNewBlock: main: UpdateTip: new best hash=0000000000ac94332f5ab635f059747bdc1d993b7bed13b3d1cb38c623837493 height=1722978 bits=469885114 log2_work=59.274059 tx=10951222 date=2022-07-02 01:18:56 progress=0.978919 cache=16.4MiB(2649tx)
2022-08-01T13:00:02.643292Z  INFO main: net thread interrupt
2022-08-01T13:00:02.650149Z  INFO main: msghand thread interrupt
2022-08-01T13:00:11.802472Z  INFO main: txnotify thread interrupt
2022-08-01T13:00:11.813070Z  INFO Shutdown: main: StopRPC: waiting for async rpc workers to stop
2022-08-01T13:00:11.813232Z  INFO Shutdown: main: StopNode()
2022-08-01T13:00:12.127723Z  INFO Shutdown: main: done
2022-08-01T13:10:01.332511Z  INFO main:

/////

2022-08-01T13:10:01.332533Z  INFO main: Zcash version v5.2.0 (2022-07-26 09:03:35 -0600)
2022-08-01T13:10:01.332565Z  INFO Init: main: InitParameterInteraction: parameter interaction: -whitelistforcerelay=1 -> setting -whitelistrelay=1
2022-08-01T13:10:01.351029Z  INFO Init: main: Using the 'sse4(1way),sse41(4way),avx2(8way)' SHA256 implementation
2022-08-01T13:10:01.358158Z  INFO Init: main: Using BerkeleyDB version Berkeley DB 6.2.23: (March 28, 2016)
2022-08-01T13:10:01.358166Z  INFO Init: main: Default data directory /root/.zcash
2022-08-01T13:10:01.358170Z  INFO Init: main: Using data directory /root/.zcash
2022-08-01T13:10:01.358177Z  INFO Init: main: Using config file /root/.zcash/zcash.conf
2022-08-01T13:10:01.358183Z  INFO Init: main: Using at most 125 connections (1024 file descriptors available)
2022-08-01T13:10:01.360648Z  INFO Init: main: Using 16 MiB out of 16 requested for signature cache, able to store 524288 elements
2022-08-01T13:10:01.362246Z  INFO Init: main: Using 8 MiB out of 8 requested for Sapling bundle cache, able to store 262144 elements
2022-08-01T13:10:01.363875Z  INFO Init: main: Using 8 MiB out of 8 requested for Orchard bundle cache, able to store 262144 elements
2022-08-01T13:10:01.363894Z  INFO Init: main: Using 4 threads for script verification
2022-08-01T13:10:01.364402Z  INFO main: scheduler thread start
2022-08-01T13:10:01.364426Z  INFO Init: main: Loading Sapling (Spend) parameters from /root/.zcash-params/sapling-spend.params
2022-08-01T13:10:01.364432Z  INFO Init: main: Loading Sapling (Output) parameters from /root/.zcash-params/sapling-output.params
2022-08-01T13:10:01.364435Z  INFO Init: main: Loading Sapling (Sprout Groth16) parameters from /root/.zcash-params/sprout-groth16.params
2022-08-01T13:10:05.284383Z  INFO Init: main: Loading Orchard parameters
2022-08-01T13:10:10.033047Z  INFO Init: main: Loaded proof system parameters in 8.668586s seconds.
2022-08-01T13:10:10.033238Z  INFO Init: main: HTTP: creating work queue of depth 16
2022-08-01T13:10:10.033314Z  INFO Init: main: Config options rpcuser and rpcpassword will soon be deprecated. Locally-run instances may remove rpcuser to use cookie-based auth, or may be replaced with rpcauth. Please see share/rpcuser for rpcauth auth generation.
2022-08-01T13:10:10.033336Z  INFO Init: main: HTTP: starting 4 worker threads
2022-08-01T13:10:10.033447Z  INFO Init: main: Using wallet wallet.dat
2022-08-01T13:10:10.033470Z  INFO Init: main: init message: Verifying wallet...
2022-08-01T13:10:10.033518Z  INFO Init: main: CDBEnv::Open: LogDir=/root/.zcash/database ErrorFile=/root/.zcash/db.log
2022-08-01T13:10:10.034871Z  INFO Init: main: Bound to [::]:8233
2022-08-01T13:10:10.034888Z  INFO Init: main: Bound to 0.0.0.0:8233
2022-08-01T13:10:10.034905Z  INFO Init: main: Cache configuration:
2022-08-01T13:10:10.034911Z  INFO Init: main: * Using 337.5MiB for block index database
2022-08-01T13:10:10.034915Z  INFO Init: main: * Using 36.1MiB for chain state database
2022-08-01T13:10:10.034918Z  INFO Init: main: * Using 76.4MiB for in-memory UTXO set
2022-08-01T13:10:10.034921Z  INFO Init: main: init message: Loading block index...
2022-08-01T13:10:10.034940Z  INFO Init: main: Opening LevelDB in /root/.zcash/blocks/index
2022-08-01T13:10:11.510867Z  INFO Init: main: Opened LevelDB successfully
2022-08-01T13:10:11.512373Z  INFO Init: main: Opening LevelDB in /root/.zcash/chainstate
2022-08-01T13:10:12.510812Z  INFO Init: main: Opened LevelDB successfully
2022-08-01T13:13:06.217917Z  INFO Init: main: LoadBlockIndexDB: last block file = 276
2022-08-01T13:13:06.243332Z  INFO Init: main: LoadBlockIndexDB: last block file info: CBlockFileInfo(blocks=1322, size=130959771, heights=1721658...1722985, time=2022-06-30...2022-07-02)
2022-08-01T13:13:06.243354Z  INFO Init: main: Checking all blk files are present...
2022-08-01T13:13:06.601393Z  INFO Init: main: LoadBlockIndexDB: transaction index enabled
2022-08-01T13:13:06.601449Z  INFO Init: main: LoadBlockIndexDB: insight explorer enabled
2022-08-01T13:13:06.601457Z  INFO Init: main: LoadBlockIndexDB: light wallet daemon disabled
2022-08-01T13:13:07.557362Z  INFO Init: main: LoadBlockIndexDB: hashBestChain=0000000000ac94332f5ab635f059747bdc1d993b7bed13b3d1cb38c623837493 height=1722978 date=2022-07-02 01:18:56 progress=0.978912
2022-08-01T13:13:07.571728Z  INFO Init: main: init message: Rewinding blocks if needed...
2022-08-01T13:13:12.205319Z  INFO Init: main: init message: Verifying blocks...
2022-08-01T13:13:12.205350Z  INFO Init: main: Verifying last 288 blocks at level 3
2022-08-01T13:13:20.908820Z  INFO Init: main: No coin database inconsistencies in last 289 blocks (11187 transactions)
2022-08-01T13:13:20.911665Z  INFO Init: main:  block index          190877ms
2022-08-01T13:13:20.940571Z  INFO Init: main: init message: Loading wallet...
2022-08-01T13:13:21.065047Z  INFO Init: main: nFileVersion = 5020050
2022-08-01T13:13:21.065082Z  INFO Init: main: Keys: 102 plaintext, 0 encrypted, 102 w/ metadata, 102 total
2022-08-01T13:13:21.065092Z  INFO Init: main: ZKeys: 0 plaintext, 0 encrypted, 0 w/metadata, 0 total
2022-08-01T13:13:21.067413Z  INFO Init: main:  wallet                  127ms
2022-08-01T13:13:21.067580Z  INFO Init: main: init message: Rescanning...
2022-08-01T13:13:21.067605Z  INFO Init: main: CWallet::InitLoadWallet(): Rescanning last 3408 blocks (from block 1719570)...
2022-08-01T13:13:21.068357Z  INFO Init: main: CWallet::ScanForWalletTransactions(): Rewinding Orchard wallet to height 1722977; current is 1719570
```
```

lsb_release -a
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
uname -a
Linux * 5.10.0-16-amd64 #1 SMP Debian 5.10.127-2 (2022-07-23) x86_64 GNU/Linux
gcc --version
gcc (Debian 10.2.1-6) 10.2.1 20210110
ld -v
GNU ld (GNU Binutils for Debian) 2.35.2
as --version
GNU assembler (GNU Binutils for Debian) 2.35.2
```

Is it rather strange that besides me, no one is facing this problem?

Today I will try to build from git, and reproduce the situation.

**Comment by yangchou19** [comment] 2022-08-02 02:46
I meet the same problem, when i use "zcash-cli stop" to stop zcash node, and can't restart it. Did anyone solve the problem?

**Comment by docblocxxx** [comment] 2022-08-02 13:34
Yesterday I built from git, under

```
lsb_release -a
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
uname -a
Linux * 5.10.0-16-amd64 #1 SMP Debian 5.10.127-2 (2022-07-23) x86_64 GNU/Linux
gcc --version
gcc (Debian 10.2.1-6) 10.2.1 20210110
ld -v
GNU ld (GNU Binutils for Debian) 2.35.2
as --version
GNU assembler (GNU Binutils for Debian) 2.35.2
```

The node worked up to a height of 173**** stably, periodically calling (every 5-10 minutes)
```

zcash-cli stop
pidof zcashd...
zcash-cli-daemon
```

After reaching a height of 173**** and activating NU5 - the node ended incorrectly, and again led to uResultHeight == rewindHeight

Today I will down to version 5.1.0 in git, and try again.

My knowledge in debugging unfortunately does not allow me to fully identify the problem.
I ask developers to help.

**Comment by docblocxxx** [comment] 2022-08-03 13:20
Version 5.1.0 built from git.
also results in uResultHeight == rewindHeight. after After zcash-cli stop above 173****


I will try to rule out

#txindex=1
#experimentalfeatures=1
#insightexplorer=1

And try again.

**Comment by yangchou19** [comment] 2022-08-04 07:45
> experimentalfeatures=1
> insightexplorer=1

did you solve the problem? I meet it again.

**Comment by docblocxxx** [comment] 2022-08-04 12:50
Unfortunately, I can only temporarily eliminate it with the help of
**zcashd -daemon -rescan**, this works in settings
```
txindex=1
experimentalfeatures=1
insightexplorer=1
```
I also started the node with
```
#txindex=1
#experimentalfeatures=1
#insightexplorer=1
```

and periodically called **zcash-cli stop** and started again - this also led to **uResultHeight == rewindHeight** !

I think it does not depend on these settings.
This is easily reproducible.
This is affected by 5.1.0, 5.2.0, 
5.0.0 - currently being tested.

I will also monitor the node that had -rescan called and the problem is temporary? eliminated.

Please don't call -txindex (I ran into a lot of problems after that)

I think if the developers find the time, they will easily reproduce it.

I keep testing, and various configurations.
I also plan to change some settings on initialization, I'll post it here. if it helps.

**Comment by fluidvanadium** [comment] 2022-10-25 20:21
Same error

`Thank you for running a mainnet zcashd v5.3.0 node!                                                                                                                                                       │
│You're helping to strengthen the network and contributing to a social good :)                                                                                                                             │
│                                                                                                                                                                                                          │
│In order to ensure you are adequately protecting your privacy when using Zcash,                                                                                                                           │
│please see <https://z.cash/support/security/>.                                                                                                                                                            │
│                                                                                                                                                                                                          │
│Since starting this node 48 seconds ago:                                                                                                                                                                  │
│- You have validated 1083 transactions!                                                                                                                                                                   │
│                                                                                                                                                                                                          │
│Init message: Verifying blocks...                                                                                                                                                                         │
│                                                                                                                                                                                                          │
│[Press Ctrl+C to exit] [Set 'showmetrics=0' to hide]                                                                                                                                                      │
│zcashd: wallet/wallet.cpp:4725: int CWallet::ScanForWalletTransactions(CBlockIndex *, bool, bool): Assertion `uResultHeight == rewindHeight' failed.                                                      │
│Aborted (core dumped)   `

**Comment by daira** [comment] 2022-11-09 15:28
This was introduced in #5789. Looking at the logs posted on this ticket, all of them have `CWallet::ScanForWalletTransactions` being called from `CWallet::InitLoadWallet` and are trying to rewind to a point past the latest Orchard wallet checkpoint, so I believe that #6238 will fix this issue.

**Closed** 2022-11-10 19:12 UTC
Labels: C-bug, I-regression, I-fail-to-run
