### ISSUE TITLE
Update zcashd to accommodate ZIP-244 signing changes.

### ISSUE THREAD

**Issue by nuttycom** [zcash/zcash#5491] opened 2022-01-20 15:49 UTC
Update to zcash/librustzcash@81c69dd0a93dcb07bc136d31969f9f8021a5ec48

**Comment by nuttycom** [comment] 2022-01-20 15:53
This blocks #5184 because zcash/librustzcash#475 is based upon it, and that blocks #5469.

**Comment by str4d** [comment] 2022-01-20 22:43
This is no longer a blocker of #5184 (we fixed the upstream ordering problem). This is also a duplicate of #5446.

**Closed by str4d** 2022-01-20 22:43 UTC
