### ISSUE TITLE
z_sendmany can send more funds than expected when selecting coinbase UTXOs

### ISSUE THREAD

**Issue by 5a1t** [zcash/zcash#1662] opened 2016-10-27 02:33 UTC
To reproduce:
Mine multiple UTXOs to a t_addr.
Get total balance at UTXO.
Send total balance - 0.5 TAZ to z_addr.

Expected: Error since UTXO cannot split to a t_addr and z_addr since it has not been sent to a z_addr yet.

Actual: Amount is rounded to nearest UTXO and sent to specified z_addr in two parts.

Result of  z_sendmany 3.934 TAZ from t_addr with 4.43400000 TAZ to empty z_addr (ztZGUn7sJWx27Ne5MJj58xdpgjay6fTjtTumo411qP4cfZaEnscFpZC6sd7eP1JtT2tKmctNvyLZZLoycNhfBTmk1nwzcA6):

zcash-cli z_listreceivedbyaddress ztZGUn7sJWx27Ne5MJj58xdpgjay6fTjtTumo411qP4cfZaEnscFpZC6sd7eP1JtT2tKmctNvyLZZLoycNhfBTmk1nwzcA6
[
    {
        "txid" : "4c8fbe9738f330f7ebc31c710b83742159fe142ab2426938ddd265820fab5982",
        "amount" : 3.93400000,
        "memo" : "f600000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
    },
    {
        "txid" : "4c8fbe9738f330f7ebc31c710b83742159fe142ab2426938ddd265820fab5982",
        "amount" : 0.49990000,
        "memo" : "f600000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
    }
]

Have not tested if behaviour varies with a z_addr not owned by wallet.

**Comment by daira** [comment] 2016-10-27 02:41
Duplicate of #1616, fixed in rc3. Please reopen if this is not fixed.

**Closed by daira** 2016-10-27 02:41 UTC
