### ISSUE TITLE
Verify all code licensing works for us.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#3] opened 2014-11-25 21:13 UTC

**Comment by ebfull** [comment] 2016-01-30 02:37
We need to do a sweep of our libraries and *if* there is any confusion we need to contact a lawyer.

**Comment by str4d** [comment] 2016-09-15 11:37
The references above are all false positives caused by pasted log output :smile:

All code written by us inside this repository falls under the existing MIT license, so that should not be an issue.

Since forking from Bitcoin, we have introduced dependencies on the following libraries (obtained via `git diff 21e58b8e..HEAD depends/packages`):

- `googlemock`
  - We use: https://github.com/google/googlemock/blob/master/googlemock/LICENSE
  - Active repo: https://github.com/google/googletest/blob/master/googlemock/LICENSE
- `googletest`
  - https://github.com/google/googletest/blob/master/googletest/LICENSE
- `libgmp`
  - Since v6, dual licensed under [GNU LGPL v3](https://www.gnu.org/licenses/lgpl.html) and [GNU GPL v2](https://www.gnu.org/licenses/gpl-2.0.html).
  -  We use 6.0.0a, so can use GNU LGPL v3, but we need to check the requirements around making the source code we use available if we are distributing binaries. I think this is technically covered because the dependency system we provide in our source code pulls in the source code for dependencies?
- `libsnark`
  - https://github.com/scipr-lab/libsnark/blob/master/LICENSE
- `libsodium`
  - [ISC License](https://github.com/jedisct1/libsodium/blob/master/LICENSE)

**Comment by daira** [comment] 2016-09-15 12:27
LGPL via the depends system should be okay. To make absolutely sure we can add a brief note in our licence saying that libgmp is LGPL. The other non-MIT licences are definitely compatible with MIT.

**Comment by daira** [comment] 2016-09-16 02:54
To comply with the LGPLv3 for libgmp we need to:

a) Give prominent notice with each copy of the Combined Work that the Library is used in it and that the Library and its use are covered by this License.
b) Accompany the Combined Work with a copy of the GNU GPL and this license document.
c) For a Combined Work that displays copyright notices during execution, include the copyright notice for the Library among these notices, as well as a reference directing the user to the copies of the GNU GPL and this license document.

(The other requirements are already met by the depends system.)

**Comment by daira** [comment] 2016-09-16 02:57
It's actually quite confusing that you should have to include a copy of the GPL when nothing used by Zcash is covered by that licence, but that's what the terms of the LGPL say.

**Comment by ebfull** [comment] 2016-09-16 06:40
FYI I thought that libsecp256k1 was bundled with (optionally?) libgmp. Perhaps we can learn from their example.

**Comment by daira** [comment] 2016-09-16 10:21
libsecp256k1 [does use libgmp](https://github.com/bitcoin-core/secp256k1/blob/master/src/num_gmp_impl.h), but I see no reference to that in its licencing documentation.

**Comment by daira** [comment] 2016-09-16 10:29
http://programmers.stackexchange.com/a/302435/34924

**Comment by daira** [comment] 2016-09-29 12:25
This is not needed for beta 2. @nathan-at-least shall we move it to the rc1 milestone?

**Comment by str4d** [comment] 2016-10-01 07:00
BDB 6.X is released under the AGPL, so we can't use it without relicensing the entire project as AGPL. So we need to only upgrade to 5.X in order to keep the same licensing as used by Bitcoin (see https://github.com/zcash/zcash/pull/1429#issuecomment-250896180).

**Comment by bitcartel** [comment] 2016-10-21 21:44
@daira Have reviewed. Required licenses are in `contrib/DEBIAN/copyright`.  To close this ticket, shall we save them as individual license files and place them in a folder?  e.g. /contrib/licenses or /licenses ?

**Comment by ageis** [comment] 2016-10-21 22:20
I dunno if we should duplicate stuff. Maybe just put a note/pointers to where they are in `COPYING` and/or `README.md`

**Comment by daira** [comment] 2016-10-21 23:17
-1 on duplicating stuff; referencing ``contrib/DEBIAN/copyright`` is fine.

**Comment by daira** [comment] 2016-10-23 02:10
Fixed by #1611.

**Closed by daira** 2016-10-23 02:10 UTC
Labels: in 1.0, task
