### ISSUE TITLE
Peers ban when loading pre-overwinter blocks

### ISSUE THREAD

**Issue by ichthuss** [zcash/zcash#3399] opened 2018-07-18 06:02 UTC
Summay: While loading pre-overwinter part of blockchain, peers are getting constantly banned by the daemon because transactions that they relay are considered invalid.

Zcash Daemon version v1.1.2, installed from debian repo.
Upgraded from Zcash Daemon v1.0.14.

Detailed description: I haven't run my zcashd since May 2018. Initial chain loading had worked well with v1.0.14, and blockchain was consistent as of May 5th when it was ran the last time. I now (18 Jul 2018) upgraded it to current version (1.1.2), and ran it to load blockchain for last three months. However, while loading process itself works well, new transactions relayed through network make daemon think that their peers are misbehaving (sending overwinter transactions in a pre-overwinter network), so eventually all of them are get banned, and blockchain loading stucks.

Related log fragment:

2018-07-18 05:18:40 ERROR: ContextualCheckTransaction(): overwinter is not active yet
2018-07-18 05:18:40 ERROR: AcceptToMemoryPool: ContextualCheckTransaction failed
2018-07-18 05:18:40 Misbehaving: 82.196.7.218:8233 (30 -> 40)

**Comment by str4d** [comment] 2018-07-18 16:52
Related: #3393 and #3394.

**Comment by zookozcash** [comment] 2018-07-21 05:34
I don't think it is a good idea to ban peers just because they're giving you invalid transactions.

**Comment by daira** [comment] 2018-07-21 14:43
The banning was put in place to mitigate a class of DoS attacks that were happening against Bitcoin (or at least, that the Bitcoin devs were concerned about). Let's not make hasty changes that could cause a regression of DoS resistance if we get it wrong. OTOH, I tend to think that this banning is actually useless against DoS.

**Comment by bitcartel** [comment] 2018-07-25 21:47
A quick solution which should work is:

To see the peers which have been banned:
`zcash-cli listbanned`

To unban the peers:
zcash-cli clearbanned

I haven't tried this, so I don't know if you need a restart or not to resume downloading blocks.

@ichthuss Let us know if this helps.  Thanks.

**Comment by ichthuss** [comment] 2018-07-25 21:53
> A quick solution which should work is:
> 
> To see the peers which have been banned:
> `zcash-cli listbanned`
> 
> To unban the peers:
> zcash-cli clearbanned
> 
> I haven't tried this, so I don't know if you need a restart or not to resume downloading blocks.
> 
> @ichthuss Let us know if this helps.  Thanks.

Daemon restart helps on its own. When daemon is started, it works well for 10-15 minutes before all peers become banned. So I just wrote script that restarted daemon every 15 minutes, and it successfully 
synced past Overwinter hard fork. I will try 'clearbanned' command to know if it works without daemon restart, but I need to move all downloaded blocks from .zcash data dir.

**Comment by ichthuss** [comment] 2018-07-25 22:43
I tried it and it indeed works well.

**Comment by daira** [comment] 2018-08-16 09:40
This should have been fixed by #3410. Please reopen if you're still seeing this behaviour in 2.0.0.

**Closed by daira** 2018-08-16 09:40 UTC
Labels: networking, usi
