### ISSUE TITLE
2-day delay in mining a transaction with 586 transparent inputs

### ISSUE THREAD

**Issue by Karlmaster2k3** [zcash/zcash#2668] opened 2017-10-17 17:45 UTC
Hello Guys,

i got a big problem.

I send from cryptonator 6.x ZEC to my hardware ledger wallet, after 30Hours its dont confirmed in my wallet.

<a href="https://www.pic-upload.de/view-34115934/zec2.jpg.html" target="_blank"><img src="https://www2.pic-upload.de/thumb/34115934/zec2.jpg" title="Bilder oder Fotos hochladen"></a>

Transaction ID : 821810a34670614f645e8775337da8b6a952642369308df8bdc27178e7455730

<a href="https://www.pic-upload.de" target="_blank"><img src="https://www2.pic-upload.de/img/34115932/LEDGER.jpg" title="Bilder oder Fotos hochladen"></a>

Yesterday i found the transaction id there:
https://zcashnetwork.info/tx/821810a34670614f645e8775337da8b6a952642369308df8bdc27178e7455730
At this morning, the transaction id wasnt found with that link/id.
Now 8Hours later, i see the transaction id at that link, but with a other date and time.
Okay, i found out, that the date and time are from load at the moment is. 

<a href="https://www.pic-upload.de" target="_blank"><img src="https://www2.pic-upload.de/img/34115933/PM.jpg" title="Bilder oder Fotos hochladen"></a>

Normaly the transactions need max 10-15 Minutes.

I send 3 Zec from my hardware ledger wallet to a exchange and there is too not confirmed near 24 Hours.

Fee is on 0.0001 ZEC

Can me explain some one, what i have to do, or whats going on here?

I opened a ticket today on cryptonator, but i think they dont can do something.

I am mining self ZEC, can i mine my transaction self?

Umpf, i am confused.

Thats my wallet address
https://zcashnetwork.info/address/t1JQ2YxhbKpd8npsSKwyuMiYH7WT6SECAUG

I know, it gives much more peoples like me, if you see the unconfirmed transactions
https://minergate.com/blockchain/zec/transpool

Best Regards
Karlmaster

**Comment by ucwong** [comment] 2017-10-18 07:34
https://explorer.zcha.in/accounts/t1JQ2YxhbKpd8npsSKwyuMiYH7WT6SECAUG

**Comment by daira** [comment] 2017-10-18 13:24
This transaction was mined at Oct 18, 2017 10:46:19 AM in block 203899.

**Comment by Karlmaster2k3** [comment] 2017-10-18 21:45
Hello and sorry for my panic Thread,

but can explain me some one, why that transactions does need 2 Days ?

Thanks

**Comment by daira** [comment] 2017-10-18 22:10
That transaction has [586 inputs](https://minergate.com/blockchain/zec/transaction/821810a34670614f645e8775337da8b6a952642369308df8bdc27178e7455730), which is abnormally high. Due to a design flaw in Bitcoin inherited by Zcash, the verification cost of a transaction is roughly proportional to the *square* of the number of inputs. Hence, many miners/pools are configured not to allow transactions with this many inputs to enter their mempools. The transaction therefore has to wait until a mining pool that is not so configured wins a block.

**Comment by daira** [comment] 2017-10-18 22:18
The only adequate long-term fix for this is to solve the performance design flaw, but that will require careful design and a hard fork. There are various less effective mitigations that we can consider in the meantime.

**Comment by nathan-at-least** [comment] 2017-10-18 23:31
Another user had a similar problem and brought it up in [`#zcash`](https://chat.zcashcommunity.com/channel/zcash). This other user was using `zcash4mac` (so I assume a GUI). I want to point out multiple usability pain points here:

- Users can't easily predict how many txins any given request will require.
- Users can't easily tell how many txins are actually used. For example, blockchain explorers don't describe this, as far as I can tell. Many users rely on those and GUIs instead of a low-level thing like `zcash-cli gettransaction <TXID>`.
- Once such a transaction is generated, there's no easy way for a user to cancel it. (*)
- Once such a transaction is generated, there's no easy way to predict how long it takes to mine. The users in this ticket chat channel reported 2 days and >24 hours, respectively.

I'm going to file a couple of new feature requests to help with this case…

(*) An advanced way to get out of that situation might be to forget the offending transaction locally, then try to reissue a new txn that doublespends one of the inputs, then try to get that new transaction propagated to a miner. https://github.com/zcash/zcash/issues/2482 could help in this case. But no user should be expected to jump through these kind of shenanigans, and this would only be useful as an emergency measure by dedicated users.

**Comment by nfedoseev** [comment] 2017-11-06 03:01
Hi.
I have a similar problem.

Some days ago i'm made transaction: 
![default](https://user-images.githubusercontent.com/4405149/32423386-29f73a6e-c2b7-11e7-925d-f34a168d1892.png)
![default](https://user-images.githubusercontent.com/4405149/32423527-eeec2b68-c2b7-11e7-92b2-54874c67bc32.png)


But now (06.11) this transaction isn't confirmed at destination service:
![default](https://user-images.githubusercontent.com/4405149/32423464-8cfba7f8-c2b7-11e7-8f5a-058a8b42fe34.png)


And i see minus balance at destination service https://explorer.zcha.in/accounts/t1aDWp2qjG68xJ2RjBmuY932bGWCccKNP2j and unable to view transaction page: https://explorer.zcha.in/transactions/34c83b098749c26187381c2da3925f6fc73a9577fb6393c8c869192fbabd9a63

However you can see details at another service: https://zcashnetwork.info/tx/34c83b098749c26187381c2da3925f6fc73a9577fb6393c8c869192fbabd9a63

Can you explain it and help me?

**Comment by cosmicog** [comment] 2018-02-24 21:30
I've seen 1177 transparent addresses in one [transaction](https://explorer.zcha.in/transactions/0a0ad15c63289b8b5299de90ca7c05b7a9ccf507a1594265eac63f31919d363c). Why you guys allowing that much for just one transaction? Does it really need a million+ confirmations?

**Comment by str4d** [comment] 2018-02-26 15:21
@nfedoseev the transaction you linked was mined into a block. If your balance wasn't being updated, you should contact the destination service to ask them (as it would be caused by their local node being out-of-sync).

@cosmicog 1177 transparent outputs in a single transaction is perfectly fine - there's almost no performance cost of additional outputs. This issue is about transactions with many inputs. The transaction you linked was mined shortly after it was created, so as above, any delay with the funds appearing in the destination address are due to the recipient's local node being out-of-sync.

**Comment by cosmicog** [comment] 2018-02-26 15:29
@str4d Okay sorry, my bad, I'm newbie in cryptocurrencies and was struggling with transaction basics. Thanks for the explanations. I thought it needs a million+ confirmations :sweat_smile: I'm gonna edit my comment, It's so embarrassing :sweat_smile: :joy:

**Comment by daira** [comment] 2018-07-31 08:37
The original problem is not likely to reoccur (at least not for the same reason) given that Overwinter has activated, and the limit on number of inputs for a transaction to be mined has been removed.

**Closed by daira** 2018-07-31 08:37 UTC
Labels: tx propagation/mining latency
