### ISSUE TITLE
Update zcash for bitcore - Sapling support

### ISSUE THREAD

**Issue by andrey-bienko-iq** [zcash/zcash#3459] opened 2018-08-13 13:20 UTC
Hello
bitcore fork stil uses zcash v1.1.0.
Please update zcash for bitcore to latest binary.

**Comment by ioptio** [comment] 2018-08-13 18:11
This is the latest version of the library: https://github.com/zcash-hackworks/bitcore-node-zcash

It doesn't support Sapling yet but does support Overwinter.

**Comment by radix42** [comment] 2018-08-28 19:26
SOMEONE is running a testnet node on a Digital Ocean IP that identifies
itself as being subver

"/MagicBean:2.0.0(bitcore)/"

Any idea who that is, @str4d ?

**Comment by LeBleu89** [comment] 2018-10-08 20:18
Hello,
I'm trying to prepare https://explorer.zcashfr.io for Sapling and I have tested to install latest insight component from zcash-hackworks. Problem is zcash-pateched-for-explorer seems not fully compatible with insight-api-zcash. There is an issue with block listing and chart. When I replace it by wo01 version (https://github.com/wo01/zcash/tree/bitcore) everything seems OK.
Is it planed to fix https://github.com/zcash-hackworks/zcash-patched-for-explorer ?

**Comment by jmunson** [comment] 2018-10-11 20:45
> They work mostly.
 @wo01  could you elaborate on that a bit? Whats broken, and are you actively working on those things or is fixing them out of scope for the work you're doing?

Also, thank you for your effort, it's nice to know insight users are not being left behind

**Comment by wo01** [comment] 2018-10-12 09:50
"They work mostly" means that I don't test them much.
But, there is no problem for now.

**Comment by LitecoinZ** [comment] 2019-01-08 14:59
@bitcartel please enable the issue tab on https://github.com/zcash-hackworks/bitcore-lib-zcash

I have an issue with it because V4 transactions are not created correctly due a bad signature. Sapling require a different signature way. See https://github.com/zcash/zips/blob/master/zip-0243.rst for details.

Thanks
Mark

**Comment by daira** [comment] 2019-01-08 15:59
It's intentional that the issue tracker is disabled there; please report issues here, where we're more likely to notice them (and where we can track them in the User Support project etc.)

**Comment by LitecoinZ** [comment] 2019-01-08 17:16
ok @daira so, the issue is that bitcore-lib-zcash is non compatible with sapling because it still generate old signature on Transaction.sign. 

Works on V2 and V3 Transaction.sign but not on V4.

Thanks for helping to fix this lib.

**Comment by LarryRuane** [comment] 2019-01-10 17:58
Within the next few days, I will work on fixing the V4 transaction signature problem.

**Comment by LitecoinZ** [comment] 2019-01-10 18:45
ok @LarryRuane 
Please take a look also to this issue: https://github.com/zcash/zcash/issues/3776

**Comment by LitecoinZ** [comment] 2019-01-14 00:11
any update?

**Comment by braddmiller** [comment] 2019-01-15 17:38
This ticket was originally about updating the library to v2.0.2, which is done, signing transactions is something else so I'll close this issue and refer people to #3776 for v4 transaction signing.

**Closed by braddmiller** 2019-01-15 17:38 UTC
Labels: usi
