### ISSUE TITLE
Partial balance temporarily shown after transaction on a fully synced node

### ISSUE THREAD

**Issue by solardiz** [zcash/zcash#3746] opened 2018-12-20 15:42 UTC
### Describe the issue

Shortly upon sending funds to a third-party (not an address in the same wallet), the RPC commands' reported remaining balance does not include some other (past and unrelated) transactions for a while, then restores to normal.

### Can you reliably reproduce the issue?

This is at least somewhat reproducible since I saw it happen several times already on Zcash mainnet (running a 2.0.2-rc1 node) and on a (yet non-public) Zcash fork's testnet (forked off a similar Zcash revision).

#### If so, please list the steps to reproduce below:

1. Start with a fully synced Zcash 2.0.2-rc1 node and some funds in its local wallet. Take note of the balance on a specific address (to send funds from) and total balances.

2. Send a portion of the funds to a third-party (not an address in the same wallet). The most recently observed example involved sending from a Sapling zaddr to a taddr, but IIRC the issue isn't limited to that combination of address types.
 
3. Check the balances - they remain the same until a block is mined.

4. Check the balances again after a block is mined. If the issue is triggered, they will mysteriously not include some other past transactions (from way prior to step 1 above), as well as the most recent outbound transfer. In other words, the balance of the sending address will appear to be what it actually was a long time ago (way before step 1). The totals will agree with that.

5. Repeat step 4 for a while. After a little while - quite possibly consistent with mining yet another block - the reported balances become correct and up to date (just step 1's initial balance minus the recent transfer and fee amounts).

### Expected behaviour

I'd expect the correct balance to always be seen right away at step 4.

### Actual behaviour + errors

Here's some detail on a recent occurrence of the issue described above:

```
$ ./zcash-cli z_getbalance zs[redacted]
3[redacted]
$ ./zcash-cli z_sendmany zs[redacted] '[{"address": "t[redacted]", "amount": "[redacted]"}]'
opid-[redacted]
$ ./zcash-cli z_getbalance zs[redacted]
3[redacted]

After a minute or so:

$ ./zcash-cli z_getbalance zs[redacted]
0.8[redacted]
$ ./zcash-cli z_getbalance zs[redacted]
0.8[redacted]
$ ./zcash-cli z_getbalance zs[redacted]
0.8[redacted]
$ ./zcash-cli z_getbalance zs[redacted]
0.8[redacted]
$ ./zcash-cli z_getbalance zs[redacted]
0.8[redacted]
$ ./zcash-cli z_gettotalbalance 
{
  "transparent": "0.00",
  "private": "0.8[redacted]",
  "total": "0.8[redacted]"
}

After another minute or so:

$ ./zcash-cli z_getbalance zs[redacted]
2[redacted]
$ ./zcash-cli z_gettotalbalance 
{
  "transparent": "0.00",
  "private": "2[redacted]",
  "total": "2[redacted]"
}
```

Here, the `2[redacted]` balance is the correct outcome of taking the transfer amount from the initial `3[redacted]` balance. The temporarily seen `0.8[redacted]` balance is exactly what was on the Sapling address a long time ago, before some incoming transfer increased it to above `3[redacted]` and some other outgoing transfers decreased it to `3[redacted]` - in other words, that balance is missing one incoming and several outgoing transfers.

### The version of Zcash you were using:

```
Zcash Daemon version v2.0.2-rc1-aae4b57
```

### Machine specs:

I've seen this happen on different Linux distros, Zcash or its fork built with different versions of gcc, and running on different hardware (both bare metal and VM).

### Any extra information that might be useful in the debugging process.

For the above opid, `~/.zcash/debug.log` shows the usual `z_sendmany finished (status=success, txid=` line. No errors nearby.

### Do you have a backup of `~/.zcash` directory and/or take a VM snapshot?

Not from prior to triggering the issue.

**Comment by ioptio** [comment] 2019-01-07 19:11
If you try using minconf=0 in the `z_gettotalbalance` command do you still see the wrong balance?

**Comment by tromer** [comment] 2019-01-08 02:00
Duplicate of #1962?

The description here says that the balance drops when the new transaction is _mined_, whereas #1962 (which I've just re-tested) says that the balance drops as soon as the transaction is _generated_.   @solardiz, are you sure the description here is correct? (You can repeat with the node disconnected from the network, to prevent the new transaction from being mined, and see if the balance still drops.)

Ping @lindanlee: this is an example of the "available funds" UX issue.

**Comment by ioptio** [comment] 2019-01-14 19:16
We recommend the test that @tromer suggested anyway because it gives us more information.

**Comment by ioptio** [comment] 2019-01-21 19:10
@solardiz let us know if you've gotten around to the above.

**Comment by solardiz** [comment] 2019-02-04 20:38
@ioptio Not yet, sorry. I intend to play with it more on Zcash mainnet on a suitable occasion, but I'm not happy about accessing my normally "cold" filesystem with that for a testing-only purpose. So next time I need to do a transfer. Meanwhile, I could play with this more on a Zcash fork, but I think Zcash proper results would be more valuable to you.

**Comment by solardiz** [comment] 2019-04-02 20:45
I finally proceeded to reproduce this issue on the latest Zcash codebase as of today. Reproduced it from the first try. It appears that you were correct: the issue shows up when the transaction is generated, and goes away when it is mined.

Specifically, right after issuing the `z_sendmany` command and for ~1 second after that, the original pre-transaction balance is shown with both `z_gettotalbalance` and `z_gettotalbalance 0`. However, ~1 second later `z_gettotalbalance` starts showing a balance lacking many past transactions, whereas `z_gettotalbalance 0` starts showing the correct post-transaction balance. This persists until a block is mined, at which point both start showing the correct post-transaction balance.

**Comment by solardiz** [comment] 2019-04-02 20:56
Also, in today's test the network block height didn't change during that ~1 second, which confirms that my initial understanding/guess was wrong. I must have confused the slowness in generating the transaction (which is probably what happened in the case I reported in here initially) for having a block mined shortly after the transaction was generated (such mining probably didn't happen until much later, which is probably what corrected the balance display).

So I guess this is a duplicate of #1962.

**Comment by ioptio** [comment] 2019-04-15 18:11
Let's close this as a duplicate of #1962, then.

**Closed by ioptio** 2019-04-15 18:11 UTC
Labels: duplicate
