### ISSUE TITLE
Ensure none of the `assert()` in libzerocash are "bad."

### ISSUE THREAD

**Issue by defuse** [zcash/zcash#520] opened 2015-12-15 22:18 UTC
Make sure the asserts are only checking locally-verifiable properties. Change anything else to an exception throw.

```
[firexware@firexware-pc libzerocash]$ ack assert libzerocash tests zerocash_pour_ppzksnark/
libzerocash/PourTransaction.cpp
254:    assert(ciphertext_1_internals.size() == (ZC_V_SIZE + ZC_R_SIZE + ZC_RHO_SIZE));
272:    assert(ciphertext_2_internals.size() == (ZC_V_SIZE + ZC_R_SIZE + ZC_RHO_SIZE));

libzerocash/serialize.h
10:#include <assert.h>

libzerocash/streams.h
13:#include <assert.h>
126:        assert(last - first >= 0);
140:        assert(last - first >= 0);
242:        assert(nSize >= 0);

libzerocash/ZerocashParams.cpp
132:    assert(p_pk_1 != NULL || p_vk_1 != NULL);

libzerocash/allocators.h
37:        assert(!(page_size & (page_size - 1))); // size must be power of two
43:        assert(this->GetLockedPageCount() == 0);
80:            assert(it != histogram.end()); // Cannot unlock an area that was not locked

zerocash_pour_ppzksnark/tests/test_zerocash_pour_ppzksnark.cpp
28:    assert(log2(value) < length);
51:    assert(log2(num_positions) <= log2_universe_size);
52:    assert(log2_universe_size <= 8 * sizeof(size_t));
136:    assert(log2(num_old_coins) <= tree_depth);
274:    assert(pb.is_satisfied());
308:    assert(verification_result);

zerocash_pour_ppzksnark/zerocash_pour_ppzksnark.tcc
167:    assert(pb.is_satisfied());

zerocash_pour_ppzksnark/zerocash_pour_gadget.tcc
75:    assert(input_as_bits.size() == input_size_in_bits);
426:    assert(merkle_tree_root.size() == sha256_digest_len);
427:    assert(old_coin_serial_numbers.size() == num_old_coins);
430:        assert(old_coin_serial_number.size() == serial_number_length);
432:    assert(new_coin_commitments.size() == num_new_coins);
435:        assert(new_coin_commitment.size() == coin_commitment_length);
437:    assert(public_value.size() == coin_value_length);
438:    assert(signature_public_key_hash.size() == sha256_digest_len);
439:    assert(signature_public_key_hash_macs.size() == num_old_coins);
442:        assert(signature_public_key_hash_mac.size() == sha256_digest_len);
```

From #493.

**Comment by ebfull** [comment] 2016-03-14 03:11
Duplicate of #69.

**Closed by ebfull** 2016-03-14 03:11 UTC
Labels: error handling, in 1.0, libzerocash
