### ISSUE TITLE
Upgrade all dependencies (as necessary).

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#1393] opened 2016-09-13 22:17 UTC
Let's upgrade dependencies in a focused effort. If upgrading multiple dependencies doesn't immediately work, try to isolate the working upgrades into a PR and merge it early to make forward progress.

**Comment by ageis** [comment] 2016-09-13 22:42
When dependency updates are merged, please notify me and ideally send me a link so I can make sure it's added to the `depends-sources` mirror.

**Comment by str4d** [comment] 2016-09-22 12:50
Duplicate of #867.

**Closed by str4d** 2016-09-22 12:50 UTC
Labels: dependencies, invalid
