### ISSUE TITLE
Crash due to inconsistent wallet state and node chainstate

### ISSUE THREAD

**Issue by ebfull** [zcash/zcash#5805] opened 2022-04-01 20:51 UTC
I was synced beyond NU5 activation on our private testnet, with Orchard notes in my wallet, when my node crashed (due to an unrelated bug). When I start my node back up, it says

```
2022-04-01T20:36:20.314998Z  INFO Init: main: LoadBlockIndexDB: hashBestChain=002562758fe265f8015eeac0ea5185fff847048d631bbd3dd11af05f8864a9b9 height=1813499 date=2022-03-29 22:21:40 progress=0.999090
```

Height 1813499 is the block before NU5 activation on this testnet.

The node then proceeds to initialize the wallet, skipping over ScanForWalletTransactions, and eventually ThreadNotifyWallets calls CWallet::ChainTip on the NU5 block. However, the Orchard wallet state is way ahead of this (by like 3000 blocks) so it crashes with an assertion when `orchardWallet.CheckpointNoteCommitmentTree` is called because the heights differ.

**Comment by str4d** [comment] 2022-04-01 21:11
@ebfull and I dug into this, and confirmed that `SetBestChain` was not to blame here; the Orchard wallet's state being that far ahead of chain tip was because the wallet's `bestBlock` locator was also at that height.

I think the problem here is that we are encountering a situation we'd hoped to avoid (by not supporting imports of Orchard viewing keys initially): the node's chain state is behind the wallet's chain state.

Here's what things look like under normal circumstances:
- The node writes out its chain state something like hourly:
  https://github.com/zcash/zcash/blob/9befdb2c457b43d8d46b93ac9168db914703e222/src/main.cpp#L3591-L3600
  https://github.com/zcash/zcash/blob/9befdb2c457b43d8d46b93ac9168db914703e222/src/main.cpp#L3631-L3644
- The wallet writes out its chain state every 10 minutes:
  https://github.com/zcash/zcash/blob/9befdb2c457b43d8d46b93ac9168db914703e222/src/wallet/wallet.cpp#L1424-L1436
- On graceful shutdown, the node writes out its chain state, while the wallet only flushes its pending writes:
  https://github.com/zcash/zcash/blob/9befdb2c457b43d8d46b93ac9168db914703e222/src/init.cpp#L223-L239
  https://github.com/zcash/zcash/blob/9befdb2c457b43d8d46b93ac9168db914703e222/src/wallet/wallet.cpp#L1712-L1715

In @ebfull's case, the assertion triggered an immediate process abort, meaning no state was flushed on shutdown. That means the node's and wallet's respective best chain state were at whatever they had happened to last write, and the node's was significantly older than the wallets because it writes out that state less frequently.

When Orchard support was added to `ScanForWalletTransactions`, it was assumed that the wallet chain state would never be ahead of the node chain state, so we only needed to handle rewinds (and even then, we only supported rewinds up to a point, depending on where notes had been witnessed). As it is, we need the ability to "rescan" from arbitrary past points in the chain, which is precisely what we need for UFVK importing, but now also for recovering nicely from node crashes.

To rescan arbitrarily, we need the ability to graft an Orchard Merkle tree onto an existing one, and then we need to actually start the rescan from the most recent witnessed note prior to the rescan point (so the bridges line up for grafting). Then during `ScanForWalletTransactions` we'd witness at all the notes we already know about, in addition to any new notes we discover.

This doesn't need to block 4.7.0, because wallets can recover from this situation with a manual `-rescan`.

**Comment by str4d** [comment] 2022-04-01 22:15
Aha, I've actually found a different bug that I believe is the real cause of @ebfull's crash: we're initialising `ThreadNotifyWallets` incorrectly.

https://github.com/zcash/zcash/blob/9befdb2c457b43d8d46b93ac9168db914703e222/src/init.cpp#L1713-L1729

Specifically, this comment makes the same incorrect assumption as I described in my above comment:
> We perform this before step 10 (import blocks) so that the original value of chainActive.Tip(), which corresponds with the wallet's view of the chaintip, is passed to ThreadNotifyWallets before the chain tip changes again.

That is, it assumes that the last chain tip notified to the wallet is equal to the node chain tip at startup, when it should instead use the chain tip stored in the wallet's `bestBlock` at startup. Fixing this would ensure that in a scenario like @ebfull's we would properly rewind (and trigger the 100-block limit assertion) instead of trying to incorrectly append (and triggering the non-sequential increment assertion). Then, we could reposition where we initialise `ThreadNotifyWallets` to allow the node to finish reloading already-downloaded blocks from disk, with the aim of reducing the delta between the wallet and chain's states (and thus avoiding the 100-block limit assertion).

**Comment by therealyingtong** [comment] 2022-04-06 00:04
Closed by https://github.com/zcash/zcash/pull/5809.

**Closed by therealyingtong** 2022-04-06 00:04 UTC
Labels: C-bug, A-wallet, I-fail-to-run, A-chain-sync, A-orchard
