### ISSUE TITLE
Sometimes parameter load path is unexpectedly ``~/.zcash-params/$FILENAME`` with no network name.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#659] opened 2016-01-22 17:10 UTC

**Comment by defuse** [comment] 2016-01-29 02:13
#689 is a duplicate of this. You can see the evidence that it really happens in that tickets. I'm guessing it's a byproduct of using one of those command-line arguments.

**Comment by defuse** [comment] 2016-02-05 23:58
tite12354 on IRC had this problem, too.

**Comment by nathan-at-least** [comment] 2016-02-10 23:32
After a fair amount of debugging, we believe the issue is that ``ZC_LoadParams`` is called prior to commandline parsing. This is also why the "loading parameters" log entries don't appear.

A fix is to load the parameters after commandline parsing, while also early enough to avoid the race condition bug that moved them there in the first place.

**Comment by ebfull** [comment] 2016-02-11 03:55
I agree, moving LoadParams before blockchain verification but after command line parsing should be fine. I think we should document the motivation behind the ordering in case we run into a similar issue later.

**Comment by nathan-at-least** [comment] 2016-02-11 18:49
After attempting to reproduce the issue either with the current ``zc.v0.11.2.latest`` revision (which calls ``ZC_LoadParams`` immediately at the start of ``AppInit2``) or a local tweak to load parameters after CLI parsing, we were unable to reproduce the issue.

So that hypothesis is suspect. There is either a race condition or some file system condition (or some network condition?) that triggers this bug that we couldn't reproduce.

**Comment by str4d** [comment] 2016-06-09 11:38
#942 is a different user issue with the same underlying cause. See [#942 (comment)](https://github.com/zcash/zcash/issues/942#issuecomment-223503765) for my analysis.

**Comment by ebfull** [comment] 2016-08-30 18:02
This will be addressed by #1312 (the paths are changing).

**Closed by ebfull** 2016-08-30 18:02 UTC
Labels: bug, in 1.0, special to Nathan, usability, zkSNARK Parameter Deployment
