### ISSUE TITLE
Update from Berkeley DB  v4.8 to latest release (v6.2.23)

### ISSUE THREAD

**Issue by rcseacord** [zcash/zcash#1257] opened 2016-08-16 01:30 UTC
Inherited from upstream Bitcoin, see doc/build-unix.md.  Upstream version of this doc has a bit more info: "Ubuntu and Debian have their own libdb-dev and libdb++-dev packages, but these will install BerkeleyDB 5.1 or later, which break binary wallet compatibility with the distributed executables which are based on BerkeleyDB 4.8. If you do not care about wallet compatibility, pass --with-incompatible-bdb to configure." https://github.com/bitcoin/bitcoin/blob/master/doc/build-unix.md#berkeley-db

The upgrade procedures required depend on whether or not the release is a major or minor release (in which either the major or minor number of the version changed), or a patch release (in which only the patch number in the version changed). Berkeley DB major and minor releases may optionally include changes in all four areas, that is, the application API, region files, database formats, and log files may not be backward-compatible with previous releases.

**Comment by daira** [comment] 2016-08-16 10:58
Duplicate of #1255.

**Closed by daira** 2016-08-16 10:58 UTC
