### ISSUE TITLE
Zcashd errors because quotes autocorrected to smart quotes 

### ISSUE THREAD

**Issue by lindanlee** [zcash/zcash#2924] opened 2018-01-31 21:12 UTC
### Describe the issue
This isn't really a technical error, because zcashd is working as expected. It's just easy to make the mistake that I made, which was to copy and paste commands from an editor that automatically correct quotes into smart quotes. 

See the following picture, the first command throws an error, but the second command does not. It's because all the quotes were replaced with smart quotes. 
![image](https://user-images.githubusercontent.com/6580269/35647531-7a175892-0698-11e8-8aba-e54a293eddab.png)

It's somewhat hard to tell that it happened, and in the editor I was using, the difference between those two smart quotes weren't visible. In the terminal, the difference is visible now that I know what the problem was, but I wouldn't have noticed the difference. I thought I was formatting the command incorrectly some other way. 

### Can you reliably reproduce the issue?
Yes, try any command with smart quotes instead of regular quotes and it will break. There are editors that will automatically correct quotes to smart quotes. 

### Expected behaviour
An error telling me that the quotes were the problem would have been nice. Or maybe automatically correcting smart quotes into regular quotes and making the command work anyway? I don't know if that's actually a good idea though, or if it makes other things kind of weird. 

### The version of Zcash you were using:
Zcash Daemon version v1.0.14-1ddecf64-dirty

### Machine specs:
- OS name + version: MacOS High Sierra 10.13.2

**Comment by daira** [comment] 2018-02-01 12:04
I don't think we can reliably correct for smart quotes, because the *intended* quotes would have had a particular effect on parsing of the original shell command line that ``zcashd`` doesn't have enough information to reproduce. The intended effect would also be different between POSIX shells and Windows.

Detecting smart quotes and producing a more specific error seems quite feasible. In order to guarantee not to affect correct cases that happen to include smart quote characters (I don't know whether there are any actual uses of them, maybe memo fields but those are in hex at the moment?), we could look for them only on a JSON parser error.

Actually now that I think about it there are cases in which only *some* of the quotes have been replaced, in which the interpretation of the JSON could change even though it's still valid. Do we need to handle that?

Also, what if the smart quotes end up as [mojibake](http://text-mode.tumblr.com/post/31409503070/russian-postmen-fix-an-error-caused-by-an) when interpreted according to the locale's character encoding &mdash; do we try to detect that?

**Comment by LarryRuane** [comment] 2018-05-31 20:06
I hit this too, copy-and-pasting from http://zcash.readthedocs.io/en/latest/rtd_pages/rtd_docs/payment_api.html

**Comment by lindanlee** [comment] 2018-05-31 20:12
@mdr0id can we turn off smartquotes in readthedocs?

**Comment by mdr0id** [comment] 2018-07-17 05:04
@lindanlee Resolved. Closing for archive purposes

**Closed by mdr0id** 2018-07-17 05:04 UTC
Labels: RPC interface, error handling, usability, usi
