### ISSUE TITLE
On post-crash restart: Assertion `(nd->witnessHeight == -1) || (nd->witnessHeight == pindex->nHeight - 1)' failed.

### ISSUE THREAD

**Issue by artlav** [zcash/zcash#1715] opened 2016-10-29 12:00 UTC
At a random point, zcashd (1.0.0) crashed. It was executing several Z transactions one after another at the time. The machine have 6Gb of RAM. The actual crash message didn't get recorded, sadly.
There was nothing in the log file, it just cut itself off.

The real issue is what happens next.

On restart, zcashd crashes with this message after a short time:

zcashd: wallet/wallet.cpp:653: void CWallet::IncrementNoteWitnesses(const CBlockIndex_, const CBlock_, ZCIncrementalMerkleTree&): Assertion `(nd->witnessHeight == -1) || (nd->witnessHeight == pindex->nHeight - 1)' failed.

The log cuts off during rescan with no errors.
This is eerily familiar, i remember reporting similar issues before and them being fixed by RC2.

Eventually, nothing short of a complete restore from backup fixed the situation.
I consider this is a critical, money-can-easily-get-lost bug.

Log fragment attached, starting a little before the initial crash.

(Bonus issue: Uploading a .log file gives a "We don’t support that file type. try again with a PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, PDF, or ZIP. " error... Kinda broken, i think, considering the feature's main use).
[debug.txt](https://github.com/zcash/zcash/files/559907/debug.txt)

**Comment by str4d** [comment] 2016-10-31 00:09
This bug **will not** result in loss of funds. It *could* result in an inability to spend funds without repairing the wallet, but only if this assertion was not there. There is a simple fix: launch the node with `-reindex`.

Not knowing the cause of the initial crash makes this much more *fun* to debug :sweat_smile: Any crash output should be sent to stdout, but you wouldn't see that if you were running your node in `-daemon` mode.

> (Bonus issue: Uploading a .log file gives a "We don’t support that file type. try again with a PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, PDF, or ZIP. " error... Kinda broken, i think, considering the feature's main use).

This is a GitHub issue, nothing we can do about it AFAIK.

**Comment by ocminer** [comment] 2016-11-03 07:09
I can confirm this bug as well:

zcashd: wallet/wallet.cpp:653: void CWallet::IncrementNoteWitnesses(const CBlockIndex*, const CBlock*, ZCIncrementalMerkleTree&): Assertion `(nd->witnessHeight == -1) || (nd->witnessHeight == pindex->nHeight - 1)' failed.


Restart not working - rescanning now

**Comment by ocminer** [comment] 2016-11-03 20:44
Actually this issue lastly at last corrupted my "wallet.dat" completely and made me getting it restored from backup + resync

**Comment by str4d** [comment] 2016-11-03 20:47
There was a separate bug that prevented `-reindex` from working, that is being fixed in 1.0.1. However, I'm surprised that your wallet.dat became completely corrupted, as this should not affect keys in any way - it should only affect wallet transactions, if at all.

**Comment by ocminer** [comment] 2016-11-03 20:49
Ah, I just wanted to open a issue for -reindex as well, as it always fails with the wrong genesis block hash... 

No, wallet.dat was broken completely and I had to dump db, reload db, salvagewallet and then do a full rescan (12h time ...)

**Comment by str4d** [comment] 2016-11-03 20:54
The `-reindex` bug was fixed in #1754 :smiley:

Did your assertion occur while your node was running, or after you restarted after a crash? If the latter, do you have the original crash output?

**Comment by ocminer** [comment] 2016-11-03 21:22
While it was running.. It crashed silently, I tried to restart and got the above error again - no game with the wallet file like this anymore.

**Comment by str4d** [comment] 2016-11-03 21:37
`zcashd` should never crash silently. There should be a crash message printed on stdout - although maybe it isn't visible in `-daemon` mode.... How are you running `zcashd`?

**Comment by ocminer** [comment] 2016-11-03 21:39
In -daemon mode - the last message in the log was an AddToWallet - then this:

zcashd: wallet/wallet.cpp:653: void CWallet::IncrementNoteWitnesses(const CBlockIndex, const CBlock, ZCIncrementalMerkleTree&): Assertion `(nd->witnessHeight == -1) || (nd->witnessHeight == pindex->nHeight - 1)' failed.

then nothing

**Comment by str4d** [comment] 2016-11-03 21:43
That's the message I'd expect for the assertion crash after you restarted. Are you saying that's what was in your log during the initial silent crash?

**Comment by ocminer** [comment] 2016-11-03 21:44
Exactly, it crashed with that message and everytime after I try to restart it from then on unless you "repair" the wallet manually

**Comment by str4d** [comment] 2016-11-17 02:00
@bitcartel Have you satisfied yourself that this was resolved by #1858?

**Closed** 2016-11-17 16:48 UTC
Labels: bug, has PR, wallet
