### ISSUE TITLE
Investigate intermittent hangs downloading parameters with Rust 1.64 reported by ZF

### ISSUE THREAD

**Issue by daira** [zcash/zcash#6185] opened 2022-09-29 01:40 UTC
@teor2345 wrote:
> We're seeing intermittent hangs downloading Zcash parameters with Rust 1.64, but Rust 1.63 works fine:
https://github.com/ZcashFoundation/zebra/pull/5251
> We're still trying to work out *why*, but I wanted to let the `zcashd` team know now, since we use the same parameter download code.
>
> (If you're not seeing it yet, it might be a bug in my recent `zcash_proofs` changes, or in the way `zebrad` calls the download code.)

We updated master to pin Rust 1.64.0 in baf7d9e24ab24d620d96fb4ee1a9768a4f4dd581 (part of #6177).

**Comment by teor2345** [comment] 2022-10-03 22:21
It looks like this is a performance regression in Rust 1.64:
https://github.com/ZcashFoundation/zebra/issues/5091#issuecomment-1265771671

Using Rust 1.63, this code is still significantly slower than other download methods, so we might want to work on a fix.

**Comment by upbqdn** [comment] 2022-10-05 20:59
I opened https://github.com/zcash/librustzcash/pull/666.

**Comment by daira** [comment] 2022-10-08 23:38
This has probably been fixed by https://github.com/zcash/librustzcash/pull/666, but that should be verified.

**Comment by nuttycom** [comment] 2022-10-10 19:28
Closed in favor of zcash/librustzcash#666

**Closed by nuttycom** 2022-10-10 19:28 UTC
Labels: zkSNARK Parameter Deployment
