### ISSUE TITLE
Use default fee for sendmany & sendtoaddress

### ISSUE THREAD

**Issue by ioptio** [zcash/zcash#2551] opened 2017-07-24 20:53 UTC
### Describe the issue
In using `sendtoaddress`, I was expecting the default .0001 ZEC fee to be taken but this call instead seemed to use the upstream fee calculation

### Can you reliably reproduce the issue?
Yes

#### If so, please list the steps to reproduce below:
1. Use `sendtoaddress` to send t-addr wallet funds to another t-addr

### Expected behaviour
Default fee of .0001 ZEC used for the transaction

### Actual behaviour + errors
Instead a 0.00000374 ZEC fee was taken

### The version of Zcash you were using:
1.0.10-1

### Any extra information that might be useful in the debugging process.
I can share txn id privately. Let me know if that would be helpful.

**Comment by daira** [comment] 2018-10-30 13:36
Duplicate of #2942.

**Closed** 2018-12-10 19:05 UTC
Labels: Bitcoin design divergence, RPC interface, duplicate, special to Daira, special to Zooko, transaction fees, wallet
