### ISSUE TITLE
HTTPRPC.FailsOnGET gtest fails on Debian 9

### ISSUE THREAD

**Issue by benjesito** [zcash/zcash#2599] opened 2017-08-29 20:49 UTC
### Describe the issue
```
======================================
   Zcash 1.0.11: src/test-suite.log
======================================

# TOTAL: 2
# PASS:  1
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: zcash-gtest
=================

[==========] Running 132 tests from 26 test cases.
[----------] Global test environment set-up.
[----------] 24 tests from checktransaction_tests
[ RUN      ] checktransaction_tests.check_vpub_not_both_nonzero
[       OK ] checktransaction_tests.check_vpub_not_both_nonzero (0 ms)
[ RUN      ] checktransaction_tests.valid_transaction
[       OK ] checktransaction_tests.valid_transaction (0 ms)
[ RUN      ] checktransaction_tests.BadVersionTooLow
[       OK ] checktransaction_tests.BadVersionTooLow (0 ms)
[ RUN      ] checktransaction_tests.bad_txns_vin_empty
[       OK ] checktransaction_tests.bad_txns_vin_empty (0 ms)
[ RUN      ] checktransaction_tests.bad_txns_vout_empty
[       OK ] checktransaction_tests.bad_txns_vout_empty (1 ms)
[ RUN      ] checktransaction_tests.bad_txns_oversize
[       OK ] checktransaction_tests.bad_txns_oversize (1 ms)
[ RUN      ] checktransaction_tests.bad_txns_vout_negative
[       OK ] checktransaction_tests.bad_txns_vout_negative (0 ms)
[ RUN      ] checktransaction_tests.bad_txns_vout_toolarge
[       OK ] checktransaction_tests.bad_txns_vout_toolarge (0 ms)
[ RUN      ] checktransaction_tests.bad_txns_txouttotal_toolarge_outputs
[       OK ] checktransaction_tests.bad_txns_txouttotal_toolarge_outputs (0 ms)
[ RUN      ] checktransaction_tests.bad_txns_txouttotal_toolarge_joinsplit
[       OK ] checktransaction_tests.bad_txns_txouttotal_toolarge_joinsplit (0 ms)
[ RUN      ] checktransaction_tests.bad_txns_txintotal_toolarge_joinsplit
[       OK ] checktransaction_tests.bad_txns_txintotal_toolarge_joinsplit (0 ms)
[ RUN      ] checktransaction_tests.bad_txns_vpub_old_negative
[       OK ] checktransaction_tests.bad_txns_vpub_old_negative (0 ms)
[ RUN      ] checktransaction_tests.bad_txns_vpub_new_negative
[       OK ] checktransaction_tests.bad_txns_vpub_new_negative (1 ms)
[ RUN      ] checktransaction_tests.bad_txns_vpub_old_toolarge
[       OK ] checktransaction_tests.bad_txns_vpub_old_toolarge (0 ms)
[ RUN      ] checktransaction_tests.bad_txns_vpub_new_toolarge
[       OK ] checktransaction_tests.bad_txns_vpub_new_toolarge (0 ms)
[ RUN      ] checktransaction_tests.bad_txns_vpubs_both_nonzero
[       OK ] checktransaction_tests.bad_txns_vpubs_both_nonzero (0 ms)
[ RUN      ] checktransaction_tests.bad_txns_inputs_duplicate
[       OK ] checktransaction_tests.bad_txns_inputs_duplicate (0 ms)
[ RUN      ] checktransaction_tests.bad_joinsplits_nullifiers_duplicate_same_joinsplit
[       OK ] checktransaction_tests.bad_joinsplits_nullifiers_duplicate_same_joinsplit (0 ms)
[ RUN      ] checktransaction_tests.bad_joinsplits_nullifiers_duplicate_different_joinsplit
[       OK ] checktransaction_tests.bad_joinsplits_nullifiers_duplicate_different_joinsplit (0 ms)
[ RUN      ] checktransaction_tests.bad_cb_has_joinsplits
[       OK ] checktransaction_tests.bad_cb_has_joinsplits (0 ms)
[ RUN      ] checktransaction_tests.bad_cb_empty_scriptsig
[       OK ] checktransaction_tests.bad_cb_empty_scriptsig (0 ms)
[ RUN      ] checktransaction_tests.bad_txns_prevout_null
[       OK ] checktransaction_tests.bad_txns_prevout_null (1 ms)
[ RUN      ] checktransaction_tests.bad_txns_invalid_joinsplit_signature
[       OK ] checktransaction_tests.bad_txns_invalid_joinsplit_signature (0 ms)
[ RUN      ] checktransaction_tests.non_canonical_ed25519_signature
[       OK ] checktransaction_tests.non_canonical_ed25519_signature (0 ms)
[----------] 24 tests from checktransaction_tests (4 ms total)

[----------] 7 tests from founders_reward_test
[ RUN      ] founders_reward_test.general

[WARNING] ../src/gtest-death-test.cc:825:: Death tests use fork(), which is unsafe particularly in a threaded context. For this test, Google Test couldn't detect the number of threads.

[WARNING] ../src/gtest-death-test.cc:825:: Death tests use fork(), which is unsafe particularly in a threaded context. For this test, Google Test couldn't detect the number of threads.

[WARNING] ../src/gtest-death-test.cc:825:: Death tests use fork(), which is unsafe particularly in a threaded context. For this test, Google Test couldn't detect the number of threads.

[WARNING] ../src/gtest-death-test.cc:825:: Death tests use fork(), which is unsafe particularly in a threaded context. For this test, Google Test couldn't detect the number of threads.
[       OK ] founders_reward_test.general (2 ms)
[ RUN      ] founders_reward_test.mainnet
[       OK ] founders_reward_test.mainnet (61 ms)
[ RUN      ] founders_reward_test.testnet
[       OK ] founders_reward_test.testnet (61 ms)
[ RUN      ] founders_reward_test.regtest
[       OK ] founders_reward_test.regtest (0 ms)
[ RUN      ] founders_reward_test.slow_start_subsidy
[       OK ] founders_reward_test.slow_start_subsidy (4 ms)
[ RUN      ] founders_reward_test.per_address_reward_mainnet
[       OK ] founders_reward_test.per_address_reward_mainnet (305 ms)
[ RUN      ] founders_reward_test.per_address_reward_testnet
[       OK ] founders_reward_test.per_address_reward_testnet (315 ms)
[----------] 7 tests from founders_reward_test (748 ms total)

[----------] 3 tests from wallet_zkeys_tests
[ RUN      ] wallet_zkeys_tests.store_and_load_zkeys
[       OK ] wallet_zkeys_tests.store_and_load_zkeys (1 ms)
[ RUN      ] wallet_zkeys_tests.write_zkey_direct_to_db
[       OK ] wallet_zkeys_tests.write_zkey_direct_to_db (98 ms)
[ RUN      ] wallet_zkeys_tests.write_cryptedzkey_direct_to_db
[       OK ] wallet_zkeys_tests.write_cryptedzkey_direct_to_db (2134 ms)
[----------] 3 tests from wallet_zkeys_tests (2233 ms total)

[----------] 1 test from tautologies
[ RUN      ] tautologies.seven_eq_seven
[       OK ] tautologies.seven_eq_seven (0 ms)
[----------] 1 test from tautologies (0 ms total)

[----------] 9 tests from DeprecationTest
[ RUN      ] DeprecationTest.NonDeprecatedNodeKeepsRunning
[       OK ] DeprecationTest.NonDeprecatedNodeKeepsRunning (0 ms)
[ RUN      ] DeprecationTest.NodeNearDeprecationIsWarned
[       OK ] DeprecationTest.NodeNearDeprecationIsWarned (0 ms)
[ RUN      ] DeprecationTest.NodeNearDeprecationWarningIsNotDuplicated
[       OK ] DeprecationTest.NodeNearDeprecationWarningIsNotDuplicated (0 ms)
[ RUN      ] DeprecationTest.NodeNearDeprecationWarningIsRepeatedOnStartup
[       OK ] DeprecationTest.NodeNearDeprecationWarningIsRepeatedOnStartup (0 ms)
[ RUN      ] DeprecationTest.DeprecatedNodeShutsDown
[       OK ] DeprecationTest.DeprecatedNodeShutsDown (0 ms)
[ RUN      ] DeprecationTest.DeprecatedNodeErrorIsNotDuplicated
[       OK ] DeprecationTest.DeprecatedNodeErrorIsNotDuplicated (0 ms)
[ RUN      ] DeprecationTest.DeprecatedNodeErrorIsRepeatedOnStartup
[       OK ] DeprecationTest.DeprecatedNodeErrorIsRepeatedOnStartup (0 ms)
[ RUN      ] DeprecationTest.DeprecatedNodeShutsDownIfOldVersionDisabled
[       OK ] DeprecationTest.DeprecatedNodeShutsDownIfOldVersionDisabled (0 ms)
[ RUN      ] DeprecationTest.DeprecatedNodeKeepsRunningIfCurrentVersionDisabled
[       OK ] DeprecationTest.DeprecatedNodeKeepsRunningIfCurrentVersionDisabled (0 ms)
[----------] 9 tests from DeprecationTest (0 ms total)

[----------] 5 tests from equihash_tests
[ RUN      ] equihash_tests.expand_and_contract_arrays
[       OK ] equihash_tests.expand_and_contract_arrays (0 ms)
[ RUN      ] equihash_tests.minimal_solution_representation
[       OK ] equihash_tests.minimal_solution_representation (0 ms)
[ RUN      ] equihash_tests.is_probably_duplicate
[       OK ] equihash_tests.is_probably_duplicate (0 ms)
[ RUN      ] equihash_tests.check_basic_solver_cancelled
[       OK ] equihash_tests.check_basic_solver_cancelled (5 ms)
[ RUN      ] equihash_tests.check_optimised_solver_cancelled
[       OK ] equihash_tests.check_optimised_solver_cancelled (3 ms)
[----------] 5 tests from equihash_tests (8 ms total)

[----------] 3 tests from HTTPRPC
[ RUN      ] HTTPRPC.FailsOnGET
FAIL zcash-gtest (exit status: 139)
```

### Can you reliably reproduce the issue?
./qa/zcash/full-test-suit.sh

### Machine specs:
- OS Debian unstable
- CPU: Intel® Core™ i7-6700K CPU @ 4.00GHz × 8 
- RAM: 32G
- Disk size: 250G
- Disk Type (HD/SDD): SSD
- Linux kernel version (uname -a): Linux debian-axon 4.3.0-1-amd64 #1 SMP Debian 4.3.5-1 (2016-02-06) x86_64 GNU/Linux

- Compiler version (gcc -7): 7

**Comment by str4d** [comment] 2017-09-11 20:43
This looks like the same issue we see in our CI on Debian 9 (which is currently unsupported): https://ci.z.cash/#/builders/12/builds/9

**Comment by nathan-at-least** [comment] 2017-09-11 22:59
Also #2545 may be relevant. I recommend we try to repro this failure on our master, and if that does reproduce and fail, then see if #2545 fixes the issue directly.

**Comment by arcalinea** [comment] 2017-09-14 21:07
Trying to reproduce this error on Debian sid, gcc version 7.2.0, RAM 32G, I'm running into errors building...

**Comment by arcalinea** [comment] 2017-09-14 22:00
Ok, on Debian sid, gcc version 7.2.0, RAM 32G, zcash wouldn't build without #2545, but once it built was able to run full-test-suite.sh successfully. Can't replicate this issue

**Comment by str4d** [comment] 2017-09-20 13:07
This reliably occurs on Debian 9.1 (at least the version used by the CI worker), so if this now works on Sid, that suggests it is something introduced in Debian 9 that has now been fixed.

@benjesito could you re-test and confirm your OS version (or equivalent)?

**Comment by str4d** [comment] 2017-11-15 09:26
Duplicate of #2690, which contains a diagnosis.

**Closed by str4d** 2017-11-15 09:26 UTC
Labels: portability, testing
