### ISSUE TITLE
Ubuntu 22.04 secp256k1 fail

### ISSUE THREAD

**Issue by mdr0id** [zcash/zcash#6115] opened 2022-08-16 21:34 UTC
During testing of the newer Ubuntu 22.04 platform, it was noticed that the full-test-suite does not gracefully complete as expected like all other supported production platforms:

```
Running stage secp256k1
=======================

make: Entering directory '/home/zcash/src/secp256k1'
make  check-TESTS
make[1]: Entering directory '/home/zcash/src/secp256k1'
make[2]: Entering directory '/home/zcash/src/secp256k1'
./build-aux/test-driver: line 112: 137048 Aborted                 (core dumped) "$@" >> "$log_file" 2>&1
FAIL: tests
PASS: exhaustive_tests
============================================================================
Testsuite summary for libsecp256k1 0.1
============================================================================
# TOTAL: 2
# PASS:  1
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See ./test-suite.log
============================================================================
make[2]: *** [Makefile:1286: test-suite.log] Error 1
make[2]: Leaving directory '/home/zcash/src/secp256k1'
make[1]: *** [Makefile:1394: check-TESTS] Error 2
make[1]: Leaving directory '/home/zcash/src/secp256k1'
make: *** [Makefile:1612: check-am] Error 2
make: Leaving directory '/home/zcash/src/secp256k1'

------------------------
Finished stage secp256k1

!!! Stage secp256k1 failed !!!
!!! One or more test stages failed !!!
```
test-suite.log:
```
========================================
   libsecp256k1 0.1: ./test-suite.log
========================================

# TOTAL: 2
# PASS:  1
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: tests
===========

test count = 64
random seed = 5b65aae462bb1ebd60d2a243f2e194de
Failure 10 on 30 34 02 1a ff 3e ff ff ff ff ff ff ff ff 7f 00 00 00 00 13 ff ff ff ff e3 ff 0b 00 00 00 02 16 00 a0 00 00 00 00 00 00 20 fc ff ff ff ff ff 1f 00 00 ff ff e2 ff 
src/tests.c:4947: test condition failed: ret == 0
FAIL tests (exit status: 134)
```

**Comment by daira** [comment] 2022-09-27 22:37
Closing as duplicate of #6180, since that issue has more information and this is not actually dependent on Ubuntu 22.04. (It happens on any machine with OpenSSL 3.x as its installed libssl, AFAIK.)

**Closed by daira** 2022-09-27 22:37 UTC
