### ISSUE TITLE
RPC z_listtransactions

### ISSUE THREAD

**Issue by Crypto2** [zcash/zcash#1639] opened 2016-10-25 15:58 UTC
Will there be a z_listtransactions implemented? I was reading the integration guide but I only see a way to list Z transactions by address; for exchange and wallet providers this is a big issue since we'd have to poll every address individually versus being able to make one call and see all incoming transactions.

I also saw in z_sendmany that change would be sent back to the originating address, is there a field in the output of z_listreceivedbyaddress/z_listtransactions showing it is change so our systems won't see it as a incoming payment?

**Comment by daira** [comment] 2016-10-25 16:38
Duplicate of #1333. Related ticket: #1438 

Note that it's potentially inefficient to list all incoming transactions because the node needs to trial-decrypt separately for each key. We will probably add a call to do it though (that is #1333).

For the question about detecting change, you can potentially use memo fields for this: instead of allowing the wallet code to calculate change, calculate it yourself and use an explicit output with a memo field you can recognize. (Use a reserved first byte for this that is not valid in UTF-8, as specified in the "Note Plaintexts and Memo Fields" section of the protocol spec.)

**Closed by daira** 2016-10-25 16:38 UTC
