### ISSUE TITLE
Repository for zcash 1.0.1 is missing changelog 

### ISSUE THREAD

**Issue by tombelpasso** [zcash/zcash#1791] opened 2016-11-05 08:25 UTC
Followed the Debian installation instructions from the user-guide to update my 1.0.0 package.

I used the following command to upgrade to 1.0.1:

sudo apt-get update && sudo apt-get install zcash

The help messages from 1.0.1 seem to reference 1.0.0 instead of 1.0.1 so I wanted to make sure I was getting the correct version.  Ran:

 apt-get changelog zcash

Message:
E: Failed to fetch changelog:/zcash.changelog  Changelog unavailable for zcash=1.0.1

Since it include 1.0.1 at the end I assume I am running the updated version.

Please add the change log to the Debian package.

Thanks,

- Tom

**Comment by str4d** [comment] 2016-11-08 02:32
@ageis any ideas as to what might cause this?

**Comment by ageis** [comment] 2016-11-08 04:10
@str4d That command works on my system (Debian stretch). @tombelpasso, what distro and distro version are you running?

**Comment by ageis** [comment] 2017-01-09 22:07
Closing as original poster has not responded and I'm unable to reproduce and we're now at 1.0.4. We fixed up some of the packaging in version 1.0.1 or 1.0.2 and this may have been related to that.

**Closed by ageis** 2017-01-09 22:07 UTC
Labels: packaging

**Comment by sk-jame** [comment] 2017-03-22 10:06
ageis, could you say what did you fix. I has the same error with my own package, and can't find reason.
lintian has no warning about changelog
