### ISSUE TITLE
Unknown config / commandline options should exit with error.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#4649] opened 2020-08-05 16:42 UTC
### Describe the issue

Unrecognized config options are silently ignored, which can be confusing.

In my latest case I started a node with `index=1` when I meant `txindex=1`. Because it could not retrieve tx info, I assumed there was an indexing bug and guessed incorrectly it might be because I used `wallet=0` (just based on a hunch).

### Can you reliably reproduce the issue?

Yes. Create any unrecognized option in the config file or commandline, then start `zcashd`.

#### If so, please list the steps to reproduce below:
1. Add a made up option to `zcash.conf` and add an unrecognized option, for example `pangalacticgargleblaster=1`
2. Start `zcashd`.
3. Observe that there's no indication that there's an unrecognized option.
4. Repeat as above except instead of adding an option to `zcash.conf`, add an unrecognized commandline argument like `-fluxcapacitor=42`.

### Expected behaviour

On startup, before initializing network or database access, exit with an error message listing unrecognized options and their source (ie: config file path + line or commandline arg).

### Actual behaviour + errors

Currently `zcashd` silently ignores the unrecognized option and continues operation normally.

### The version of Zcash you were using:

```Zcash Daemon version v3.1.0```

### Do you have a backup of `~/.zcash` directory and/or take a VM snapshot?

Yes.

**Comment by daira** [comment] 2020-08-05 17:36
Duplicate of #2284. Another duplicate was #3609.

**Closed by daira** 2020-08-05 17:36 UTC
Labels: bug, duplicate
