### ISSUE TITLE
Tor-apt onion service not working

### ISSUE THREAD

**Issue by ioptio** [zcash/zcash#3867] opened 2019-03-11 18:14 UTC
https://forum.zcashcommunity.com/t/tor-apt-onion-service-doesnt-seem-to-work/32832

**Comment by ioptio** [comment] 2019-03-11 18:14
@mdr0id anyone in dev-infra that can look at this?

**Comment by garethtdavies** [comment] 2019-08-19 14:42
This was working until last week. I actually initially installed it this way to confirm it was working but I can't find that post I made. However, now I am seeing:

```
Err:15 tor+http://zcaptnv5ljsxpnjt.onion stretch InRelease                       
  Timed out while waiting to read 'first part of response' from proxy socks5h://127.0.0.1:9050 [IP: 127.0.0.1 9050]
```

Note that I had updated the repo to Stretch as opposed to Jessie listed in the docs https://zcash.readthedocs.io/en/latest/rtd_pages/install_debian_bin_packages.html?highlight=tor#tor and had installed v2.0.6 this way.

**Comment by garethtdavies** [comment] 2019-08-19 16:26
This was fixed via @zebambam so this issue can be closed.

**Comment by garethtdavies** [comment] 2019-08-30 01:48
Looks like this got rebroken:

```
Ign:15 tor+http://zcaptnv5ljsxpnjt.onion stretch InRelease                       
Err:16 tor+http://zcaptnv5ljsxpnjt.onion stretch Release
  404  Not Found [IP: 127.0.0.1 9050]
Reading package lists... Done
E: The repository 'tor+http://zcaptnv5ljsxpnjt.onion stretch Release' no longer has a Release file.```
```

**Comment by mdr0id** [comment] 2019-08-30 02:35
@garethtdavies Will add it to the fix list. Many thanks for the find! Always appreciated!

**Comment by garethtdavies** [comment] 2019-09-16 19:56
Any update on this as still broken for me? Can anyone else reproduce this? cc @zebambam

**Comment by the-metalworker** [comment] 2019-10-15 01:05
@garethtdavies I came here to report that I am also receiving this error when trying to update zcashd on my Debian machine:

> Ign:21 tor+http://zcaptnv5ljsxpnjt.onion jessie InRelease
> Err:22 tor+http://zcaptnv5ljsxpnjt.onion jessie Release
> 404  Not Found [IP: 127.0.0.1 9050]
> Reading package lists... Done
> E: The repository 'tor+http://zcaptnv5ljsxpnjt.onion jessie Release' no longer has a Release file.
> N: Updating from such a repository can't be done securely, and is therefore disabled by default.
> N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by the-metalworker** [comment] 2019-11-20 04:30
Hi @mdr0id I am checking in to report that I am still receiving this error when trying to update zcashd on my Debian machine using the Tor hidden service documented [here](https://zcash.readthedocs.io/en/latest/rtd_pages/install_debian_bin_packages.html#tor).

```
E: The repository 'tor+http://zcaptnv5ljsxpnjt.onion jessie Release' no longer has a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

Do you have a timeline as to when the issue causing this error message will be fixed? My node is currently stuck at block 617512 because of this problem.

```
Error: This version has been deprecated as of block height 617512. You should upgrade to the latest version of Zcash.
```

**Comment by benzcash** [comment] 2019-11-25 17:24
The tor link for `tor+http://zcaptnv5ljsxpnjt.onion` should be working again, and the fix commited :pray: 

Please let me know if you're still having an issue.

**Comment by mdr0id** [comment] 2019-11-25 19:29
@the-metalworker @garethtdavies Above should be fix, per mentioned patch, can one of you verify on your end. Thank you for your feedback on this, it is greatly appreciated.

**Comment by garethtdavies** [comment] 2019-11-28 04:10
I can confirm this is working again, thanks

**Comment by the-metalworker** [comment] 2019-12-03 21:11
@mdr0id I can also confirm this is working again. Thank you!

**Comment by benzcash** [comment] 2020-01-13 16:44
Fixed with https://github.com/Electric-Coin-Company/infrastructure/pull/441

**Closed by benzcash** 2020-01-13 16:44 UTC
Labels: Tor, usi
