### ISSUE TITLE
High transaction volumes causing problems for miners

### ISSUE THREAD

**Issue by sammy007** [zcash/zcash#2333] opened 2017-05-01 11:12 UTC
There is tx spam ongoing, I see many blocks with up to 2 MB size with just ~50 tx. RPC `getblocktemplate` poll leads to timeouts (I have 5s timeout). This is not ok and I believe `getblocktemplate` must take less than 5s on decent hardware `Intel(R) Xeon(R) CPU E3-1245 v5 @ 3.50GHz`. Load average is 1.5.

You seems don't care about it, dev channel is silent and only cosmetic changes discussed there so far. It seems I must create a patch to ignore transactions at all and mine empty blocks if you are going to pretend that it's fine.

Consequences:

* Mining centralisation
* Empty block mining
* Tons of orphans (uncle bs proposal can't help)
* Tons of rejects
* Fee market
* Thousands of transactions hanging out in mempool
* Full nodes shortage
* Lazy mining leads to forks

**Comment by sammy007** [comment] 2017-05-01 12:44
Mining 1-2 MB blocks in ZCash makes no economic sense at all, bitcoin network pays several thousands dollars in fees for 1 MB blocks.

If it takes more than 5 seconds to build new block template I encourage miners to mine empty blocks instead. So please either optimise it or remove 20% tax if you are not capable to deploy fix or raise fees to some decent level like 1000x from current price via hard fork.

**Comment by sammy007** [comment] 2017-05-01 12:48
```
New block to mine on <skipped> at height 106477 with 57 tx, 10.00000000 reward, 0.01994709 fees (25.5959ms, 3.260499057s)
```

The former is a time spent on building merkle tree on a pool side, the latter is how much time spent to call `getblocktemplate` via loopback interface: **3.26 seconds**. It takes 3.26 seconds to produce block template with just 57 transactions in zcashd.

**Comment by a1binos** [comment] 2017-05-01 13:55
+1 . I notice pool freezing, because of transaction spam.

**Comment by sammy007** [comment] 2017-05-01 13:59
`getmempoolinfo`

{
  "size": 173,
  "bytes": 6261224,
  "usage": 13303840
}

I am working on a patch to completely ignore mempool for now, will mine empty blocks.

**Comment by zapv0lt** [comment] 2017-05-01 14:25
I'm seeing similar issues with slow getblocktemplate today.  It hasn't been reported above, but I'm also seeing extremely large RSS after running a node for several weeks.  After some digging, I think this could be related: bitcoin/bitcoin#6876.

Leaving aside the issue of whether or not this is actually intentional transaction spam, I think it's fair to expect getblocktemplate to handle these worst-case situations without become extremely slow.

**Comment by gobitfly** [comment] 2017-05-01 14:34
I can confirm the issue as well. Those large spam blocks cause huge CPU usage and even crashed some of my nodes on lower-spec machines.

**Comment by jackgavigan** [comment] 2017-05-01 14:44
Looks like it started around block #106404 (00000000200321ae35759cca1c57a1600451532817e3483fad732edd4e775e6d at 10:08:12 BST)

Looking at a single sample, an amount of ZEC is unshielded (e.g. txn c18cd332d4e09b9e53a4a9e23d32206d997aa7ece9d7bd41872d1b6fd2bbca79 unshielded 82.74963511 ZEC into t1QMCGKi92v85Jmar2PD3SjQF8Eadbd2y4q), then sent in a single transaction with 100s of small outputs (e.g. t1QMCGKi92v85Jmar2PD3SjQF8Eadbd2y4q sent 82.74963511 ZEC to 1869 outputs - tx c00782ba18f2ae70b60b983fb273c2160020a10e4cab27db39e8a5c59320071c), which then seem to get (partially?) re-aggregated into other addresses. 

Some of the addresses involved t1VoqSxHh1ZnWBRFyHh6diWM4whimFzhjcJ have been around for a while (and have been part of similar patterns of transactions in the past).

**Comment by daira** [comment] 2017-05-01 14:58
@sammy007 wore:
> [...] if you are going to pretend that it's fine.
> [...] or raise fees to some decent level like 1000x from current price via hard fork.

We are not "pretending that it's fine". This started at 9:08 UTC which was only 2 hours before you filed the ticket; please give us time to analyse the issue thoroughly. There's not going to be any knee-jerk reaction where we raise fees (at all, let alone by 1000-fold) unless we have strong evidence that it is required. Nor would raising fees require a hard fork, if it were required.

**Comment by sammy007** [comment] 2017-05-01 15:02
Spam started more than 16 hours ago. And this is not my duty to watch network state.

**Comment by daira** [comment] 2017-05-01 15:15
Indeed it does seem to have started around block 106077, which was at 2017-04-30 19:35:35 UTC, which is just under 20 hours ago. I stand corrected.

**Comment by jackgavigan** [comment] 2017-05-01 15:28
@daira: My bad. It looks like the activity comes in waves.

**Comment by miningpoolhub** [comment] 2017-05-02 00:24
This is quite critical problem. Pool is suffering.

**Comment by str4d** [comment] 2017-05-02 01:48
We've been looking into this for the last ten hours or so. Here's what we've established:

- The transactions appear to be the result of a miner collecting six month's worth of mining rewards into a single address, most likely via a script started over the weekend.
- The script appears to use batching: around 300 transactions are created at a time containing ~250 inputs each (for a size of around 37070 bytes each), and the next batch is not created until the previous batch has been completely removed from the mempool.
- The mining network is clearing these batches from the mempool in about six blocks (as expected given the transaction sizes and block size limit).
- Per-transaction-input validation time is around 0.2-0.4ms for an up-to-date node, or 0.6-0.9ms for a node syncing the block chain at the same time (both measured on my Core i7-6600U laptop).
  - This is the quadratic hashing issue inherited from Bitcoin, and is in line with our [existing benchmark on a Xeon E3-1225 V2 for validating a transaction with many inputs](https://speed.z.cash/timeline/?exe=1&base=1%2B178&ben=time+validatelargetx&env=1&revs=50&equid=off&quarts=on&extr=on) (specifically [555 inputs](https://github.com/zcash/zcash/blob/master/src/zcbenchmarks.cpp#L193), targeting the [consensus maximum transaction size of 100,000 bytes](https://github.com/zcash/zcash/blob/master/src/consensus/consensus.h#L18)).
  - This puts the time to validate the full blocks (containing around 60 of these transactions) at around 6 seconds (`60 tx/block * 250 txin/tx * 0.4 ms/txin`), with a maximum of 10 seconds for an up-to-date node (again, as seen on my Core i7-6600U laptop).
- `getblocktemplate` latency appears to be affected by the mempool load, but we are still investigating exactly how.

We are still in the middle of investigating several parts of the code, and will post another update later on.

**Comment by str4d** [comment] 2017-05-02 04:01
Here is the log output for `getblocktemplate` with `-debug=bench` after applying [this patch](https://github.com/zcash/zcash/files/969356/getblocktemplate-bench.txt) to master, while there were 255 of these transactions in my local mempool:

```
 - getblocktemplate called
   - Preamble: 0.01ms
   - Longpoll: 0.14ms
 keypool reserve 2
   - CreateNewBlock called
     - Preamble: 0.02ms
     - Locked preamble: 0.23ms
     - Mempool access: 3310.92ms
       - Prev tx access: 3291.40ms (0.05ms x 61769)
       - Coins access: 6.29ms (0.00ms x 61769)
     - Block filling: 6536.69ms
       - Check inputs: 6480.59ms (104.53ms x 62)
       - Update coins: 38.83ms (0.63ms x 62)
 CreateNewBlock(): total size 1985159
     - Block creation: 0.27ms
       - Connect 63 transactions: 445.62ms (7.073ms/tx, 0.033ms/txin) [1.26s]
     - Verify 13326 txins: 1067.32ms (0.080ms/txin) [5.09s]
     - Block validation: 1385.73ms
     - Total time: 11548.25ms
 keypool return 2
   - Block update: 11601.63ms
   - Ret prep txs: 21.15ms
   - Ret prep aux: 3.60ms
   - Total time: 11626.59ms
```

The bottlenecks are:
- Prev tx access: `CCoinsViewCache::HaveCoins(txin.prevout.hash)`
- Check inputs: `ContextualCheckInputs(tx)`
- Block validation: `TestBlockValidity(block)`

**Comment by str4d** [comment] 2017-05-02 06:03
As the primary bottleneck is transparent signature validation, I've opened #2335 to switch to libsecp256k1 for validation, which should be "anywhere between 2.5 and 5.5 times faster" per https://github.com/bitcoin/bitcoin/pull/6954.

@sammy007 @a1binos @zapv0lt @gobitfly @miningpoolhub please test this PR in your infrastructure and let me know how much latency this removes compared to the current release (either overall, or using the benchmark patch I linked in my last comment).

**Comment by sammy007** [comment] 2017-05-02 13:30
Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz `str4d:2333-validation-speed`

```
1.60983597s
419.145133ms
847.123985ms
22.432544ms
1.482908816s
```

Intel(R)  Xeon(R) CPU E3-1245 v5 @ 3.50GHz `-TestBlockValidity`
```
3.808361534s
2.762839296s
4.369284388s
3.075969ms
4.253306917s
```

**Comment by Xandrah** [comment] 2017-05-02 16:35
This is getting pretty severe now, zcashd becomes unresponsive and takes 100% CPU on 4 cores. My pool is not functioning correctly because zcashd is freezing, you cannot even do zcash-cli getinfo without it hanging for 10 seconds.

**Comment by str4d** [comment] 2017-05-03 00:06
@Xandrah per our chat in #zcash on Rocket.Chat, the reason for the lock-up (and likely for the ballooning memory usage) is because `getblocktemplate` is being called every few seconds, but each call is taking a few seconds to return. `getblocktemplate` holds the global lock `cs_main`, so while it is running, other calls (including subsequent `getblocktemplate` calls) will back up, eventually exceeding the work queue depth and causing the error you saw. You can increase the work queue depth from its default of 16 with `-rpcworkqueue=##`, but `getblocktemplate` needs to be called less frequently if it is taking longer to respond.

**Comment by aayanl** [comment] 2017-05-03 01:06
Got about the same results as Sammy with the pr.

**Comment by Kukarism** [comment] 2017-05-03 04:27
If the "activity" seems to be "in waves", i'd suggest that this is f2pool processing dayly payments. Its hashrate grew up noticebly the last few days. Unlike flypool - its the only matching in hash power opponent, which processes just-in-time on-the-fly micropayments when miners reach their "threshold" - f2pool makes all the payments (hundreds of tons of them, eventually) just 1 time per day, nearly the morning of China time.
Suggestion: let f2pool implement "threshold" payments distributed equally (in common) during all the day (like Flypool), or somehow let it rearrange miners on several groups which get their coins on some different predefined time patterns.

**Comment by sammy007** [comment] 2017-05-03 04:45
The correct way is to enforce economic, but since this pool has major hashrate it will not work. And if further significant optimisation is impossible, this is doom, because smaller players will never have benefits over big ones.

You shouldn't ask anyone to be nice in this space, it does not work. Either make it strong with zero trust or die.

**Comment by str4d** [comment] 2017-05-03 04:53
@Kukarism that's not the cause:
- The waves occur anywhere at intervals anywhere between twenty minutes and an hour.
- The transactions are all "collecting" (combining many small UTXOs into a single UTXO) - the opposite of mining pool payouts.

**Comment by wangchun** [comment] 2017-05-03 08:47
@Kukarism we cannot process payment because we suffer very high orphan rate. We lost 100 ZEC on day one and 300 more on day two. If the situation persists, we have to increase the fee to 20% or simply close the zcash pool.

**Comment by shooterman** [comment] 2017-05-03 17:36
I can't confirm my timeout problems,  focus on the issue.

**Comment by ocminer** [comment] 2017-05-03 19:14
I don't see any issues at all on my side, hardware Dual Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz with 256GB RAM.

**Comment by sammy007** [comment] 2017-05-03 19:22
> I don't see any issues at all on my side

Then you should measure properly.

**Comment by ocminer** [comment] 2017-05-03 19:35
No need for attacks :) I'm measuring properly and the longest call over the last 24 was about 2 secs, currently it's 179 ms

**Comment by sammy007** [comment] 2017-05-03 19:41
We are talking about longest calls, yes, `2s` is not normal. This is what this issue is about.

**Comment by zookozcash** [comment] 2017-05-03 21:03
We posted a note about this issue on the forum:

**Comment by zookozcash** [comment] 2017-05-03 21:03
https://forum.z.cash/t/performance-issues-on-the-network/15664/3

**Comment by zookozcash** [comment] 2017-05-03 21:04
Let's leave this ticket open to track the performance of our software in handling this kind of load. The next step is to get a benchmark into our CI system that exercises this case and shows the same results as people are experiencing in practice.

**Comment by sammy007** [comment] 2017-05-03 21:06
Thanks for not closing it.

**Comment by zookozcash** [comment] 2017-05-04 14:51
Update: this issue increased orphan rates for miners, and some miners started throttling blocksizes or excluding transactions from blocks approximately 2017-05-04_08:00Z, and this caused a backlog of transactions not getting mined.

We've written a simple patch (attached) against 1.0.8-1 which miners could use if they want. It excludes transactions with > 100 inputs from being mined.

[2017-05-04-CreateNewBlock-ignore-many-input-txs.diff.txt](https://github.com/zcash/zcash/files/976533/2017-05-04-CreateNewBlock-ignore-many-input-txs.diff.txt)

**Comment by zookozcash** [comment] 2017-05-04 16:59
To close this ticket, make it so that all txns that do get mined into blocks are so efficient to verify that the resulting block can propagate quickly enough to avoid excessive orphaning. We can accomplish this by some combination of increasing efficiency of verification of txns and by excluding txns from blocks if they can't be verified efficiently enough.

Note: it is a separate issue to limit mempool RAM usage. This ticket is _only_ about preventing verification-expensive txns _in blocks_ from causing too much propagation delay for those blocks. The other issue of mempools using excess RAM is a separate issue and should probably be solved with a separate mechanism.

**Comment by bitcartel** [comment] 2017-05-04 17:12
A patch to allow a local node (let's say a miner) to reject tx with > n transparent inputs from entering their mempool will prevent txs which are expensive to verify from getting mined.  It will also help reduce the size of the mempool.

**Comment by zookozcash** [comment] 2017-05-04 17:13
> A patch to allow a local node (let's say a miner) to reject tx with > n transparent inputs from entering their mempool will prevent txs which are expensive to verify from getting mined. It will also help reduce the size of the mempool.

Yes, but that's the approach that I'm saying I don't want. ;-) Let's not kill two birds with one stone here.

**Comment by daira** [comment] 2017-05-04 17:24
@zookozcash: Why not? I don't understand why we would want to only solve half the problem (or less; more precisely half of the problem we could solve right now).

**Comment by daira** [comment] 2017-05-04 17:29
Note that if you accept a tx into your mempool, you have to verify it. Verification cost is the main problem here. So if we still verify the problematic many-input txns then it's not just that we have failed to solve a different problem than the one that caused the performance issue. It's that we will fail to solve the primary problem.

**Comment by ocminer** [comment] 2017-05-04 17:37
I guess changing the verification process to be multi-threaded would/should help as well as currently I only see one core used (100%) when verifying those large txes

**Comment by zookozcash** [comment] 2017-05-04 18:00
Daira: I think "how large should my mempool be" is a separate policy issue from "how fast do I want my blocks to propagate", which is separate yet again from "what kinds of txns do I want to favor or disfavor".

As for "how large should me mempool be" we need a separate method of controlling that (which you are going to open an issue ticket for — please link to it here when you do). IMO the configuration should be a simple hard upper bound of how much memory the mempool can use, and the implementation should be _random_ drop — if adding a txn would exceed the upper bound, then randomly select from all txns (including the new one) to drop, and repeat that until the upper bound would not be exceeded.

**Comment by daira** [comment] 2017-05-04 19:58
@zookozcash wrote:
> I think "how large should my mempool be" is a separate policy issue from "how fast do I want my blocks to propagate", which is separate yet again from "what kinds of txns do I want to favor or disfavor".

I disagree:
* The purpose of the mempool is to store transactions that a node should either relay or mine.
* Therefore, a mempool only contains the transactions that node policy specifies someone should potentially be able to mine. (If you don't want anyone to be able to mine a tx, why relay it, and therefore why store it?)
* By definition, a full node validates all of the transactions that it relays or mines, i.e. all of the transactions in its mempool.
* So, to address any performance problem with validation, mempool acceptance is the correct place to enforce restrictions. Any other place is too late; the transaction has already been validated, incurring the undesired cost.
* It's not possible to have a policy that mines something that isn't in the mempool (well, it is, but that would be a significant change to the Bitcoin/Zcash design). Therefore, mining policy and mempool acceptance policy are not independent; transactions included by the former must be a subset of the latter.
* There is no way to separate "what kinds of txns do I want to favour or disfavour" from "what transactions do I want to relay" and "what transactions do I want to mine". The latter two questions are the *only* policy levers available to implement the former.
* Technically, you could have two thresholds: the maximum number of transparent inputs in txns you will relay, and the maximum number of transparent inputs in txns you will mine. But I believe this is overcomplicated and unnecessary to solve the problem at hand.

**Comment by zookozcash** [comment] 2017-05-05 00:46
Red flag: Nathan mistakenly thought that the Incident Response team had required this ticket to be prioritised for 1.0.9. In fact the opposite was true, the Incident Response team (me as Executive Coordinator) had decided that we would take steps to fix the problem in the short term _explicitly under the assumption_ that this would not imply that this ticket would be prioritised for 1.0.9.

**Comment by zookozcash** [comment] 2017-05-05 23:30
The next step on this issue is diagnosis, experimentation, and benchmarking. Why does this issue not happen in Bitcoin?

**Comment by jameshilliard** [comment] 2017-05-06 10:16
> The next step on this issue is diagnosis, experimentation, and benchmarking. Why does this issue not happen in Bitcoin?

For some historical context 0.11.x bitcoind had major performance issues(it couldn't properly handle mining/propagation of 1MB blocks without the relay network and had some pretty severe performance degradation with mempools larger than a few megabytes) these were fairly well known issues at the time, and these issues were largely resolved with the 0.12 bitcoin core release(diagnosis, experimentation, benchmarking and of course writing the code to resolve them was done).

When I was operating a pool with 0.11.x I had to do a lot of mostly manual mempool monitoring and limiting to prevent GBT call times from being excessive. The performance issues were not due to a single cause but multiple factors and required major rewrites of a number of internal bitcoin core components to resolve.

Since zcash is a fork of 0.11.2 I would expect it to have those same issues bitcoin had back then.

You may want to rebase on top of bitcoin 0.14.1 since it has many performance improvements since 0.11.2.

**Comment by nathan-at-least** [comment] 2017-05-11 17:33
@jameshilliard Thanks for the context! Looks like we have our work cut out for us.

**Comment by daira** [comment] 2017-06-22 17:57
#2342, adding the ``-mempooltxinputlimit`` config option to limit the number of transparent inputs in transactions, is included in 1.0.10. Updating the milestone for remaining issues.

**Comment by daira** [comment] 2018-11-13 08:31
The original problem was mitigated by adding `-mempooltxinputlimit`, and then solved by fixing the quadratic hashing problem at Overwinter activation (which also removed `-mempooltxinputlimit`). If there are other tx validation performance improvements that could be pulled in from Bitcoin, that should be a separate ticket.

**Closed by daira** 2018-11-13 08:31 UTC
Labels: Denial of Service, PoW and mining, economics, performance, tx propagation/mining latency, usi

**Comment by daira** [comment] 2018-11-13 08:33
Note, incidentally, that we solved this without raising fees (denominated in ZEC) at all.
