### ISSUE TITLE
bad-txns-joinsplit-requirements-not-met

### ISSUE THREAD

**Issue by tromer** [zcash/zcash#3114] opened 2018-03-23 22:38 UTC
When using `z_sendmany` to create a simple z->t transaction with `zcashd` 1.0.5, I ran into the following error, as reported in `debug.log` (and similarly via `z_getoperationresult`):

```
... ERROR: AcceptToMemoryPool: joinsplit requirements not met
... opid-...: z_sendmany finished (status=failed, error=18: bad-txns-joinsplit-requirements-not-met)
```
No further hints that I can see. Note that it doesn't say which requirements were unmet; evidently the verbose debugging code fails to cover some case.

After a `zcashd -rescan`, the same transaction goes through. No other change, and with network disabled so no change in the blockchain.

I have this state reproducible in a VM snapshot.

**Comment by rex4539** [comment] 2018-03-23 22:41
I experienced the same recently and also fixed with `-rescan` but not sure what caused it...

**Comment by tromer** [comment] 2018-03-24 05:11
@ebfull, was your patch for verbose `bad-txns-joinsplit-requirements-not-met` debugging actually merged? At a glance, I actually don't see it in master.

**Comment by Voluntary-zcash** [comment] 2018-03-25 22:41
Is this related? https://github.com/zcash/zcash/issues/2938

**Comment by ioptio** [comment] 2018-04-02 18:26
@Voluntary-zcash probably not, different error message + symptoms

**Comment by pmoses987** [comment] 2018-05-18 04:32
I'm getting this error in the Windows Swing wallet.  How do I do this -rescan?

**Comment by rex4539** [comment] 2018-05-18 06:18
You need to run open a command line window and type `zcashd -rescan`

So basically you need to run the Zcash daemon with the `-rescan` argument.

**Comment by zcash-coins-gone** [comment] 2019-02-24 01:07
BEWARE: -rescan may EAT YOUR COINS. I just made this account to post here, because Zcash ate my coins. I started with approximately 6.36 zcash on private addresses, all sent to the same address. Experienced this "bug" (negligence and bad policy testing software on unsuspecting users) and did rescan after finding this bug thread. To my dismay, the balance available now is 4.83 zec TOTAL. 

So fixing the problem meant removing the coins from my wallet, tragedy. How can you continue on like nothing is wrong? The daemon should notify all users of this potential problem on boot up not veil it on some obscure github post while allowing people to lose their coins. "experimental software" = no liability and NO DISCLOSURE. That is just wrong. I have been using Zcash for years and I am seriously disappointed with the priorities of this management team.

BEWARE: -rescan may EAT YOUR COINS.

**Comment by mineZcash** [comment] 2019-02-24 15:19
@zcash-coins-gone I don't think it's possible for a `-rescan` with your local Node to eat anything.

Coins are stored _on the Blockchain_ not in your wallet. If you still have the private keys for your addresses then you still have your coins.

The `-rescan` command forces your Node to scan the Blockchain for transactions all the way back to block #1. What you are likely seeing is that your Node has not completed the rescan, and is not caught up with the latest Block height on the main chain.

Wait until your nodes block height matches the one here:  https://explorer.zcha.in and see if your coins show up.

**Comment by zcash-coins-gone** [comment] 2019-03-06 05:13
So maybe it is best to treat the customer as an ignorant fool who has no knowledge of blockchain (because most of them are, right?? ) than to BE SURE THE SOFTWARE WORKS BEFORE COMPROMISING THE UNSUSPECTING PUBLIC'S HARD EARNED CASH. This is an interesting justification. I happen to be a developer, also happen to be working on a Zcash wallet right now. Hilariously enough. I understand that you would expect the person with problems to be the idiot not the developers (who released "experimental", "unfinished" code and charged hundreds of millions of dollars to the public for it). To be honest, I am not totally versed on the inner workings of Zksnarks. For sure I know what -rescan (fking DUH brother) does. My screaming fast machine with super nand chips also did just fine on TOTALLY RESCANNING the blockchain and you better believe that I waited for it to TOTALLY FINISH before writing a post here on github. 

In short, it is not a viable solution to sweep the morally reprehensible approach of experimenting on the public under the rug by disclaiming my comment as that of one coming from an ignorant fool. I am neither, have been studying Zcash since shortly after it was released, and bitcoin for quite a bit longer. 

You still didn't tell me where my coins were or why they were *gone* from the wallet and your comment does nothing to fix anybody else's problems (with lost coins). However, just to humor you I will start a new wallet and import the privkey from the Z-address. If you don't hear back from me it's because my coins are still gone and nothing further has been said to add insult to injury. If my coins do show up again I will write here again, not to apologize for the mistakes of team Zcash, simply to publish (in the public interest) one way to recover coins that should have NEVER BEEN LOST IN THE FIRST PLACE.

**Comment by mineZcash** [comment] 2019-03-06 11:02
@zcash-coins-gone Just for clarification, I am not a developer and don't work for Zcash Company. I have seen plenty of new users stuck on a simple issue like thier node had not completely synced before when posting an issue. 

Also, how do you expect me to know your background whatsoever since you decided to create a new throw away account instead of using your super duper developer account?

Either way I hope you are able to find your coins importing your the keys to a different wallet.

**Comment by zcash-coins-gone** [comment] 2019-03-06 22:23
I don't care who you are, you simply insulted me and I let you know. I don't have a "super duper developer account" here on github, your assumptions are truly puzzling. I don't expect you to know anything but I do expect you not to go to default mode of dealing with a no-nothing-idiot. It looks bad for the company when somebody like you responds to "help" things you know nothing about with assumption of idiocy. I would expect you to not sidestep an explanation of a fundamental problem with the protocol (not myself thanks for attempting to shift the blame). Hey, I have an idea, let's use this venue for personal bickering instead of the pragmatic bug reporting that it was designed to be used for. That was sarcasm. Probably best not to speak when you have nothing to say.

**Comment by zcash-coins-gone** [comment] 2019-03-06 22:29
And don't you think it is a bit puzzling that the people who "work for Zcash" are mysteriously silent on this issue. Why? Because they know about it and already tried to close this thread. Thanks Daira, for being legitimate enough to re-open and "prioritize" it.  However, I feel this will have little result on the overall health and well-being of the network. It should have been "prioritized" above releasing the protocol on the public. This has been an issue since sprout and I was all but absolutely sure that the team had fixed it by now, until it happened again. The actual facts are that nobody even uses the zpayments, if they did there would be a lot more angry upset people who are losing coins. I have been a supporter of Zcash for years but always under the premise of knowing their ethics are highly suspect and questionable. Now that I see this problem still exists years later, I am a bit let down (again) by the whole thing. I know this isn't a venue for personal venting but when you report a problem and you are literally ignored, well I am absolutely astounded by the total lack of concern from the developers.

**Comment by tromer** [comment] 2019-03-06 22:34
@zcash-coins-gone, let's all focus on the technical issue at hand.

@mineZcash 's analysis in https://github.com/zcash/zcash/issues/3114#issuecomment-466785971 is accurate. There is also the possibility that the rescan code is buggy, but again this does not affect your ownership of the coins, just (at worst) whether your node can currently access them.

Also, I don't think your bug report is related to the original topic of this issue.

So if the problem persists even after you sync up now, please:
1. make a copy of your `~/.zcashd` directory for later analysis
2. run another `-rescan` just in case, and check if the coins become accessible
3. if not, run -reindex` (takes longer) and check if the coins become accessible
4. file a new bug and report your problem and findings there

**Comment by mineZcash** [comment] 2019-03-06 22:58
According to @tromer and @rex4359 this was an error that caused a failed send, which was then successfully sent by using the '-rescan' to get the transaction to go through. It didn't result in a loss of funds. Nobody else has posted that it causes loss of funds except for you. 

I was trying to help by walking you through things _that actually could_ cause an incorrect balance such as a un-synced wallet, a corrupted copy of the chain, etc.. 

But since you are more interested in grinding an axe with the developers than actually trying to diagnose your problem I won't be commenting further. 

Good day. 

CC @daira

**Comment by zcash-coins-gone** [comment] 2019-03-07 09:23
I didn't realize I was in your employ. Actually, wait a moment, I am not in your employ! The only thing Zcash has done for me personally so far, is lose my money. I think it is more in the interest of the public that I should create a formula to reproduce this problem and share the data with any number of local crypto news outlets. Thank you for your consideration, I know that ya'll know about this let's not play games. You need to fix it. promptly. This is a moral issue more than a technical one. 

However, I will follow some of those steps just to see if I can recover my coins.

The point is, they never should have been lost and your company is wasting my time and money as well as countless others.

**Comment by TheComputerGenie** [comment] 2019-03-24 07:28
> ...I happen to be a developer, also happen to be working on a Zcash wallet right now....

Anyone that actually believes that is a total moron.
How does a "developer" not know that a GUI is **not** a daemon?
How does a "developer" "working on a Zcash wallet" **not** see that _the rescan code **cannot** "eat" coins_?
@zcash-coins-gone is nothing more than a troll.

**Comment by daira** [comment] 2019-03-26 10:46
@zcash-coins-gone The problem you've encountered is not an instance of the original topic of this ticket. Keeping tickets focused on a single problem is essential. I second @tromer's suggestion that you open another ticket.

**Comment by mineZcash** [comment] 2019-05-17 22:24
Recent user having bad tx error,  '-rescan' didn't seem to work completely:  https://forum.zcashcommunity.com/t/coins-lost-after-rescan/33530

Any suggestions?

**Closed** 2020-10-27 03:18 UTC
Labels: C-bug, shielded address reliability, usi
