### ISSUE TITLE
Coredump: Assertion `tree.root() == old_tree_root' failed.

### ISSUE THREAD

**Issue by bitcartel** [zcash/zcash#2136] opened 2017-02-27 18:17 UTC
User reported a crash on the forum: https://forum.z.cash/t/zcashd-core-dumped/14269/13

Assertion:
zcashd: main.cpp:2116: bool ConnectBlock(const CBlock&, CValidationState&, CBlockIndex*, CCoinsViewCache&, bool): Assertion `tree.root() == old_tree_root' failed.

```
[New Thread 0x7fffbebd0700 (LWP 2852)]
zcashd: main.cpp:2116: bool ConnectBlock(const CBlock&, CValidationState&, CBlockIndex*, CCoinsViewCache&, bool): Assertion `tree.root() == old_tree_root' failed.

Thread 17 "zcash-msghand" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffd490f700 (LWP 2849)]
0x00007ffff6b5f428 in _GIraise (sig=sig@entry=6)
at ../sysdeps/unix/sysv/linux/raise.c:54
54	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt

0 0x00007ffff6b5f428 in _GIraise (sig=sig@entry=6)
at ../sysdeps/unix/sysv/linux/raise.c:54
1 0x00007ffff6b6102a in _GIabort () at abort.c:89
2 0x00007ffff6b57bd7 in _assertfail_base (fmt=,
assertion=assertion@entry=0x555555bc76ad "tree.root() == old_tree_root", 
file=file@entry=0x555555bc6d31 "main.cpp", line=line@entry=2116, 
function=function@entry=0x555555bd9a60 <ConnectBlock(CBlock const&, CValidationState&, CBlockIndex*, CCoinsViewCache&, bool)::__PRETTY_FUNCTION__> "bool ConnectBlock(const CBlock&, CValidationState&, CBlockIndex*, CCoinsViewCache&, bool)") at assert.c:92
3 0x00007ffff6b57c82 in _GI___assertfail (
assertion=assertion@entry=0x555555bc76ad "tree.root() == old_tree_root", 
file=file@entry=0x555555bc6d31 "main.cpp", line=line@entry=2116, 
function=function@entry=0x555555bd9a60 <ConnectBlock(CBlock const&, CValidationState&, CBlockIndex*, CCoinsViewCache&, bool)::__PRETTY_FUNCTION__> "bool ConnectBlock(const CBlock&, CValidationState&, CBlockIndex*, CCoinsViewCache&, bool)") at assert.c:101
4 0x000055555560d290 in ConnectBlock (block=..., state=...,
pindex=pindex@entry=0x7fffb8001300, view=..., 
fJustCheck=fJustCheck@entry=false) at main.cpp:2116
5 0x0000555555611b79 in ConnectTip (pblock=0x7fffd490ddb0,
pindexNew=0x7fffb8001300, state=...) at main.cpp:2479
6 ActivateBestChainStep (pblock=,
---Type to continue, or q to quit---
```

**Comment by daira** [comment] 2017-02-27 18:19
The assertion is here: https://github.com/zcash/zcash/blob/master/src/main.cpp#L2122

**Comment by ebfull** [comment] 2017-02-27 22:46
I would like to know the version.

**Comment by ebfull** [comment] 2017-02-27 22:56
This is likely caused by the bug we fixed in https://github.com/zcash/zcash/pull/1928

**Comment by ioptio** [comment] 2017-03-06 17:47
Must have been v1.0.2 or so? 
From https://forum.z.cash/t/zcashd-core-dumped/14269/16
> the wallet was built around the date 2016-11-24 I have never updated it,,, the wallet was just it that state it would never run so yes it was reproducible ,,,, I've had to rebuild the wallet now to get things moving ,,, I do still have copy of broken zcash and .zcash folders

**Comment by ioptio** [comment] 2017-03-06 18:11
Closing this ticket as it was an old version they had built.

**Closed by ioptio** 2017-03-06 18:11 UTC
Labels: bug, heisenbug, user support
