### ISSUE TITLE
uResultHeight == rewindHeight again?

### ISSUE THREAD

**Issue by docblocxxx** [zcash/zcash#6107] opened 2022-07-30 13:46 UTC
I am an operator of several nodes.

All of them work in
**txindex=1
experimentalfeatures=1
insightexplorer=1**

After getting update(5.2.0) via apt repositories

Node started crashing when trying zcashd(--daemon), without the possibility of restarting. (perhaps -rescan solves the problem temporarily)

```
tail -n 5 debug.log
2022-07-30T10:11:17.927094Z  INFO Init: main: ZKeys: 0 plaintext, 0 encrypted, 0 w/metadata, 0 total
2022-07-30T10:11:17.965964Z  INFO Init: main:  wallet                  152ms
2022-07-30T10:11:17.966092Z  INFO Init: main: init message: Rescanning...
2022-07-30T10:11:17.966106Z  INFO Init: main: CWallet::InitLoadWallet(): Rescanning last 1898 blocks (from block 1733780)...
2022-07-30T10:11:17.966398Z  INFO Init: main: CWallet::ScanForWalletTransactions(): Rewinding Orchard wallet to height 1735677; current is 1733780
```

i set **showmetrics=0**

and 
```
zcashd: wallet/wallet.cpp:4717: int CWallet::ScanForWalletTransactions(CBlockIndex *, bool, bool): Assertion `uResultHeight == rewindHeight' failed.
Aborted
```

first node
```
zcashd --version
Zcash Daemon version v5.2.0
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20.04
Codename:       focal
```

two node
```
zcashd --version
Zcash Daemon version v5.2.0
lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
```

wallet.dat contains keys generated by default.
5.1.0 - no problem observed.
5.0.0 - no problem observed.

**Important note**: all nodes are currently trying to download blocks from 0. rm all data folder, except zcash.conf
This error can occur at any height, usually when it reaches 17*****.

I think the problem is reproducible.
It seems that this error occurs when calling the **zcash-cli stop** command
and then running zcashd(--daemon).
Perhaps there is a problem with incorrect shutdown? (and subsequent launch which leads to `uResultHeight == rewindHeight` ).

A similar problem is described in
https://github.com/zcash/zcash/issues/5958

I think if you put on cron something like
(and run it every 5-10 minutes)

```
zcash-cli stop
sleep 10-30sec~ ///give time for the process to end.
zcashd -daemon
```

this problem can be easily reproduced. But is it really a problem of node not shutting down properly?

**Comment by str4d** [comment] 2022-08-01 12:55
This is very likely a duplicate of #5958. Closing this issue in favour of that one (but we can re-open this one if, once we've solved #5958, this issue continues to occur for you).

**Closed by str4d** 2022-08-01 12:55 UTC
