### ISSUE TITLE
Block timestamp validation too rough

### ISSUE THREAD

**Issue by miningpoolhub** [zcash/zcash#2012] opened 2017-01-11 06:13 UTC
Block 43273
https://explorer.zcha.in/blocks/000000004be64d3f7461b5304967db5a23d36b52a4d41e3e422dd8d0da005ce3

Block 43274 (1)
https://explorer.zcha.in/blocks/00000000334aded61fb369dd0b8a43de5cdabfbfad567a680c2b5eaace87aaf6

Block 43274 (2)
https://explorer.zcha.in/blocks/000000006a6ab0cddb2053d23e15ef44eb85cdaf0f06a2361523518b65a29396

43274 (1) is selected as main chain.
The problem is, 43274 (1) timestamp is 22 minutes earlier than previous block 43273
This seems incorrect timestamp validation which can lead to wrong forking.
Normally, 43274 (2) should be selected as main chain but it became orphan block.
(As https://explorer.zcha.in is not showing orphan blocks correctly, you have to query to zcash wallet directly)

**Comment by tromer** [comment] 2017-01-11 06:23
Duplicate of #1880? See discussion in #1889.

**Comment by bitcartel** [comment] 2017-01-11 20:13
@miningpoolhub Please post the decoded JSON output for the orphan block, Block 43274 (2).  Thanks.

**Comment by miningpoolhub** [comment] 2017-01-12 09:13
zcash-cli getblock 000000006a6ab0cddb2053d23e15ef44eb85cdaf0f06a2361523518b65a29396
```
{
    "hash" : "000000006a6ab0cddb2053d23e15ef44eb85cdaf0f06a2361523518b65a29396",
    "confirmations" : -1,
    "size" : 16213,
    "height" : 43274,
    "version" : 4,
    "merkleroot" : "e68047aab80047f029195e44ed9dac0d735b95600df9d159879ba24cf791273e",
    "tx" : [
        "f541bd475f3ccfc75622a613febe929a1f1d7b3448b369f8e3192016b0d71e3d",
        "1e199796df8aad97a3ab1fc758c69e00679cf8c427f01254915d2c378eefc7ba"
    ],
    "time" : 1484111489,
    "nonce" : "0400000000000000000000000000000000000000000000000581f190dbffff37",
    "solution" : "00322a8766913a6f779128868858fed72338da1c0b098a02917095da29ea8da3ab454d8cd4edda0ca6bf0df7f48f0d658803c8910340967f6b816713f4e3742d8b448519f25115a2b367225b4a85b300e4f8eab902afdbb6fa1775618b2ca288f1d6d3116ded9fd8aa10e4f367f37429edc43b7145490f4f247fa746726b129e17902e84db7c5d85b96029ea03bb834c5f55fb47abc66e9ae0056bb261c56e2564de2d7af2b3928100bd778669e7429ba624a48faf5ddb258ea4f0e5895941754cc71f06f3035f07e945fb946f1b4a7b67f03a9c077a9b9e683dabf807f969f2ccfabc90df3f804f78be2106f641cfd0d9f565d078eb43a6503d8b1209f573f8608972d9a7bdc5d8ea37938a2affd3b8c515e91bb4d122495b37d1022ae5dbaf05bbc5d338a0251fb789712bf0cfefa7b687276d373de4b091c3ea53b90511025ec48daf3786e7b6fe596abb0ed98d9000deaeb938eb1455efff233e9ae0189b62b63cea4d728b06ac0b77785bcc1887db0cee40a6422ad9a7a4140847c08299f8352c03e1f0003055c8e2e1de784d1db41d6487d330d4be01128c7e95fe3df6feb69bee0246767823587b8b271c3339f4b4d2e59d43b5f7533899528186906962a2aef5935f4ca0276032dfe953172e1a2cd70f48a4982712d9704133024429d81fd030f8970bf5d698f9526563fae2428ac52447b9a84f016120c2a729d3616fadc287107b166d6de6b1da4912400ec9515cb4f3bf02f91e2755c19a6b363ad4d7143301eb6b4965c8a2441224f153e4077ce35d7e9b247b71fea7ce3f25e0226619bfb9caae46179795c801885b3aa0fa5babe2a8025c4ff59bfcb3fb711db81ade3d4ff15ee1835224e20862cdef576b32bfab532174e4d0ac3cf7bbfd1b6423ae5eb999ae2abcf04a3b95f5056050382e986ca529d6b28c57d7619ec4d2015d980f4fca93376f7f970f12f5e7da0f86772f93160d55d9e41e91993c52117c63342121f903d7c59901c74978d70084e1a480a473206a2cf262a6f5f837134ff15d20328a6dc5a7a3cd37cb6e2a3b2fbfd17203933419f2457f80a60a7246b6947bb0cc2cfc02f826399a70cfded0d5f23d12888de04139d5a0104cd51e6615404b5e2c47434ea28f8a5705690b5b17a12d2fbac4f20678dd0bce44c380ecfc8818e1ad1cb8a409063b9b73628ae9149b1590b5b48e8d7c2d74113a1f2599b61d53b060a6371339ec3b9179a3808e5a3f0a60ea94ff2e15958824b310ba3445526057b745be3bb86fe6db57ae615c31756519df1a2962e89a62841432b776cf923939e050499133dffa0e6474d9dad51fa6a6c4ec5387d1da423693e068046a97b81c130e4cb1b44f9bab1939d45b3719af3c81272f4e7e408567b6bd0f5b61b18f3c3a280689dc508b1d9c7df78d01be700f10cd2ecb7170d1cc01b6deab00a9feddc244c9ef8efce92033c2f306fc7d4ecc66c568f847ab03ca45eeeb01f8d29c4c205fe668e530a08c26b83804a00a3458dcbecf66b218ecc2f050a2a93d3a01b103b433a488614725b4a6f434865776ad3f193231631fcd2b4d491f0837bc7445c59bb50faf41311df1e411781c37f73155cd8d8f72f44726c98a0a73f4bccb27d413f656e2228dd18b57063e3aa865e2d153f2b2036a750fd253a5c7677dc7b40acc0872bf94960d5f2f4ad1be656cb4a9a7e1b54591e0e719728430429d1fb2b55bd3b35585e13f8be08b621d4f4ee95d0cf935d7044d3d16dbe4cbcf240379420fe95905f751e30a090ab47552b7611e6d9138a6267f54fbe91d753790fb9f3499306521cabdf984a3f34a27e5539ff5110e68bda84fedf7b183af866fdbea8aa27b3f1cb141350c3d9c5198fc63071435fb72fc4429fb64923a50",
    "bits" : "1c6e174d",
    "difficulty" : 1219150.05977082,
    "chainwork" : "0000000000000000000000000000000000000000000000000000da5233cbf2ea",
    "previousblockhash" : "000000004be64d3f7461b5304967db5a23d36b52a4d41e3e422dd8d0da005ce3"
}
```

**Comment by bitcartel** [comment] 2017-01-16 21:59
The timestamp on Block 43274 (1) is valid under current consensus rules and should not lead to forking.  The timestamp is not the reason why Block 43274 (2) was orphaned.  Block 43274 (1) has a lower blockhash than Block 43274 (2).  Please see #1889 for potential changes to the timestamp consensus rules.

**Comment by ioptio** [comment] 2017-01-17 18:15
Since this is a duplicate ticket, I'm going to close this and ask you to continue discussion in #1889. Thanks!

**Closed by ioptio** 2017-01-17 18:15 UTC
Labels: user support
