### ISSUE TITLE
Missing conditional in native_clang.mk for macOS

### ISSUE THREAD

**Issue by rex4539** [zcash/zcash#4954] opened 2021-01-20 10:20 UTC
Native macOS.

```
Fetching native_clang...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
make: *** [/Users/rex/zcash/depends/sources/download-stamps/.stamp_fetched-native_clang-clang-llvm-11.0.0-x86_64-apple-darwin.tar.xz.hash] Error 22
```

A conditional is required for macOS (and Windows perhaps) as it uses 11.0.0, not 11.0.1

Bug was introduced with https://github.com/zcash/zcash/pull/4951

**Comment by str4d** [comment] 2021-01-20 10:26
We don't support native Windows compilation, but that's a good catch for macOS, thanks;

**Comment by str4d** [comment] 2021-01-21 15:17
Aha, the problem is that for `native_clang`, `$(package)_download_path` includes the version. Easily fixed by adding `$(package)_download_path_$(host)` etc. overrides, like we have for `$(package)_download_file` etc.

**Closed** 2021-01-22 00:26 UTC

**Comment by AloeareV** [comment] 2021-04-27 15:15
> I'm having the same problem, but with b2, and on Arch:
> 
> ```
> Fetching native_b2...
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
>   0    10    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
> curl: (22) The requested URL returned error: 403
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
> curl: (22) The requested URL returned error: 404
> make: *** [funcs.mk:249: /home/myname/zcash/depends/sources/download-stamps/.stamp_fetched-native_b2-boost_1_74_0.tar.bz2.hash] Error 22
> make: Leaving directory '/home/myname/zcash/depends'
> ```
> 
> The merged-in fix changes some lines in `depends/packages/native_clang.mk`, I'm not sure if that means the fix only works for clang, or if it's possible for me to override the b2 dependency. I'm also not sure how, #4956 doesn't actually say how to override the clang dep, only that it makes it possible to do so.

It appears that the issue has cleared itself up. Maybe the b2 host was temporarily down, or something. Not entirely sure.
