### ISSUE TITLE
zcashd thread deadlock

### ISSUE THREAD

**Issue by 5a1t** [zcash/zcash#1680] opened 2016-10-28 14:59 UTC
Zcashd experiences thread hangs under load and RPC becomes totally unresponsive.  Must be killed with -9 and restarted. I've attached to zcashd with gdb and dumped a stack trace of all threads:

http://pastebin.com/raw/Y1sGruD8

**Comment by 5a1t** [comment] 2016-10-28 15:06
We are experiencing this problem often, could likely provide ssh access to a zcashd if it would help.

**Comment by daira** [comment] 2016-10-28 15:22
Probable duplicate of #1652. Also see #1593.

**Comment by 5a1t** [comment] 2016-10-28 15:31
#1593 sounds like a duplicate, #1652 is a longpoll timeout but zcashd still responds to new connections.  Perhaps related.

**Comment by bitcartel** [comment] 2016-10-28 21:36
@5a1t What RPC commands are you calling frequently?  Upstream inherited Bitcoin calls?  Any z_ calls?

**Comment by feeleep75** [comment] 2016-10-29 21:13
same here - several stops today. Looks like zcashd is keeping open connections

**Comment by bitcartel** [comment] 2016-10-31 22:31
I'll take a look at this. @5a1t How many calls per second are you making?  Which RPC calls are you using the most when this happens.

**Comment by bitcartel** [comment] 2016-11-10 05:34
After some testing I can replicate.  Client software calling the RPC interface and using TCP keepalive can quickly hog all the rpc threads, which do not always release the socket, even if the client eventually time-outs. 

@5alt The simplest workaround is to add `rpckeepalive=0` to your zcash.conf.  Let me know if that works for you.

@daira I'm going to propose that we switch the default from 1 to 0, or disable the rpckeepalive option.

**Closed** 2016-11-15 11:14 UTC
Labels: RPC interface
