### ISSUE TITLE
z_mergetoaddress does not support concurrent execution

### ISSUE THREAD

**Issue by ppratscher** [zcash/zcash#3046] opened 2018-03-05 08:17 UTC
### Describe the issue
Assume having 100 unspent notes which should be merged into one t1 address. Each z_mergetoaddress, with the default settings, will merge 10 notes into one output. When starting the z_mergetoaddress call 10 times (without waiting before the previous async z_mergetoaddress call finishes) will cause the first call to succeed and all consecutive calls to fail with the "18: bad-txns-joinsplit-requirements-not-met" error.

#### If so, please list the steps to reproduce below:
1. Execute zcash-cli z_mergetoaddress '["ANY_ZADDR"]' t1xxx multiple times immediately after each other
2. The first call will succeed while all other consecutive calls will fail

### Expected behaviour
Similar to z_sendmany, z_mergetoaddress should support firing off multiple calls at once.

### The version of Zcash you were using:
1.0.15

**Comment by bitcartel** [comment] 2018-03-05 22:31
Hi, when you say "without waiting" are you firing off the RPC calls from code eg. a Python client?  Or do you mean on the command line?  Thanks.

**Comment by str4d** [comment] 2018-03-06 10:17
Firstly, thanks for testing this experimental feature! :smile:

I believe this is because there is no locking mechanism for notes yet. `z_mergetoaddress` selects notes before creating the async operation (in order to provide note value feedback to the user). The same note is probably being selected multiple times, because all of the RPC calls happen in sequence in the time it takes to finish the first async call, after which the notes become spent and later calls fail.

It doesn't affect `z_sendmany` because note selection happens inside the async call, and the async runner currently only has a single thread, so all async operations happen in the order they were created. But if/when we add concurrent creation, `z_sendmany` would also have this problem.

The solution is to implement note locking and unlocking, which is #1377. See also #1277.

**Comment by ppratscher** [comment] 2018-03-06 10:24
Thanks for your response. After going over the z_sendmany implementations and its comments I figured that it will be related to the missing note locking.

Looking forward to the note locking implementation as it will certainly make the call more usable and less error prone.

**Comment by str4d** [comment] 2018-03-06 15:09
I have reproduced this issue in an RPC test.

**Comment by bitcartel** [comment] 2018-03-27 22:59
@str4d Where's the RPC test that reproduces the issue? I'd like to take a look. Thx.

**Comment by str4d** [comment] 2018-03-27 23:14
@bitcartel it's the first commit in the note locking PR

**Comment by braddmiller** [comment] 2018-03-28 01:08
@bitcartel, as a followup to what @str4d said. The first commit in the PR has the original RPC tests, but they're slightly flawed. My understanding is that only one 0 fee note can be included in any single block. So the fee on one or both `result1` and `result2` should be changed to something >0.

**Comment by daira** [comment] 2018-03-28 09:59
I wasn't aware of such a rule. Where is it implemented?

**Comment by braddmiller** [comment] 2018-03-28 13:14
In `CreateNewBlock` in miner.cpp there is this idea of skipping a free transaction if the minimum block size is met. Check the few lines following this link. https://github.com/braddmiller/zcash/blob/b3a656cf535df043450cca4dc92a9137adc773f5/src/miner.cpp#L267

This manifested in the RPC tests as showing two transactions in the mempool corresponding to `result1` and `result2` but only including one at a time when `generate` was called and leaving the other in the mempool. Once a non-zero fee was set `generate` was able to include both.

**Comment by bitcartel** [comment] 2018-03-28 19:02
The conditional around `continue` won't ever evaluate to true, since `bool fSortedByFee = (nBlockPrioritySize <= 0);` which is false, as `nBlockPrioritySize = std::min(nBlockMaxSize, nBlockPrioritySize);` and if you work backwards and check the various constants, you'll find that `nBlockPrioritySize` is a big positive number.

**Comment by braddmiller** [comment] 2018-03-28 20:18
Not sure it's true that this conditional will never evaluate to true, at least in the context of regtest. Doing manual debugging output to the console I believe I received a printout from inside that conditional, which is the only reason I noticed the 0 fee issue.

**Comment by braddmiller** [comment] 2018-04-02 15:48
This issue should be resolved by PR 3106 which has been incorporated into master. If this issue persists please reopen this ticket and provide additional details on the failure.

**Closed by braddmiller** 2018-04-02 15:48 UTC
Labels: RPC interface, bug, has PR, note selection and JoinSplit construction, usability, wallet
