### ISSUE TITLE
z_listtransactions

### ISSUE THREAD

**Issue by abrkn** [zcash/zcash#5290] opened 2021-09-08 08:41 UTC
## Problem

- I send funds using `z_sendmany`
- It returns an operation id
- The node stalls
- I restart the node
- I query the status of the operation id
- The operation id is unknown to the node

I now have a useless operation id and no txid to check with z_viewtransaction. I have no way to know if the funds were sent.

## Possible workarounds

- Compare balance from before and after. This is only possible if I recorded my balance before `z_sendmany`
- Iterate over output from `z_listunspent`, using `z_viewtransaction` to see if any were sent to the recipient. Also very impractical and becomes unreliable if I send another tx

## Solution

A) Add a `z_listtransactions` that at least outputs recently sent shielded transaction txids
B) Allow user to configure how long operation ids live for. I'd like to store mine for days or months

**Comment by steven-ecc** [comment] 2021-09-23 05:12
Closing. Duplicate of #5030.

**Closed by steven-ecc** 2021-09-23 05:12 UTC
Labels: use case
