### ISSUE TITLE
Rescanning about 1000 blocks every time daemon restarts.

### ISSUE THREAD

**Issue by miningpoolhub** [zcash/zcash#1864] opened 2016-11-16 15:53 UTC
zcash daemon is quite slow at start by block verification process.
When I type "zcash-cli stop" and restart, mostly it start to rescan about last 1000 blocks.

How can I reduce this number?
As zcash daemon crashes frequently corrupting wallet.dat file, it would be better if block verification to take shorter time. It nearly needs more than a hour just for restarting.

**Comment by etherchain-org** [comment] 2016-11-16 16:21
I can confirm this issue. But it is not 100% reproducible. Sometimes zcash just scans the last ~12 blocks after a restart, sometimes it scans the last 1000 blocks. Up to now I was unable to figure out what influences the number of re-scanned blocks.

**Comment by str4d** [comment] 2016-11-17 03:51
That rescan feature was inherited from Bitcoin, and it unfortunately *is* somewhat random as to how many block it rescans.

The way it works (AFAICT) is that it finds a common parent between the "best block" stored in the wallet, and the chain tip. The wallet only writes out the "best block" every few minutes or hours IIRC, as well as after that rescan-on-start. Additionally, the algorithm for finding a common parent searches linearly through the last 10 or so blocks, and then exponentially further back. So in some cases, the node can end up rescanning quite a few blocks.

What causes it to be slower for us than Bitcoin is that during the rescan, the wallet is attempting to decrypt every JoinSplit between the common parent and the chain tip. Thus the time scales linearly with the number of z-addrs in the wallet.

**Comment by bitcartel** [comment] 2016-11-19 06:52
Related to #1749 where optimisations can be made.

**Comment by bitcartel** [comment] 2016-12-01 01:08
Update:
1. We have identified the bulk of the time is spent writing to disk and we have a work-in-progress PR attached to #1749 which will fix this
2. The number of blocks to rescan, per the comment above, is related to when the best block was written to disk which normally occurs every hour.

**Comment by ioptio** [comment] 2016-12-06 21:43
Closing this because issue #1749 is related. If @miningpoolhub has further comments, I suggest you to check out that issue first. This issue can be re-opened if preferred.

**Closed by ioptio** 2016-12-06 21:43 UTC
Labels: performance, user support, wallet
