### ISSUE TITLE
Streamlined parameter download and Sprout soft-deprecation

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#4491] opened 2020-05-01 22:28 UTC
## Is your feature request related to a problem? Please describe.

Currently, when users install `zcashd` for the first time, they must make sure to run `zcash-fetch-params`. This extra step is an annoyance to getting running quickly.

Additionally, few users need the older `Sprout` proving parameters, which are the largest parameters to download, coming in a bit under 700Mb.

## Describe the solution you'd like

#. Change the `zcashd` wallet code to add a new config parameter `enable_old_sprout` with default `false`.
#. At the launch of `zcashd` _before_ the current `main()` functionality, execute the equivalent of `zcash-fetch-params` *except* that if `enable_old_sprout` is not `true`, it will skip downloading the `sprout` proving params.
#. During runtime, if any operation would require Sprout proving params but `enable_old_sprout` is not `true`, then return a friendly error message like "Sprout wallet support requires setting `enable_old_sprout=true` and restarting `zcashd`." Otherwise the operation proceeds as normal.

**Outcomes:**

- For all users, there is no step to manually run `zcash-fetch-params` any more. They just run `zcashd`, which downloads the necessary params if they aren't already in place.
- For Sprout users who don't read release notes or documentation carefully, they will see a user-friendly error the next time they try to use a Sprout proving param (such as by transferring Sprout funds). That error message instructs them to set `enable_old_sprout=true` and restart. If they do that, if they don't have the Sprout proving params, they will be downloaded. Operation will then proceed as normal.

## Alternatives you've considered

This is an alternative to bundling params directly in the binary as per https://github.com/zcash/zcash/issues/3933. @rex4539 pointed out that makes the binaries much larger. By contrast, this approach has the exact same runtime behavior as before, it's simply that there's one less step for users to remember and execute along with simpler instructions.

Meanwhile, this also skips downloading Sprout proving params for new users, who are very unlikely to use them. This saves ~700MB of bandwidth and the associated delay before they see the cute `zcashd` console screen for a dopamine hit. ;-)

## Additional context

- This relates to #3788 but should happen well before protocol-level deprecation, such as #3752 or #4479.
- Note that Canopy/NU4 may introduce [ZIP 211](https://zips.z.cash/zip-0211) which is mostly orthogonal to the `enable_old_sapling` logic described here. However, to be friendly to users if ZIP 211 is likely to activate soon, the error message for this ticket should mention that. Something like:

> Sprout functionality is being retired. Sprout wallet support requires setting `enable_old_sprout=true` and restarting `zcashd`. Additionally, due to [ZIP 211](https://zips.z.cash/zip-0211) it is no longer possible to send funds into Sprout addresses from t-addrs or Sapling addresses. We recommend migrating Sprout funds into a new Sapling address. See `z_setmigration`.

**Comment by daira** [comment] 2020-05-02 11:25
Note that #1335 would hard-code only the verifying keys. If downloading the Sprout `.params` file is optional, then #1335 is a blocker because we currently rely on the `.params` file containing the verifying key. A full node always has to be able to verify JoinSplits even if it doesn't create them.

**Comment by sellout** [comment] 2022-11-16 18:08
We no longer fetch either the verifying keys or Sprout params with `fetch-params` now, right?

So this issue is just “fold `fetch-params` into `zcashd`” now?

**Comment by daira** [comment] 2023-05-11 22:30
This is essentially a duplicate of / obviated by #3933.

**Closed by daira** 2023-05-11 22:30 UTC
Labels: use case
