### ISSUE TITLE
Zcashd suddenly stops

### ISSUE THREAD

**Issue by freebeego** [zcash/zcash#6096] opened 2022-07-23 22:30 UTC
```
2022-07-23T22:09:30.875072Z INFO Init: main: CWallet::ScanForWalletTransactions(): Rewinding Orchard wallet to height 1722620; current is 1722621
2022-07-23T22:11:26.791932Z INFO Init: main: Still rescanning. At block 1722622. Progress=0.984543
2022-07-23T22:16:09.889345Z INFO main:

2022-07-23T22:16:09.889366Z INFO main: Zcash version v5.2.0-rc1-g18223753eed (Fri, 22 Jul 2022 17:06:03 -0600)
```

**Comment by freebeego** [comment] 2022-07-23 22:30
@str4d ?
it always restarts

**Comment by freebeego** [comment] 2022-07-23 22:59
when I tried indexing this wallet without blockchain. then zcash started download blockchain. then when blockchain was almost downloaded it took almost all memory and zcashd restarted over and over again.
![unknown](https://user-images.githubusercontent.com/69243332/180625507-ca1b99cc-665a-43dc-ae76-3763a50e84f8.png)
.

**Comment by freebeego** [comment] 2022-07-24 14:00
I suppose it's related to this issue.

One of my wallets ended rescan. It's cool!

<code>
2022-07-24T10:40:36.883335Z  INFO Init: main: Still rescanning. At block 1733130. Progress=0.990663
2022-07-24T10:42:26.397759Z  INFO Init: main: Still rescanning. At block 1733133. Progress=0.990670
2022-07-24T10:43:28.197319Z  INFO Init: main: Still rescanning. At block 1733135. Progress=0.990670
2022-07-24T10:44:32.233626Z  INFO Init: main: Still rescanning. At block 1733139. Progress=0.990671
2022-07-24T10:45:34.977605Z  INFO Init: main: Still rescanning. At block 1733145. Progress=0.990672
2022-07-24T10:46:35.730505Z  INFO Init: main: Still rescanning. At block 1733150. Progress=0.990673
2022-07-24T10:50:43.221261Z  INFO Init: main: Still rescanning. At block 1733155. Progress=0.990674
2022-07-24T10:54:31.786322Z  INFO Init: main: Still rescanning. At block 1733159. Progress=0.990674
2022-07-24T10:55:04.152035Z  INFO Init: main:  rescan            132195086ms
2022-07-24T10:55:04.276632Z  INFO Init: main: mapBlockIndex.size() = 1733605
2022-07-24T10:55:04.276648Z  INFO Init: main: nBestHeight = 1733160
2022-07-24T10:55:04.276654Z  INFO Init: main: setKeyPool.size() = 100
2022-07-24T10:55:04.276656Z  INFO Init: main: mapWallet.size() = 52
2022-07-24T10:55:04.276662Z  INFO Init: main: mapAddressBook.size() = 1
2022-07-24T10:55:04.276847Z  INFO main: txnotify thread start
2022-07-24T10:55:04.277407Z  INFO main: torcontrol thread start
2022-07-24T10:55:04.277753Z  INFO Init: main: init message: Loading addresses...
2022-07-24T10:55:04.296894Z  INFO Init: main: Loaded 12950 addresses from peers.dat  19ms
2022-07-24T10:55:04.296913Z  INFO Init: main: init message: Loading banlist...
2022-07-24T10:55:04.298376Z  INFO Init: main: init message: Starting network threads...
2022-07-24T10:55:04.769392Z  INFO main: UpdateTip: new best hash=000000000149d75fb3fa73329532fac7b8279c18fab2ff4598a36d1f77bbbabc height=1733161 bits=469893382 log2_work=59.286891 tx=11053439 date=2022-07-10 22:35:23 progress=0.990675 cache=1.8MiB(6tx)
2022-07-24T10:55:04.786301Z  INFO main: UpdateTip: new best hash=0000000001bb769be25148506ff176b1eb4e6bc330fdf1efa68f5849280f2c9a height=1733162 bits=469892572 log2_work=59.286892 tx=11053440 date=2022-07-10 22:35:41 progress=0.990675 cache=1.8MiB(7tx)
2022-07-24T10:55:05.368078Z  INFO main: UpdateTip: new best hash=0000000000db5cbc8ee19e4890f823b81e5b93b78abdd1a423dbaa7a0204051c height=1733163 bits=469890888 log2_work=59.286893 tx=11053451 date=2022-07-10 22:36:47 progress=0.990676 cache=1.8MiB(16tx)
</code>

...
Then sync process was started. 
...
<code>
2022-07-24T11:03:11.098250Z  INFO main: UpdateTip: new best hash=000000000061fce71b6ec74badd41ec99a8a0ac199ab566c834d8a99dd73c496 height=1733600 bits=469882895 log2_work=59.287443 tx=11058681 date=2022-07-11 07:51:59 progress=0.990942 cache=11.0MiB(1837tx)
2022-07-24T11:03:12.443906Z  INFO main: UpdateTip: new best hash=000000000162f72306c822167dbdbfc4b46024deebbb2b04fa4bbf7cf685523c height=1733601 bits=469884504 log2_work=59.287445 tx=11058685 date=2022-07-11 07:52:15 progress=0.990942 cache=11.0MiB(1838tx)
2022-07-24T11:03:13.837506Z  INFO main: UpdateTip: new best hash=0000000001a7d0a5fa24f7dafa5e9e3f48ea98a00af294028134b783f2bffd8e height=1733602 bits=469888269 log2_work=59.287446 tx=11058689 date=2022-07-11 07:52:27 progress=0.990942 cache=11.0MiB(1841tx)
2022-07-24T11:03:14.509688Z  INFO main: receive version message: /MagicBean:5.0.0/: version 170100, blocks=1748661, us=0.0.0.0:37456, peer=2
2022-07-24T11:03:15.513808Z  INFO main: socket recv error Connection reset by peer (104)
2022-07-24T11:03:15.968171Z  INFO main: receive version message: /MagicBean:5.0.0/: version 170100, blocks=1748661, us=0.0.0.0:50838, peer=4
**2022-07-24T12:14:27.429928Z  INFO main:** 



2022-07-24T12:14:27.430143Z  INFO main: Zcash version v5.2.0-rc1-g18223753eed (Fri, 22 Jul 2022 17:06:03 -0600)
</code>

it suddenly stop.
It's so sad. I didn't find some log messages in syslog
@str4d Can I help you to debug it?

**Comment by autotunafish** [comment] 2022-07-24 23:47
You should try upgrading to 5.1.0

**Comment by docblocxxx** [comment] 2022-07-30 13:18
I am an operator of several nodes.

All of them work in


After getting update(5.2.0) via apt repositories

Node began to crash, without the possibility of restarting. (perhaps -rescan solves the problem temporarily)


```
tail -n 5 debug.log
2022-07-30T10:11:17.927094Z  INFO Init: main: ZKeys: 0 plaintext, 0 encrypted, 0 w/metadata, 0 total
2022-07-30T10:11:17.965964Z  INFO Init: main:  wallet                  152ms
2022-07-30T10:11:17.966092Z  INFO Init: main: init message: Rescanning...
2022-07-30T10:11:17.966106Z  INFO Init: main: CWallet::InitLoadWallet(): Rescanning last 1898 blocks (from block 1733780)...
2022-07-30T10:11:17.966398Z  INFO Init: main: CWallet::ScanForWalletTransactions(): Rewinding Orchard wallet to height 1735677; current is 1733780
```

i set **showmetrics=0**

and 
```
zcashd: wallet/wallet.cpp:4717: int CWallet::ScanForWalletTransactions(CBlockIndex *, bool, bool): Assertion `uResultHeight == rewindHeight' failed.
Aborted
```

first node
```
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20.04
Codename:       focal
```

two node
```
lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
```

wallet.dat contains keys generated by default.
5.1.0 - no problem observed
5.0.0 - no problem observed.

**Comment by str4d** [comment] 2022-08-01 13:05
> when blockchain was almost downloaded it took almost all memory and zcashd restarted over and over again.

This is likely a duplicate of #6085. Let's track this over there.

**Closed by str4d** 2022-08-01 13:05 UTC
