### ISSUE TITLE
How to make own chain

### ISSUE THREAD

**Issue by kensukekita** [zcash/zcash#2681] opened 2017-10-24 01:27 UTC
hello all my question is how to make my own chain to can make my own coin based on zcash?
i was editing the chain params but i dont know where to get the genesis block hash

**Comment by chenhuan14** [comment] 2017-10-25 01:34
you can use the regtest mode lik bitcoin.

**Comment by marcofortina** [comment] 2017-12-13 23:45
Hello folks!
I have the same problem. It's not really clear on how to generate genesis block for regtest that include an equihash solution. I used the GenesisZ python script with silentarmy for mainnet and testnet but this software does not support regtest. Any advise?
Thanks.

**Comment by chenhuan14** [comment] 2017-12-14 14:54
hello, 
 see https://www.youtube.com/watch?v=86jqAfySi64 <https://www.youtube.com/watch?v=86jqAfySi64> for building private chain.

**Comment by marcofortina** [comment] 2017-12-14 19:05
@chenhuan14 I've already create my altcoin and the video that you posted here is for using scrypt as POW... I use equihash so it's not usefull for me.

What I need, as I wrote before, is to generate only the regtest genesis equihash solution (I've already done it for mainnet and testnet)

Thanks,
Marco

**Comment by aleqx** [comment] 2018-02-03 02:30
I'm also interested in this. Are there any guides out there on how to do this?

**Comment by braravind** [comment] 2018-02-28 10:45
I also want  to create my own chain. so please guide me how to create genesis block and how to setup this.

**Comment by ioptio** [comment] 2019-07-10 17:53
Duplicate of https://github.com/zcash/zcash/issues/3029 which is now tracked at https://gitlab.com/zcash-docs/zcash-docs/issues/41

**Closed by ioptio** 2019-07-10 17:53 UTC
Labels: blockchain genesis, documentation
