### ISSUE TITLE
The download traffic is several times larger than the downloaded data

### ISSUE THREAD

**Issue by bigbrain** [zcash/zcash#4624] opened 2020-07-18 12:23 UTC
Hello
I ran the program for a new sync and watched the network traffic
For example: File blk00000.dat about 130 MB but was downloaded about 750MB.
Files blk00000.dat and blk00001.dat about 260MB but was downloaded about 1.5GB.
For 40 .dat files (5GB), about 30GB was downloaded.
I think it's wrong. I don’t want download 200GB instead 30GB blockchain.

Zcash Daemon version v3.0.0-e3aae37
Windows 10 x64 and also tried on Windows 7 x64
was set  ibdskiptxverification=1
8 peers were connected
There are no errors in debug.log. Only sometimes:
ERROR: ContextualCheckTransaction(): overwinter is not active yet
ERROR: AcceptToMemoryPool: ContextualCheckTransaction failed

**Comment by Sheldon11F** [comment] 2020-07-18 15:38
It's the same for me. Why do you write that you need to download 28 GB? I downloaded 2 times and the traffic eats more than 100GB for 4-5 days with a good Internet. I downloaded the same monero blockchain in 2 days 60GB. Make it easier to download the blockchain !!!

**Comment by secured2k** [comment] 2020-07-20 05:40
There is additional downloaded and verified by your CPU during an initial block download. To save some space some data is not stored on the node. There are some options to enable saving that extra data but not many regular users use it so it is off by default. With most data saved, you can expect 2.5 times larger data stored on the node. For example the current 22.3GB blockchain could take up over 55.75GB.

**Comment by bigbrain** [comment] 2020-07-31 15:05
During the download process, the loaded header counter increases much faster than the block counter. The header counter value can be hundreds of thousands more than the block counter value. When the server stops and the download is interrupted, the downloaded headers are likely not being saved. Because at the next start, the counter of loaded headers is again equal to the number of loaded blocks. These hundreds of thousands of headers are being downloaded again.. It is possible that this is wasted traffic.

I also noticed that over time, all the counters are updated less and less. At the same time, the network congestion has not decreased, the entire channel is clogged. And the CPU does not process anything (about 3% of the total load) It's just that something is being downloaded.

**Comment by bigbrain** [comment] 2020-08-02 16:07
On the testnet I have this problem stronger.

Within about an hour I downloaded 9.5GB from the network (watched the traffic). The whole channel was filled with the downloaded data. But only about 80MB was written to the .dat file.

For this period, I turned on full logging. Attached it to this post. Unpacked it is more than 70MB. Maybe it will help solve this problem.

[debug.zip](https://github.com/zcash/zcash/files/5012401/debug.zip)

**Comment by bigbrain** [comment] 2020-08-03 23:27
Hello, I think I found how to solve it.

This problem was inherited from bitcoin. It was already solved in it in 2016.

> The current logic for syncing headers may lead to lots of duplicate getheaders requests being sent: If a new block arrives while the node is in headers sync, it will send getheaders in response to the block announcement. When the headers arrive, the message will be of maximum size and so a follow-up request will be sent---all of that in addition to the existing headers syncing. This will create a second "chain" of getheaders requests. If more blocks arrive, this may even lead to arbitrarily many parallel chains of redundant requests.

[https://github.com/bitcoin/bitcoin/pull/8054](https://github.com/bitcoin/bitcoin/pull/8054)

To fix it, need to add two lines to the main.cpp
Here's the solution: [https://github.com/bitcoin/bitcoin/pull/8054/files](https://github.com/bitcoin/bitcoin/pull/8054/files)

Dear developers, please fix it

**Comment by secured2k** [comment] 2020-08-06 00:39
Thanks for taking the time to investigate and report this.

I can confirm your original issue and hope this get resolved in a future release.

-----
```
31 min, 7 sec
Downloaded: 10.07 GB, No-TX, 1 Connection
Size of Data on Disk: 1.95 GB (2,100,155,169 bytes)
Downloading blocks | 51079 (511200 headers) / ~925900 (5%)
Validated 625141 transactions!
```

-----
```
31 min, 10 sec.
Downloaded: 11.41 GB, No-TX, Up to 8 Connections
Size of Data on Disk: 2.46 GB (2,642,902,622 bytes)
Downloading blocks | 94308 (255200 headers) / ~928380 (10%)
Validated 1104826 transactions!
```

-----
```
31 minutes, 9 sec.
Downloaded: 14.86 GB, Full-TX, Up to 8 Connections
Size of Data on Disk: 4.28 GB (4,598,323,047 bytes)
Downloading blocks | 69350 (323200 headers) / ~927690 (7%)
Validated 791691 transactions!
```

**Comment by bigbrain** [comment] 2020-08-11 11:16
That old solution to the Bitcoin problem was later reversed. Because: «This can cause synchronization to get stuck». Perhaps an alternative solution to this problem needs to be found.

**Comment by bigbrain** [comment] 2020-09-06 13:50
While this problem has not been fixed yet, I made a temporary fix for myself based on solutions from **domob1812**, **DeckerSU** and **OleksandrBlack**. I'm not sure if this is correct or if it's safe, but after a week of use, I haven't had any problems. This fix helped me sync the blockchain and greatly reduced network traffic. I've used it on versions 3.1.0 and 4.0.0.
This fix is automatically disabled after initial sync. It can also be disabled completely by running the program with the `-fixibd=0` argument.

**`main.cpp : ProcessMessage function`**
```
        if (nCount == 0) {
            // Nothing interesting. Stop asking this peer for more headers.
            return true;
        }

+        // If we already know the last header in the message, then it contains
+        // no new information for us.  In this case, we do not request
+        // more headers later.  This prevents multiple chains of redundant
+        // getheader requests from running in parallel if triggered by incoming
+        // blocks while the node is still in initial headers sync.
+        bool hasNewHeaders = true;
+        if (GetBoolArg("-fixibd", true) && IsInitialBlockDownload(chainparams)) {
+            hasNewHeaders = (mapBlockIndex.count(headers.back().GetHash()) == 0);
+            LogPrint("net", "IBD fix enabled: peer=%d\n", pfrom->id);
+        }

        CBlockIndex *pindexLast = NULL;
        BOOST_FOREACH(const CBlockHeader& header, headers) {
            CValidationState state;
            if (pindexLast != NULL && header.hashPrevBlock != pindexLast->GetBlockHash()) {
                Misbehaving(pfrom->GetId(), 20);
                return error("non-continuous headers sequence");
            }
            if (!AcceptBlockHeader(header, state, chainparams, &pindexLast)) {
                int nDoS;
                if (state.IsInvalid(nDoS)) {
                    if (nDoS > 0)
                        Misbehaving(pfrom->GetId(), nDoS);
                    return error("invalid header received");
                }
            }
        }

        if (pindexLast)
            UpdateBlockAvailability(pfrom->GetId(), pindexLast->GetBlockHash());

+        if (nCount == MAX_HEADERS_RESULTS && pindexLast && !hasNewHeaders)
+            LogPrint("net", "IBD fix applied: no more getheaders (%d) to send to peer=%d (startheight:%d)\n", pindexLast->nHeight, pfrom->id, pfrom->nStartingHeight);

+        if (nCount == MAX_HEADERS_RESULTS && pindexLast && hasNewHeaders) {
-        if (nCount == MAX_HEADERS_RESULTS && pindexLast) {
            // Headers message had its maximum size; the peer may have more headers.
            // TODO: optimize: if pindexLast is an ancestor of chainActive.Tip or pindexBestHeader, continue
            // from there instead.
            LogPrint("net", "more getheaders (%d) to send to peer=%d (startheight:%d)\n", pindexLast->nHeight, pfrom->id, pfrom->nStartingHeight);
            pfrom->PushMessage("getheaders", chainActive.GetLocator(pindexLast), uint256());
        }

        CheckBlockIndex(chainparams.GetConsensus());

```

**Comment by LarryRuane** [comment] 2021-01-08 02:01
@bigbrain 
> That old solution to the Bitcoin problem was later reversed

[Here](https://github.com/bitcoin/bitcoin/pull/8306) is the PR that reverted the original [PR](https://github.com/bitcoin/bitcoin/pull/8054). [Here](https://github.com/bitcoin/bitcoin/pull/8306#issuecomment-231584578) is a very useful comment that explains at least one way the original PR can cause a problem:

> One example: before reverting this patch, if there are two competing forks with tips A and B, and a node is at tip A and the fork point C between A and B is more than 2000 blocks in the past, and a node already has the first 2000 headers from C to B but no later ones, then it's possible that the hasHeaders check added by #8054 would prevent the node from ever learning about tip B, causing chain sync to fail.

The relevance of 2000 is that it is the [maximum number of entries](https://github.com/bitcoin/bitcoin/blob/86a8b35f321d55bb2381ea56bcc1cdd17c7896e6/src/net_processing.cpp#L99) in the `headers` message (which is the "reply" message to `getheaders`). In zcash, this constant is 160 (see #1289).

I experimentally verified that Bitcoin Core does still have this problem, but it's somewhat minor there because its IBD downloads only headers first, before downloading any blocks. The `debug.log` file (mainnet) has an entry for every 2000 headers fetched, and only after they're all fetched does it begin to download blocks:
``` 
2021-01-06T21:22:02Z Synchronizing blockheaders, height: 2000 (~0.32%)
2021-01-06T21:22:02Z Synchronizing blockheaders, height: 4000 (~0.64%)
2021-01-06T21:22:03Z Synchronizing blockheaders, height: 6000 (~0.95%)
(...)
2021-01-06T21:38:10Z Synchronizing blockheaders, height: 654000 (~98.37%)
2021-01-06T21:38:12Z Synchronizing blockheaders, height: 656000 (~98.72%)
2021-01-06T21:38:14Z Synchronizing blockheaders, height: 658000 (~99.00%)
2021-01-06T21:38:16Z UpdateTip: new best=00000000839a8e6886ab5951d76f411475428afc90947ee320161bbf18eb6048 height=1 version=0x00000001 log2_work=33.000022 tx=2 date='2009-01-09T02:54:25Z' progress=0.000000 cache=0.0MiB(1txo)
2021-01-06T21:38:16Z UpdateTip: new best=000000006a625f06636b8bb6ac7b960a8d03705d1ace08b1a19da3fdcc99ddbd height=2 version=0x00000001 log2_work=33.584985 tx=3 date='2009-01-09T02:55:44Z' progress=0.000000 cache=0.0MiB(2txo)
2021-01-06T21:38:17Z UpdateTip: new best=0000000082b5015589a3fdf2d4baff403e6f0be035a5d9742c1cae6295464449 height=3 version=0x00000001 log2_work=34.000022 tx=4 date='2009-01-09T03:02:53Z' progress=0.000000 cache=0.0MiB(3txo)
```
On my system, downloading all the headers took only about 16 seconds, as you can see from the timestamps. I noticed that if a new block is found _during_ this time (which didn't happen in the logs shown here), bitcoind will begin sending the redundant `getheaders` messages. This isn't too bad, because:
- it's unlikely that a new block will appear during this short time interval, especially with Bitcoin's 10-minute blocks
- if that does happen, it only persists for a few seconds because then the headers will have finished downloading

I did see that 12 identical header messages (2k entries each) were repeated 11 times each. That was the worst-case; there were others repeated 10 times, 9 times, and so on. Overall, the node received 1.7 times as many headers as it should have (1129722 vs 664858). This, of course, depends very much on exactly when the new block arrived during the 16 seconds.

To sum it up, then, this isn't a big problem for Bitcoin and that's probably why this problem still exists today.

When zcashd is doing initial sync (IBD), it interleaves fetching headers with fetching blocks. I think we inherited that behavior from Bitcoin Core, which later changed (as described, all headers first, then all blocks). This is why the problem is worse for us:
- it takes much longer for zcashd to finish fetching headers (since it's also busy fetching blocks)
- many new blocks can be mined during that time, especially with our lower 75 second block time
- when zcashd does get into this redundant-headers messages state, it's worse because our headers are larger (1487 bytes, versus 80 bytes)

Here's the good news:

The zcashd node will never reorg more than 100 blocks. (Bitcoin Core has no such limit.) Since a full `headers` message contains 160 entries (these messages are always full during IBD), the [problem quoted above](https://github.com/bitcoin/bitcoin/pull/8306#issuecomment-231584578) can't happen. So I do think PR #4935 is safe to merge, even though this same change was backed out of Bitcoin Core.

**Closed** 2021-01-14 15:04 UTC
Labels: A-chain-sync, A-networking, C-bug, I-performance
