### ISSUE TITLE
Upgrade googletest to 1.8.0 and drop separate googlemock dependency.

### ISSUE THREAD

**Issue by nathan-at-least** [zcash/zcash#2110] opened 2017-02-20 00:56 UTC
Our dependency specification for googletest and googlemock contain [a weird hack](https://github.com/zcash/zcash/blob/be5ac31607befe2ff3796379f94a51c9bf8a6894/depends/packages/googlemock.mk#L18), since at the time googlemock wasn't a well-packaged independent dependency. According to https://github.com/google/googletest/issues/763#issuecomment-280864617 it looks like if we depend on googletest 1.8.0 it will include the mock stuff directly, and we can drop the `googlemock.md` package file completely.

**Comment by str4d** [comment] 2017-02-20 01:02
See #1437 for my initial attempt at doing this back before launch. It was failing with a linker error at the time.

**Comment by daira** [comment] 2017-02-20 16:59
Duplicate of #1432.

**Closed by daira** 2017-02-20 16:59 UTC
Labels: dependencies, testing
