### ISSUE TITLE
Crash: "Assertion `nd->witnesses.size() == 0' failed."

### ISSUE THREAD

**Issue by mappum** [zcash/zcash#1648] opened 2016-10-26 04:01 UTC
My zcashd instance has been running for about a week with no issues, but now that I am trying to create transactions it crashes (even after restarting the daemon). 

Error message:
```
zcashd: wallet/wallet.cpp:702: void CWallet::IncrementNoteWitnesses(const CBlockIndex*, const CBlock*, ZCIncrementalMerkleTree&): Assertion `nd->witnesses.size() == 0' failed.
```

````
mappum@zcash:~/zcash$ uname -a
Linux zcash 4.4.0-38-generic #57-Ubuntu SMP Tue Sep 6 15:42:33 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
````
Compiled from zcashd commit `1218603f7357c0649545fbf0ea59e47508d4298f`

**Comment by daira** [comment] 2016-10-26 14:21
That commit is rc1; this bug appears to be a duplicate of #1378 which was fixed in rc2.

**Closed by daira** 2016-10-26 14:21 UTC
