### ISSUE TITLE
Can't send funds to z-address: Invalid Zcash address

### ISSUE THREAD

**Issue by jcramer** [zcash/zcash#2647] opened 2017-10-01 00:02 UTC
### the issue
zcash-cli does not recognize z-addresses when using the command `zcash-cli sendtoaddress "zaddr" ammount `.  Sending from a t-address works fine.

#### steps to reproduce below:
1.  install zcash on ubuntu (I have 16.10),
2.  send funds to a new t-addr,
3.  create a new z-addr,
4.  try to send funds to new z-addr

### expected behaviour
funds should send as they do when using t-addr.

### actual behaviour + errors
```
zcash-cli sendtoaddress "zcWhhXbDXTPmAffyniEP46mkMddSwfoHbbasXk54AZGopERon2qbSwzhW5E4MnGV1b2LZ5md7459CzeoNUrfaWMz35LCanj" 0.5

error code: -5
error message:
Invalid Zcash address
```

### the version of Zcash you were using:
`Zcash Daemon version v1.0.12` I also tried 1.0.11

### machine specs: 
a beast

**Comment by daira** [comment] 2017-10-02 10:14
This is intended behaviour, but we should reconsider it.

**Comment by jcramer** [comment] 2017-10-02 10:26
your "getting started" section suggest otherwise.  Feels like something isn't adding up here.....

**Comment by jcramer** [comment] 2017-10-02 10:28
From "getting started":

Here's an example of how to use the Zcash command line to create a shielded transaction. First, create a shielded address (z-addr):

zcash-cli z_getnewaddress

You can send funds to this z-addr from a transparent address using the "sendtoaddress" command. Once you've funded your z-addr, send 0.8 ZEC to a friend's address using the commmand below.

zcash-cli z_sendmany "$ZADDR" "[{\"amount\": 0.8, \"address\": \"$FRIEND\"}]"

Use "zcash-cli help" to list all possible commands, and see our 1.0 User Guide for more examples of using the Zcash command line interface.

**Comment by daira** [comment] 2017-10-02 11:03
Oops, that documentation is wrong; as you found, sendtoaddress doesn't work for z-address destinations and z_sendmany should be used instead. @paige can you fix this?

**Comment by ioptio** [comment] 2017-10-09 17:02
Website ticket to fix: https://github.com/Electric-Coin-Company/z.cash/issues/994

**Comment by ioptio** [comment] 2017-10-23 17:49
We fixed the download page documentation: https://z.cash/download.html

Closing this.

**Closed by ioptio** 2017-10-23 17:49 UTC
Labels: documentation, RPC interface, usability
