### ISSUE TITLE
Daemon crashes during startup while loading wallet

### ISSUE THREAD

**Issue by etherchain-org** [zcash/zcash#1794] opened 2016-11-05 14:47 UTC
A fresh wallet install crashes during startup (had imported a pretty large z address key before)

> Opened LevelDB successfully
> LoadBlockIndexDB: last block file = 0
> LoadBlockIndexDB: last block file info: CBlockFileInfo(blocks=4985, size=48766871, heights=0...4984, time=2016-10-28...2016-11-05)
> Checking all blk files are present...
> LoadBlockIndexDB: transaction index disabled
> LoadBlockIndexDB: hashBestChain=0000000e0520c92b39879b75c27346dd1df10dd1044226bbe2200178a2e6e9a8 height=1033 date=2016-10-29 15:54:34 progress=0.025923
> init message: Verifying blocks...
> Verifying last 288 blocks at level 3
> No coin database inconsistencies in last 289 blocks (2045 transactions)
>  block index           33058ms
> init message: Loading wallet...
> zcashd: wallet/wallet.cpp:653: void CWallet::IncrementNoteWitnesses(const CBlockIndex*, const CBlock*, ZCIncrementalMerkleTree&): Assertion `(nd->witnessHeight == -1) || (nd->witnessHeight == pindex->nHeight - 1)' failed.

Edit: After having removed the wallet.dat file and the node starts up just fine.

**Comment by bitcartel** [comment] 2016-11-05 17:23
1. On the fresh install, before you imported the keys, did you let the node sync up with the blockchain?
2. How did you import the keys, via rpc z_importwallet?
3. After importing, did you leave the node running or did you shut it down immediately and then later relaunch, when you saw the crash?

**Comment by etherchain-org** [comment] 2016-11-05 21:08
The node was fully synced before importing the private key via tge z_importkey RPC command. The node crashed somewhere during the import process but I am unable to identify the exact point in time. After starting the import I left the daemon running in the background.

**Comment by etherchain-org** [comment] 2016-11-06 21:12
Another user on the forum has experience the same issue: https://forum.z.cash/t/error-after-internal-transaction-from-t-addr-to-z-addr-deamon-is-not-working/7497/4

**Comment by etherchain-org** [comment] 2016-11-12 06:47
Now my daemon crashed repeatedly with this error on two different machines. I am unable to recover my wallet at the moment because of this. Could you please advice how to proceed?!

**Comment by bitcartel** [comment] 2016-11-12 16:20
@etherchain-org so if you launch a fresh node,  import the keys, it crashes? What about if you import,  shut down,  and relaunch with zcashd -reindex, does it still crash?  What is the error message in debug.log? Please copy here. Same as above? 

Ping @ebfull @str4d

**Comment by etherchain-org** [comment] 2016-11-12 17:22
Yes I have the same key importer into two different nodes on two different machines and both crashes at the same time with the same error message. Restarting the node with -reindex is not feasible as it will take ~1 days to complete because the number of tx from and two that particular z address. There is no error message in the debug log at all, only the message given above.

I was able to recover the wallet with -salvagewallet and sweets the funds. I could provide you with the private key of that address if it helps you to debug the issue locally?

**Comment by bitcartel** [comment] 2016-11-12 18:27
@etherchain-org Yes, that would be good.  Please send the key to simon@z.cash, GPG: https://z.cash/support/pubkeys.html (Fingerprint 54BC 723B 5917 AD16 CA59  54BB C8F4 9C08 1F3A C6C4)

What were the exact commands/steps you ran with -salvagewallet?  Thanks.

**Comment by ebfull** [comment] 2016-11-13 03:10
Related: https://github.com/zcash/zcash/issues/1715

**Comment by etherchain-org** [comment] 2016-11-13 21:40
Had the issue again on a new node with a new generated z address and an freshly imported t address (via importprivkey). The node simply crashed while importing a new block:

> UpdateTip: new best=0000000159f8c9a8757287468c337db647b4f3e91dff05b992a49d867289fe16  
> height=9819  log2_work=43.279332  tx=81551  date=2016-11-13 21:15:33 progress=0.999374  cache=31.6MiB(2973tx)
> AddToWallet 252e9554663126af3e0b6568059ba184f338fa978e126cd737ee3c6d23496a08
> UpdateTip: new best=000000008375451fd9ff72f7d2c5a8f47f650b708fd74cfa6dc1ee8228c171f2  height=9820  log2_work=43.279593  tx=81559  date=2016-11-13 21:19:40 progress=0.999602  cache=31.6MiB(2981tx)
> zcashd: wallet/wallet.cpp:653: void CWallet::IncrementNoteWitnesses(const CBlockIndex*, const CBlock*, ZCIncrementalMerkleTree&): Assertion `(nd->witnessHeight == -1) || (nd->witnessHeight == pindex->nHeight - 1)' failed.
> Aborted (core dumped)

This issue is getting really annoying!

**Comment by bitcartel** [comment] 2016-11-13 22:29
@etherchain-org Thanks for the update. Have you sent the key yet, from your earlier post?

**Comment by str4d** [comment] 2016-11-15 01:15
I'm pretty confident that this is a duplicate of #1715, which will be fixed in 1.0.3 (see #1858). @etherchain-org please test once that is out (or manually test with that PR), and reopen this issue if this problem remains.

**Closed by str4d** 2016-11-15 01:15 UTC
Labels: bug, wallet
