### ISSUE TITLE
v4.5.1-1 getmininginfo() rpc always returns 0 for currentblocksize and currentblocktx

### ISSUE THREAD

**Issue by mdr0id** [zcash/zcash#5371] opened 2021-11-06 22:06 UTC
Once the zcashd v4.5.1-1 node is synced, it has been noticed that the getmininginfo RPC is always returning 0 for values in the currentblocksize and currentblocktx:

```
zcash-cli getmininginfo
{
  "blocks": 1451236,
  "currentblocksize": 0,
  "currentblocktx": 0,
  "difficulty": 68204613.96796055,
  "errors": "",
  "errorstimestamp": 1636236195,
  "genproclimit": 1,
  "localsolps": 0,
  "networksolps": 7079199125,
  "networkhashps": 7079199125,
  "pooledtx": 9,
  "testnet": false,
  "chain": "main",
  "generate": false
}
```
Checking from another RPC: `getblock -1` produces:
```
zcash-cli getblock -1
{
  "hash": "00000000005ee6ae20497493ee65830cd9e46a3d37dbc2baa1da880eef0f8714",
  "confirmations": 1,
  "size": 12522,
  "height": 1451236,
  "version": 4,
  ....
  "tx": [
    "aec0309f154f91ad8cc33648e57ddf554816bef5846d507c095b8452fbdf2f2d",
    "7ac3ac4282576dd6d150facb5b7598692c20fc0f5126589e34679445c84e2be1",
    "5521a8d3239dc70ee2fb97635ca6f2bc2a8e3554387f439a72cd07edaf6ce1db",
    "6cd0a77dcc40b1c941a6bf1c804df302b8de4f1902a8744d3755ddeb8027bb1e",
    "2c22708d38b74cee6ad8b4dc74b9e70802c01ae34d010688351e2af1122072d5",
    "135a80ba26afa14bdb114bb181714814af2d8504cdb7a4dd8011ae5e76892a5a",
    "07c8d4f8256685faeae2ec8f075fc6f2ea4ef5f42de3369555c8d8c6c773fa73",
    "cc808b6a89e324784ff0e03de1bd84b89730e529661fddaa19eb7aef81698585",
    "6308fd1fd6789a837a8899f423b58b2ba3a073227d9f86d5557fdc2aa5908e03",
    "a22b85c61e0fe9670be15ede6716fcf428e40191eab688136741a703928f1d46",
    "cc8bf558bc212aeeb4db9563ccc2804af04970398f6e88517d462d5b556eccb7",
    "3a68ca6e9cdb45c4e5be5677ae7cd818cd2da39ec8873c2b89357e853bb353e6",
    "c331ba6858708030fcb5d61b63b93365a45854b7e54ed69aeaf8691c730fa5e2",
    "17d206d270ae1ebc98363f21c7d30d74a2205315dcfd691f3577eebcc9bee77f"
  ],

```

**Comment by LarryRuane** [comment] 2021-12-02 23:43
Hmm, it works for me (running master as of 3 days ago). I'll try v4.5.1-1.
```
10:34 $ src/zcash-cli getmininginfo
{
  "blocks": 1481094,
  "currentblocksize": 4445,
  "currentblocktx": 4,
  "difficulty": 65640890.46507914,
  "errors": "",
  "errorstimestamp": 1638488158,
  "genproclimit": -1,
  "localsolps": 0,
  "networksolps": 7297177431,
  "networkhashps": 7297177431,
  "pooledtx": 3,
  "testnet": false,
  "chain": "main",
  "generate": false
}
```

**Comment by steven-ecc** [comment] 2021-12-03 00:07
4.5.1-1 doesn't work for me.

./src/zcash-cli getmininginfo
{
  "blocks": 1481115,
  "currentblocksize": 0,
  "currentblocktx": 0,
  "difficulty": 55429303.95735081,
  "errors": "",
  "errorstimestamp": 1638489946,
  "genproclimit": 1,
  "localsolps": 0,
  "networksolps": 6717917234,
  "networkhashps": 6717917234,
  "pooledtx": 3,
  "testnet": false,
  "chain": "main",
  "generate": false
}

**Comment by mdr0id** [comment] 2021-12-03 13:30
@LarryRuane and @steven-ecc Does `getblock <blockinquestion>` show either of you what you'd expect from getmininginfo at a given point in time? I noticed inconsistencies between the RPCs and the fields mentioned in the github title for the same block. Perhaps there is a delay from confirmation state in the wallet logic for a more recent block, or a delay in mempool state?

**Comment by LarryRuane** [comment] 2021-12-04 01:05
I figured out this puzzle (why I couldn't reproduce the problem). The two variables that you're seeing as zeros are initialized to zero and only set in `CreateNewBlock()`. That function only runs in three situations:
- you've mined a block (for us, that's when we've enabled mining on testnet, `-gen=1`)
- by the `generate` RPC, which is only used by the Python tests (which uses `regtest`, requiring a trivially small amount of proof-of-work)
- when you run the `getblocktemplate` RPC

When I tried to reproduce this problem, it just so happens that I had earlier run the `getblocktemplate` RPC while trying to reproduce #5401. So that's why my `getmininginfo` run reported non-zero values. When I tried it again (just now), they are zeros.

I think it's normal for these values to be zero, since we usually haven't done one of the three things listed above. So I'd recommend closing this ticket, or we can use it to improve the documentation of those values.

**Comment by steven-ecc** [comment] 2021-12-04 01:13
Thanks @LarryRuane for digging into this. Shouldn't we minimally document this in the `getmininginfo` RPC docs?

**Comment by LarryRuane** [comment] 2021-12-04 03:33
> Shouldn't we minimally document this in the `getmininginfo` RPC docs?

Good idea, I just checked upstream (bitcoin core), and their RPC help text says (note that they have the concept of block weight as opposed to block size, which we don't have):
```
  "currentblockweight" : n,    (numeric, optional) The block weight of the last assembled block (only present if a block was ever assembled)
  "currentblocktx" : n,        (numeric, optional) The number of block transactions of the last assembled block (only present if a block was ever assembled)
```
Ours is:
```
  "currentblocksize": nnn,   (numeric) The last block size
  "currentblocktx": nnn,     (numeric) The last block transaction
```
This change happened in upstream [PR 15383](https://github.com/bitcoin/bitcoin/pull/15383), which also omits these fields if they're uninitialized (seems like a good idea), adds tests, and a few other things. We could cherry-pick this commit entirely, or make a smaller change that gets at the essence.

**Comment by LarryRuane** [comment] 2021-12-06 06:21
#5404 is a loose cherry-pick of the upstream PR; some of its changes are not relevant to us. The change is documented in two places, the "help" RPC output, and the release notes.

**Closed** 2021-12-17 18:07 UTC
Labels: S-committed
