### ISSUE TITLE
Compiled Windows binary not available, can't build the Windows version from the available files

### ISSUE THREAD

**Issue by dandare76** [zcash/zcash#6447] opened 2023-02-20 08:43 UTC
It's been over 2 weeks now since the Windows node doesn't work because of deprecation. It is stuck in "Loading block index" stage.

No Windows binary is available. I have tried to build the Windows binary myself, but no solution file or makefile for Visual C++ exists.

All other popular cryptocurrencies including Bitcoin and Monero make Windows binaries available immediately after the release of a new version.

Please provide a Windows binary or solution file / makefile or instructions needed to build the Windows version of the ZCash node.

**Comment by wbaby** [comment] 2023-02-20 14:25
I have the same opinion as you, Windows has the highest proportion of users, but it is ridiculous that the official does not fully support the Windows.

Cross-compiling doesn't work either, tried that but didn't solve the problem.

#6193

**Comment by rex4539** [comment] 2023-02-21 05:52
https://zcash.readthedocs.io/en/latest/rtd_pages/windows-build.html

**Comment by wbaby** [comment] 2023-02-21 07:11
> https://zcash.readthedocs.io/en/latest/rtd_pages/windows-build.html

We need Windows native programs and don't want to use WSL.

**Comment by daira** [comment] 2023-02-28 23:45
Using WSL is the supported way to build zcash for Windows. It is built into recent Windows versions and there's no reason not to use it.

**Comment by daira** [comment] 2023-03-01 00:25
Because we do not intend to support building *on* Windows (except via WSL, which is essentially building in a Linux guest), this is essentially a duplicate of #6193.

**Closed by daira** 2023-03-01 00:25 UTC
Labels: use case, S-duplicate
