### ISSUE TITLE
Investigate why some tests are dependent on the contents of `~/.zcash/testnet3`

### ISSUE THREAD

**Issue by str4d** [zcash/zcash#1478] opened 2016-10-04 19:59 UTC
While merging PRs for the beta 2 release, we discovered an issue where if the PR for updating dependencies was tested and failed (so not merged), all subsequent builds (or was it tests?) of branches that didn't use the new dependencies would fail. The fix was to delete the `~/.zcash/testnet3` folder, which suggests two things:

- The tests are unnecessarily writing to the live (testnet) data directory.
- The tests are unnecessarily reading from the live (testnet) data directory.

We should identify the cause of this.

**Comment by nathan-at-least** [comment] 2016-10-04 20:05
We have a dumb work-around: ensure buildslaves always nuke that directory prior to test steps.

If there are multiple concurrent buildslave processes for the same user, we may be able to set the ``HOME`` env variable for each build step uniquely.

Because of that, I suggest we timebox figuring out the root cause. If we hit the timebox, switch to this work-around for rc1. For The Glorious Future™ we can find and fix the root cause.

**Comment by str4d** [comment] 2016-10-04 20:07
My main concern is that if users run the tests, they may adversely affect their live network data.

**Comment by bitcartel** [comment] 2016-10-06 22:08
The build slave configuration could delete the folder, rather than having it as part of the codebase.

**Comment by nathan-at-least** [comment] 2016-10-10 21:02
The most important thing is to convince ourselves users cannot accidentally destroy their mainnet wallet. If that's possible we need to protect users with some mitigation in rc1. If this cannot destroy user wallets, and it's just a testing pain-point we can address it later.

**Comment by nathan-at-least** [comment] 2016-10-10 21:04
A first verification is to run automated with no-pre-existing `~/.zcash` and no `$(pwd)/wallet.dat`, then see if either are created.

**Comment by bitcartel** [comment] 2016-10-11 03:29
Resolved by PR #1506

**Closed** 2016-10-14 21:36 UTC
Labels: bug, has PR, testing, testnet
