### ISSUE TITLE
HTTPRPC.FailsOnGET gtest fails on Debian 9

### ISSUE THREAD

**Issue by adityamakkar** [zcash/zcash#2690] opened 2017-10-26 10:22 UTC
### Describe the issue
Test failure after running   ./qa/zcash/full-test-suite.sh on Ubuntu 17.10, g++ 7.2

### Can you reliably reproduce the issue?
```
 ======================================
   Zcash 1.0.12: src/test-suite.log
======================================

# TOTAL: 2
# PASS:  1
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: zcash-gtest
=================

[==========] Running 132 tests from 26 test cases.
[----------] Global test environment set-up.
[----------] 24 tests from checktransaction_tests
[ RUN      ] checktransaction_tests.check_vpub_not_both_nonzero
[       OK ] checktransaction_tests.check_vpub_not_both_nonzero (0 ms)
[ RUN      ] checktransaction_tests.valid_transaction
[       OK ] checktransaction_tests.valid_transaction (0 ms)
[ RUN      ] checktransaction_tests.BadVersionTooLow
[       OK ] checktransaction_tests.BadVersionTooLow (1 ms)
[ RUN      ] checktransaction_tests.bad_txns_vin_empty
[       OK ] checktransaction_tests.bad_txns_vin_empty (0 ms)
[ RUN      ] checktransaction_tests.bad_txns_vout_empty
[       OK ] checktransaction_tests.bad_txns_vout_empty (0 ms)
[ RUN      ] checktransaction_tests.bad_txns_oversize
[       OK ] checktransaction_tests.bad_txns_oversize (2 ms)
[ RUN      ] checktransaction_tests.bad_txns_vout_negative
[       OK ] checktransaction_tests.bad_txns_vout_negative (0 ms)
[ RUN      ] checktransaction_tests.bad_txns_vout_toolarge
[       OK ] checktransaction_tests.bad_txns_vout_toolarge (0 ms)
[ RUN      ] checktransaction_tests.bad_txns_txouttotal_toolarge_outputs
[       OK ] checktransaction_tests.bad_txns_txouttotal_toolarge_outputs (0 ms)
[ RUN      ] checktransaction_tests.bad_txns_txouttotal_toolarge_joinsplit
[       OK ] checktransaction_tests.bad_txns_txouttotal_toolarge_joinsplit (1 ms)
[ RUN      ] checktransaction_tests.bad_txns_txintotal_toolarge_joinsplit
[       OK ] checktransaction_tests.bad_txns_txintotal_toolarge_joinsplit (0 ms)
[ RUN      ] checktransaction_tests.bad_txns_vpub_old_negative
[       OK ] checktransaction_tests.bad_txns_vpub_old_negative (0 ms)
[ RUN      ] checktransaction_tests.bad_txns_vpub_new_negative
[       OK ] checktransaction_tests.bad_txns_vpub_new_negative (0 ms)
[ RUN      ] checktransaction_tests.bad_txns_vpub_old_toolarge
[       OK ] checktransaction_tests.bad_txns_vpub_old_toolarge (0 ms)
[ RUN      ] checktransaction_tests.bad_txns_vpub_new_toolarge
[       OK ] checktransaction_tests.bad_txns_vpub_new_toolarge (0 ms)
[ RUN      ] checktransaction_tests.bad_txns_vpubs_both_nonzero
[       OK ] checktransaction_tests.bad_txns_vpubs_both_nonzero (1 ms)
[ RUN      ] checktransaction_tests.bad_txns_inputs_duplicate
[       OK ] checktransaction_tests.bad_txns_inputs_duplicate (0 ms)
[ RUN      ] checktransaction_tests.bad_joinsplits_nullifiers_duplicate_same_joinsplit
[       OK ] checktransaction_tests.bad_joinsplits_nullifiers_duplicate_same_joinsplit (0 ms)
[ RUN      ] checktransaction_tests.bad_joinsplits_nullifiers_duplicate_different_joinsplit
[       OK ] checktransaction_tests.bad_joinsplits_nullifiers_duplicate_different_joinsplit (0 ms)
[ RUN      ] checktransaction_tests.bad_cb_has_joinsplits
[       OK ] checktransaction_tests.bad_cb_has_joinsplits (0 ms)
[ RUN      ] checktransaction_tests.bad_cb_empty_scriptsig
[       OK ] checktransaction_tests.bad_cb_empty_scriptsig (0 ms)
[ RUN      ] checktransaction_tests.bad_txns_prevout_null
[       OK ] checktransaction_tests.bad_txns_prevout_null (1 ms)
[ RUN      ] checktransaction_tests.bad_txns_invalid_joinsplit_signature
[       OK ] checktransaction_tests.bad_txns_invalid_joinsplit_signature (0 ms)
[ RUN      ] checktransaction_tests.non_canonical_ed25519_signature
[       OK ] checktransaction_tests.non_canonical_ed25519_signature (0 ms)
[----------] 24 tests from checktransaction_tests (6 ms total)

[----------] 7 tests from founders_reward_test
[ RUN      ] founders_reward_test.general

[WARNING] ../src/gtest-death-test.cc:825:: Death tests use fork(), which is unsafe particularly in a threaded context. For this test, Google Test couldn't detect the number of threads.

[WARNING] ../src/gtest-death-test.cc:825:: Death tests use fork(), which is unsafe particularly in a threaded context. For this test, Google Test couldn't detect the number of threads.

[WARNING] ../src/gtest-death-test.cc:825:: Death tests use fork(), which is unsafe particularly in a threaded context. For this test, Google Test couldn't detect the number of threads.

[WARNING] ../src/gtest-death-test.cc:825:: Death tests use fork(), which is unsafe particularly in a threaded context. For this test, Google Test couldn't detect the number of threads.
[       OK ] founders_reward_test.general (903 ms)
[ RUN      ] founders_reward_test.mainnet
[       OK ] founders_reward_test.mainnet (78 ms)
[ RUN      ] founders_reward_test.testnet
[       OK ] founders_reward_test.testnet (74 ms)
[ RUN      ] founders_reward_test.regtest
[       OK ] founders_reward_test.regtest (0 ms)
[ RUN      ] founders_reward_test.slow_start_subsidy
[       OK ] founders_reward_test.slow_start_subsidy (7 ms)
[ RUN      ] founders_reward_test.per_address_reward_mainnet
[       OK ] founders_reward_test.per_address_reward_mainnet (434 ms)
[ RUN      ] founders_reward_test.per_address_reward_testnet
[       OK ] founders_reward_test.per_address_reward_testnet (420 ms)
[----------] 7 tests from founders_reward_test (1918 ms total)

[----------] 3 tests from wallet_zkeys_tests
[ RUN      ] wallet_zkeys_tests.store_and_load_zkeys
[       OK ] wallet_zkeys_tests.store_and_load_zkeys (1 ms)
[ RUN      ] wallet_zkeys_tests.write_zkey_direct_to_db
[       OK ] wallet_zkeys_tests.write_zkey_direct_to_db (50 ms)
[ RUN      ] wallet_zkeys_tests.write_cryptedzkey_direct_to_db
[       OK ] wallet_zkeys_tests.write_cryptedzkey_direct_to_db (798 ms)
[----------] 3 tests from wallet_zkeys_tests (849 ms total)

[----------] 1 test from tautologies
[ RUN      ] tautologies.seven_eq_seven
[       OK ] tautologies.seven_eq_seven (0 ms)
[----------] 1 test from tautologies (0 ms total)

[----------] 9 tests from DeprecationTest
[ RUN      ] DeprecationTest.NonDeprecatedNodeKeepsRunning
[       OK ] DeprecationTest.NonDeprecatedNodeKeepsRunning (0 ms)
[ RUN      ] DeprecationTest.NodeNearDeprecationIsWarned
[       OK ] DeprecationTest.NodeNearDeprecationIsWarned (0 ms)
[ RUN      ] DeprecationTest.NodeNearDeprecationWarningIsNotDuplicated
[       OK ] DeprecationTest.NodeNearDeprecationWarningIsNotDuplicated (0 ms)
[ RUN      ] DeprecationTest.NodeNearDeprecationWarningIsRepeatedOnStartup
[       OK ] DeprecationTest.NodeNearDeprecationWarningIsRepeatedOnStartup (0 ms)
[ RUN      ] DeprecationTest.DeprecatedNodeShutsDown
[       OK ] DeprecationTest.DeprecatedNodeShutsDown (0 ms)
[ RUN      ] DeprecationTest.DeprecatedNodeErrorIsNotDuplicated
[       OK ] DeprecationTest.DeprecatedNodeErrorIsNotDuplicated (0 ms)
[ RUN      ] DeprecationTest.DeprecatedNodeErrorIsRepeatedOnStartup
[       OK ] DeprecationTest.DeprecatedNodeErrorIsRepeatedOnStartup (0 ms)
[ RUN      ] DeprecationTest.DeprecatedNodeShutsDownIfOldVersionDisabled
[       OK ] DeprecationTest.DeprecatedNodeShutsDownIfOldVersionDisabled (0 ms)
[ RUN      ] DeprecationTest.DeprecatedNodeKeepsRunningIfCurrentVersionDisabled
[       OK ] DeprecationTest.DeprecatedNodeKeepsRunningIfCurrentVersionDisabled (0 ms)
[----------] 9 tests from DeprecationTest (0 ms total)

[----------] 5 tests from equihash_tests
[ RUN      ] equihash_tests.expand_and_contract_arrays
[       OK ] equihash_tests.expand_and_contract_arrays (1 ms)
[ RUN      ] equihash_tests.minimal_solution_representation
[       OK ] equihash_tests.minimal_solution_representation (0 ms)
[ RUN      ] equihash_tests.is_probably_duplicate
[       OK ] equihash_tests.is_probably_duplicate (0 ms)
[ RUN      ] equihash_tests.check_basic_solver_cancelled
[       OK ] equihash_tests.check_basic_solver_cancelled (8 ms)
[ RUN      ] equihash_tests.check_optimised_solver_cancelled
[       OK ] equihash_tests.check_optimised_solver_cancelled (4 ms)
[----------] 5 tests from equihash_tests (13 ms total)

[----------] 3 tests from HTTPRPC
[ RUN      ] HTTPRPC.FailsOnGET
FAIL zcash-gtest (exit status: 139)
```

### Expected behaviour
Test should have been successful as all the steps were followed correctly

### Actual behaviour + errors
Test fails and shows make error

What's the fix for this?

Thank you

**Comment by daira** [comment] 2017-10-30 17:11
Exit status 139 means that zcash-gtest failed with a SIGSEGV (segmentation fault). Ideally we need a backtrace of where it failed, by running zcash-gtest under gdb:
```
gdb src/zcash-gtest
run
```
(then when it crashes)
```
bt
```

**Comment by syd0** [comment] 2017-11-15 02:24
Hi @daira,

I was able to reproduce this with Debian 9, g++ 6.3. I don't know how to fix this, but I was able to isolate it to the httprpc test, specifically this line:
```
 TEST(HTTPRPC, FailsOnGET) {
    ...
    EXPECT_FALSE(HTTPReq_JSONRPC(&req, "")); // <-- This guy here
```

The issue happens when the HTTPReq_JSONRPC() method calls the WriteReply mock method:
```
    req->WriteReply(HTTP_BAD_METHOD, "JSONRPC server handles only POST requests");
```

This in turns ends up calling UntypedInvokeWith(), which returns null and crashes when that gets dereferenced:
```
    this->UntypedInvokeWith(&args))->GetValueAndDelete();
```

This crash goes away however if you compile without optimizations (the tests are currently compiled at -O1). So I did some digging and found that the -ftree-free optimization option that is enabled at -O1 causes the crash. If you build with -O1 -fno-tree-fre, the test passes. This smells like a compiler bug to me.. I'm not sure how to work around this.

gdb output:
```
$ gdb --args ./zcash-gtest --gtest_filter=HTTPRPC.FailsOnGET
...
(gdb) run
Starting program: /home/syd/zcash/src/zcash-gtest --gtest_filter=HTTPRPC.FailsOnGET
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Note: Google Test filter = HTTPRPC.FailsOnGET
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from HTTPRPC
[ RUN      ] HTTPRPC.FailsOnGET

Program received signal SIGSEGV, Segmentation fault.
testing::internal::FunctionMockerBase<void (int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>::InvokeWith(std::tuple<int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&> const&) (
    args=std::tuple containing = {...}, this=0x7fffffffdb40)
    at /home/syd/zcash/depends/x86_64-unknown-linux-gnu/share/../include/gmock/gmock-spec-builders.h:1530
1530            this->UntypedInvokeWith(&args))->GetValueAndDelete();
(gdb) bt
#0  testing::internal::FunctionMockerBase<void (int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>::InvokeWith(std::tuple<int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&> const&) (
    args=std::tuple containing = {...}, this=0x7fffffffdb40)
    at /home/syd/zcash/depends/x86_64-unknown-linux-gnu/share/../include/gmock/gmock-spec-builders.h:1530
#1  testing::internal::FunctionMocker<void (int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>::Invoke(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (
    a2="JSONRPC server handles only POST requests", a1=405, this=0x7fffffffdb40)
    at /home/syd/zcash/depends/x86_64-unknown-linux-gnu/share/../include/gmock/gmock-generated-function-mockers.h:118
#2  MockHTTPRequest::WriteReply (this=this@entry=0x7fffffffd990, gmock_a1=gmock_a1@entry=405, gmock_a2=...)
    at gtest/test_httprpc.cpp:15
#3  0x000055555561b7ed in HTTPReq_JSONRPC (req=req@entry=0x7fffffffd990) at ./httprpc.cpp:94
#4  0x000055555561cb5e in HTTPRPC_FailsOnGET_Test::TestBody (this=<optimized out>) at gtest/test_httprpc.cpp:30
#5  0x000055555573207a in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) () at /home/syd/zcash/depends/x86_64-unknown-linux-gnu/share/../include/boost/throw_exception.hpp:69
#6  0x000055555572d7e0 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) () at /home/syd/zcash/depends/x86_64-unknown-linux-gnu/share/../include/boost/throw_exception.hpp:69
#7  0x00005555557148ae in testing::Test::Run() ()
    at /home/syd/zcash/depends/x86_64-unknown-linux-gnu/share/../include/boost/throw_exception.hpp:69
#8  0x0000555555715074 in testing::TestInfo::Run() ()
    at /home/syd/zcash/depends/x86_64-unknown-linux-gnu/share/../include/boost/throw_exception.hpp:69
#9  0x00005555557156bd in testing::TestCase::Run() ()
    at /home/syd/zcash/depends/x86_64-unknown-linux-gnu/share/../include/boost/throw_exception.hpp:69
#10 0x000055555571c18b in testing::internal::UnitTestImpl::RunAllTests() ()
    at /home/syd/zcash/depends/x86_64-unknown-linux-gnu/share/../include/boost/throw_exception.hpp:69
#11 0x0000555555732eff in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) ()
    at /home/syd/zcash/depends/x86_64-unknown-linux-gnu/share/../include/boost/throw_exception.hpp:69
#12 0x000055555572e566 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) ()
    at /home/syd/zcash/depends/x86_64-unknown-linux-gnu/share/../include/boost/throw_exception.hpp:69
#13 0x000055555571ae7b in testing::UnitTest::Run() ()
    at /home/syd/zcash/depends/x86_64-unknown-linux-gnu/share/../include/boost/throw_exception.hpp:69
#14 0x00005555555d0fb3 in RUN_ALL_TESTS () at /home/syd/zcash/depends/x86_64-unknown-linux-gnu/share/../include/gtest/gtest.h:2288
#15 main (argc=<optimized out>, argv=0x7fffffffe0b8) at gtest/main.cpp:22
```

Let me know if there is anything else I can do to help.
-s-

**Comment by daira** [comment] 2017-11-15 05:09
Great debugging, thanks.

It could be a compiler bug, or it could be undefined behaviour in the test process that just happens to only cause a crash if that optimisation is enabled.

**Comment by syd0** [comment] 2017-11-15 06:30
Hi @daira,

I dug a little bit more and you're right, it's a bug in googletest that was fixed:
https://github.com/google/googletest/issues/705

The quick workaround if you don't want to update to a newer googletest is to build the test with -fno-delete-null-pointer-checks. Apparently this only seems to affect mock functions that return void.

Let me know if you'd like me to take a stab at this, i can attempt to update googletest and/or change the way the tests are built.

**Comment by str4d** [comment] 2017-11-15 09:25
This is a duplicate of #2599, but as this issue contains the actual diagnosis, I'll close the other issue :smile:

**Comment by str4d** [comment] 2017-11-15 09:29
@syd0 I tried upgrading Google Test several months ago in #1437, and ran into build issues (they merged Google Mock into Google Test in that release). If you want to try fixing it, that would be awesome!

**Comment by daira** [comment] 2017-11-15 10:20
Added to the CI milestone so that we get the Debian 9 worker correctly running tests for the rest of the release period.

**Comment by syd0** [comment] 2017-11-16 01:02
@str4d I'd be happy to try to fix it but it looks like @daira is working on #1437 already at the moment. @daira if you get tired of it let me know I can take a stab at it.

In the meantime if it looks like updating googletest is going to take some time, the quick fix is just this patch:
```
diff --git a/src/Makefile.gtest.include b/src/Makefile.gtest.include
index 9e1e590d..f2853208 100644
--- a/src/Makefile.gtest.include
+++ b/src/Makefile.gtest.include
@@ -44,7 +44,7 @@ zcash_gtest_SOURCES += \
        wallet/gtest/test_wallet.cpp
 endif

-zcash_gtest_CPPFLAGS = -DMULTICORE -fopenmp -DBINARY_OUTPUT -DCURVE_ALT_BN128 -DSTATIC $(BITCOIN_INCLUDES)
+zcash_gtest_CPPFLAGS = -fno-delete-null-pointer-checks -DMULTICORE -fopenmp -DBINARY_OUTPUT -DCURVE_ALT_BN128 -DSTATIC $(BITCOIN_INCLUDES)

 zcash_gtest_LDADD = -lgtest -lgmock $(LIBBITCOIN_SERVER) $(LIBBITCOIN_CLI) $(LIBBITCOIN_COMMON) $(LIBBITCOIN_UTIL) $(LIBBITCOIN_CRYPTO) $(LIBUNIVALUE) $(LIBLEVELDB) $(LIBMEMENV) \
   $(BOOST_LIBS) $(BOOST_UNIT_TEST_FRAMEWORK_LIB) $(LIBSECP256K1)
```

**Comment by daira** [comment] 2017-11-18 13:36
Feel free to work on #1437 from where I left off, @syd0.

**Comment by syd0** [comment] 2017-11-19 17:53
ack @daira - having a look

**Comment by syd0** [comment] 2017-11-19 19:45
Hi @daira, @str4d - I've submitted #2751. There is a test failure, but it seems like it might not have anything to do with the googletest update?

**Comment by daira** [comment] 2017-11-24 22:22
No that *is* caused by the googletest update. Your mission, should you choose to accept it, is to work out why this is platform-dependent. (A hint could be that the kitchensink builder already has some random version of googletest apt-installed.)

**Comment by syd0** [comment] 2017-11-24 22:27
@daira - indeed this mirrors your previous finding:
```
In file included from /usr/src/gtest/src/gtest-all.cc:42:0:
```

The kitchensink guy is using a global gtest. Let me see how to solve that, perhaps the order of includes/libraries search path is wrong.

**Comment by daira** [comment] 2017-11-24 23:14
Another hint is that it only fails on the libsnark testing step, not the main build.

**Comment by syd0** [comment] 2017-11-24 23:16
Yeah I figured it out - it's pretty dumb! Pushing a fix soon.

**Comment by str4d** [comment] 2017-11-28 17:09
Test went green! [Before](https://ci.z.cash/#/builders/12/builds/120), [after](https://ci.z.cash/#/builders/12/builds/121).

**Closed by str4d** 2017-11-28 17:09 UTC
Labels: dependencies, portability, testing
