### ISSUE TITLE
Compilation problem in ./depends/x86_64-unknown-linux-gnu/include/libsnark/gadgetlib2/constraint.hpp

### ISSUE THREAD

**Issue by JanKalin** [zcash/zcash#835] opened 2016-04-06 10:17 UTC
Compilation on Debian fails with "<:: cannot begin a template-argument list" in line 157 of file 
./depends/x86_64-unknown-linux-gnu/include/libsnark/gadgetlib2/constraint.hpp

Solution is to change from
`typedef ::std::set<::std::unique_ptr<Polynomial> > PolyPtrSet;`
to
`typedef ::std::set< ::std::unique_ptr<Polynomial> > PolyPtrSet;`

**Comment by JanKalin** [comment] 2016-04-06 10:22
Too quick to post - saw that it was already reported

**Comment by daira** [comment] 2016-04-06 12:30
Duplicate of #775.

**Closed by daira** 2016-04-06 12:30 UTC
Labels: build, C++11, duplicate, libsnark
