### ISSUE TITLE
libgomp error

### ISSUE THREAD

**Issue by amacfie** [zcash/zcash#1692] opened 2016-10-28 19:35 UTC
I followed the [Debian install instructions](https://github.com/zcash/zcash/wiki/Debian-binary-packages) and ran `zcash-fetch-params`.
Then I followed the [configuration](https://github.com/zcash/zcash/wiki/1.0-User-Guide#configuration) instructions and enabled CPU mining with the default miner.
Now running `zcashd` gives the following error:

```
zcashd: /usr/lib/x86_64-linux-gnu/libgomp.so.1: version `GOMP_4.0' not found (required by zcashd)
a
```

Dist: Ubuntu 14.04
Kernel: Linux 3.19.3-031903-generic x86_64

**Comment by woeisme** [comment] 2016-10-29 17:33
New VM with debian wheezy, experienced this problem also. Was informed in the IRC channel by radix42 that debian repo is only built on jessie

**Comment by amacfie** [comment] 2016-10-30 00:49
@woeisme Thanks! I'll stop trying to use the package for Ubuntu.

**Comment by ragsx** [comment] 2016-10-30 04:15
got the same error "zcashd: /usr/lib/x86_64-linux-gnu/libgomp.so.1: version `GOMP_4.0' not found (required by zcashd). 
What is the solution if using Ubuntu them?

**Comment by hazinstore** [comment] 2016-10-30 05:17
The answer is to install GCC from backports or just recompile it locally.
Sounds like you're on 16.04, libgomp is in 16.10
I solved it with a dist-upgrade

**Comment by radix42** [comment] 2016-10-30 09:02
My zcash deb built on Ubuntu 16.04 is at:
https://s3-us-west-1.amazonaws.com/zcash.dl.mercerweiss.com/zcash-1.0.0-sprout-amd64.deb

**Comment by wmark** [comment] 2016-10-30 13:29
There is more recent version of libgomp, too:
https://s.blitznote.com/debs/ubuntu/amd64/all/zcash_1.0.0_amd64.deb
https://s.blitznote.com/debs/ubuntu/amd64/all/zcash-params_20161024_amd64.deb

**Comment by ragsx** [comment] 2016-10-31 02:35
upgrading it is, thanks!

**Comment by nathan-at-least** [comment] 2017-03-13 22:50
Let's see if we can improve our `.deb` file to at the very least fail with an error to prevent this kind of runtime error.

**Comment by daira** [comment] 2017-04-20 06:39
Duplicate of #2257.

**Comment by daira** [comment] 2017-04-20 13:02
Note that we now tell users in the User Guide to upgrade to gcc/g++ 4.9 if needed; that will probably also install the required version of libgomp.

**Comment by daira** [comment] 2017-07-06 22:26
The User Guide has been updated to clarify the dependency on gcc version for users who build from source, and the Debian packages now explicitly declare a dependency on libgomp. We're adding a CI worker for Ubuntu (#2471) so that should also improve testing on that platform in future.

**Closed by daira** 2017-07-06 22:26 UTC
Labels: dependencies, documentation, fails to run, OpenMP, packaging, portability, user follow-up
