### ISSUE TITLE
cli integer parsing busted for some calls / arguments

### ISSUE THREAD

**Issue by buck54321** [zcash/zcash#6519] opened 2023-03-30 23:33 UTC
When passing integer arguments via **zcash-cli**, the call fails with 
```
error code: -1
error message:
JSON value is not an integer as expected
```
The following commands all fail.
`zcash-cli getwalletinfo 1`
`zcash-cli listaddressgroupings 10`
`zcash-cli z_getbalanceforviewingkey "uview..." 1`
`zcash-cli z_getbalanceforaccount 0 10 1`
`zcash-cli z_getmigrationstatus 1`
`zcash-cli z_getnotescount 1 1`

On the other hand, integer parsing seems to work fine for
`zcash-cli listreceivedbyaddress 1`
`zcash-cli listunspent 1`
`zcash-cli z_getaddressforaccount 0`
`zcash-cli z_getbalanceforaccount 0 10`
`zcash-cli z_getnotescount 1`
`zcash-cli z_gettotalbalance 0`
`zcash-cli z_listunspent 1`

Running v5.4.2

**Comment by sellout** [comment] 2023-04-04 20:30
This is effectively a duplicate of #6429 (although you did identify some additional cases).

They’re all fixed in #6448, which will be in release 5.5.0.

**Closed by sellout** 2023-04-04 20:30 UTC
