### ISSUE TITLE
Wallet restart after a clean shutdown takes several hours.

### ISSUE THREAD

**Issue by etherchain-org** [zcash/zcash#1822] opened 2016-11-08 08:09 UTC
I had to restart my wallet to update to the new version 1.0.2. I performed a clean shutdown and after the restart the node began to rescan the last 503 blocks. This process currently takes more than 2 hours. It is simply unacceptable that a simple wallet restart takes the wallet offline for such a long period of time!

**Comment by feeleep75** [comment] 2016-11-08 10:05
I can confirm this... 

BTW: does z_sendmany performance depends somehow on avx2? one of the nodes is extremely slow in sending transactions...

**Comment by ebfull** [comment] 2016-11-08 16:30
How many zaddrs do you have?

**Comment by etherchain-org** [comment] 2016-11-08 17:01
Exactly one.

**Comment by str4d** [comment] 2016-11-17 06:03
Closing as a (likely) duplicate of #1749.

**Closed by str4d** 2016-11-17 06:03 UTC
Labels: performance, wallet
