### ISSUE TITLE
Addresses aren’t recognized with importaddress.

### ISSUE THREAD

**Issue by ytrezq** [zcash/zcash#5324] opened 2021-09-24 12:02 UTC
Simply use any current official binaries and try

    zcash-cli.exe importaddress "t1RTDdKBeiQvrmjKfpny3AETyhY6RxdHf"
    error code: -5
    error message:
    Invalid Zcash address or script

which instead should have worked directly.

**Comment by mdr0id** [comment] 2021-09-24 13:47
Are you building these Windows binaries locally or getting them from a different host/mirror?

**Comment by str4d** [comment] 2021-09-24 14:09
The above address is inherently invalid:
```
$ python
Python 3.8.10 (default, Jun  2 2021, 10:49:15)
>>> import base58
>>> base58.b58decode_check('t1RTDdKBeiQvrmjKfpny3AETyhY6RxdHf')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.8/site-packages/base58/__init__.py", line 157, in b58decode_check
    raise ValueError("Invalid checksum")
ValueError: Invalid checksum
```

It looks like the address might be truncated? A normal t-addr encoding is 35 characters.

**Comment by ytrezq** [comment] 2021-09-26 19:05
@str4d sorry, it looks you’re right.
And it’s truncated on disk. ᴏ how to retrieve the last 2 letters ? block explorer only allows to search for the exact same address, not by partial matches as far I’m aware.

**Comment by nuttycom** [comment] 2021-09-28 17:02
@ytrezq where are you obtaining this address from?

**Comment by ytrezq** [comment] 2021-09-29 01:01
@nuttycom an accidentally truncated file.

**Comment by nuttycom** [comment] 2021-09-29 03:50
@ytrezq so, one possibility since you're only a couple of characters short is you could brute-force the last two characters by repeated trial against base58check.

**Comment by nuttycom** [comment] 2021-09-29 14:13
Closing as this is not a bug.

**Closed by nuttycom** 2021-09-29 14:13 UTC

**Comment by ytrezq** [comment] 2021-09-29 17:34
> @ytrezq so, one possibility since you're only a couple of characters short is you could brute-force the last two characters by repeated trial against base58check.

@nuttycom the problem is I don’t have an idea on how to perform such brute force.

**Comment by hhanh00** [comment] 2024-02-25 06:57
Seems to fail on a valid address

```
(venv) hanhhuynhhuu@Hanhs-MacBook-Air smoke % python
Python 3.11.6 (main, Oct  2 2023, 13:45:54) [Clang 15.0.0 (clang-1500.0.40.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import base58
>>> base58.b58decode_check('t1Xon5pbiEx7eMc4XsmhThHcKfUeu9u9Dsa')
b'\x1c\xb8\x98\xd8\x82_e\xae\x01\x1cm\xa9D\x1a\xe1F\xdb\\\x07\xed\x9a\x0f'
>>> ^D
```

```
[hanh@archlinux zcash]$ ./src/zcash-cli importaddress "t1Xon5pbiEx7eMc4XsmhThHcKfUeu9u9Dsa"
error code: -5
error message:
Invalid Zcash address or script
```
