### ISSUE TITLE
Zcashd v5.2.0 crashes

### ISSUE THREAD

**Issue by PRabahy** [zcash/zcash#6103] opened 2022-07-27 21:15 UTC
### Describe the issue
I upgraded from ZecWallet from 1.8.1 (never seemed to finish catching up) to 1.8.2 and now I am getting the following message. I posted a bug report to their github tracker (https://github.com/ZcashFoundation/zecwallet/issues/375) and @adityapk00 said I should post it here.

### Can you reliably reproduce the issue?
No

### Actual behaviour + errors
```
2022-07-27T02:57:45.097068Z  INFO main: UpdateTip: new best hash=0000000001d089c19d9c21b78bc09006cc3f33341a2c5f4447a88c534a57d0ea height=1737754 bits=469904555 log2_work=59.292453 tx=11100880 date=2022-07-14 22:55:18 progress=0.991649 cache=17.3MiB(3156tx)
2022-07-27T02:57:48.760742Z  INFO ProcessNewBlock: main: UpdateTip: new best hash=0000000000fb6d5abdb000e6f67d70ec08abbc085d09185d0396de614646a22f height=1737755 bits=469906136 log2_work=59.292454 tx=11100902 date=2022-07-14 22:55:52 progress=0.991649 cache=17.3MiB(3160tx)
2022-07-27T02:57:49.415616Z  INFO ProcessNewBlock: main: UpdateTip: new best hash=0000000000779980ae22457330e8117704ee89f523f0f5a0d1f06f105f8982c0 height=1737756 bits=469903792 log2_work=59.292455 tx=11100903 date=2022-07-14 22:57:44 progress=0.991650 cache=17.3MiB(3161tx)
2022-07-27T02:57:49.747723Z  INFO ProcessNewBlock: main: Pre-allocating up to position 0x7000000 in blk00344.dat
2022-07-27T02:57:52.945802Z  INFO ProcessNewBlock: main: UpdateTip: new best hash=0000000000044037130f6a7cd672b30058c529f96b8949c358273e68d0931a82 height=1737757 bits=469908720 log2_work=59.292456 tx=11100923 date=2022-07-14 22:58:01 progress=0.991650 cache=17.3MiB(3164tx)
2022-07-27T02:57:56.414568Z  INFO ProcessNewBlock: main: UpdateTip: new best hash=00000000007e9319bbdfdebca0ccbe4ed7226aa3d77719352ffcd7878d9aeb97 height=1737758 bits=469906698 log2_work=59.292457 tx=11100929 date=2022-07-14 22:58:26 progress=0.991651 cache=17.3MiB(3165tx)
2022-07-27T02:57:57.089757Z  INFO ProcessNewBlock: main: Pre-allocating up to position 0x8000000 in blk00344.dat
2022-07-27T02:57:57.301610Z ERROR main: ReadBlockFromDisk(CBlock&, CBlockIndex*): block index entry does not provide a valid disk position for block CBlockIndex(pprev=000001805e87aaa0, nHeight=1737786, merkle=a0efc7a977b90a6bb54ccf88ec5582996393907cd8238d13df4ea7a89a213fcb, hashBlock=00000000026995e1e3d30af4e5acb2af3f54ff6b76230679528eb3a2d65c4ea3) at CBlockDiskPos(nFile=-1, nPos=0)
2022-07-27T02:57:57.301631Z  INFO main: *** ThreadNotifyWallets: Failed to read block 00000000026995e1e3d30af4e5acb2af3f54ff6b76230679528eb3a2d65c4ea3 while collecting shielded outputs
2022-07-27T02:57:57.301638Z  INFO main: Error: Error: A fatal internal error occurred, see debug.log for details
2022-07-27T02:57:57.302113Z  INFO main: txnotify thread exit
2022-07-27T02:57:57.315099Z  INFO main: tor: Thread interrupt
2022-07-27T02:57:57.315281Z  INFO main: torcontrol thread exit
2022-07-27T02:57:57.315375Z  INFO main: addcon thread interrupt
2022-07-27T02:57:57.315375Z  INFO main: opencon thread interrupt
2022-07-27T02:57:57.315459Z  INFO main: scheduler thread interrupt
2022-07-27T02:57:57.346894Z  INFO main: net thread interrupt
2022-07-27T02:57:57.428511Z  INFO ProcessNewBlock: main: UpdateTip: new best hash=00000000008bce2ea6f102f3a46d2c39250c087e6c188d9db035793187b40dcd height=1737759 bits=469905061 log2_work=59.292458 tx=11100937 date=2022-07-14 23:04:01 progress=0.991653 cache=17.3MiB(3173tx)
2022-07-27T02:57:57.428671Z  INFO main: msghand thread interrupt
2022-07-27T02:57:57.428840Z  INFO Shutdown: main: StopRPC: waiting for async rpc workers to stop
2022-07-27T02:57:57.603469Z  INFO Shutdown: main: StopNode()
2022-07-27T02:57:58.072444Z  INFO Shutdown: main: done
2022-07-27T03:00:55.386494Z  INFO main: 
```

### The version of Zcash you were using:
Zcash Daemon version v5.2.0

### Machine specs:
- OS name + version: Windows 10 Home 21H2
- CPU: AMD Ryzen 5 2600 Six-Core Processor 3.40 GHz
- RAM: 16.0 GB
- Disk size: 2TB
- Disk Type (HD/SDD): SATA SSD
- Linux kernel version (uname -a): n/a
- Compiler version (gcc --version): unknown - Whatever https://github.com/ZcashFoundation/zecwallet uses
- Linker version (ld -v): unknown - Whatever https://github.com/ZcashFoundation/zecwallet uses
- Assembler version (as --version): unknown - Whatever https://github.com/ZcashFoundation/zecwallet uses

### Do you have a backup of `~/.zcash` directory and/or take a VM snapshot?
I can if you need it, but I think the log posted is the most relevant thing.

**Comment by PRabahy** [comment] 2022-07-28 00:32
I'm not sure if this is related, but I'm getting `Assertion failed: nd.witnessHeight == -1, file wallet/wallet.cpp, line 2655` now.

**Comment by wbaby** [comment] 2022-07-28 09:30
Same problem

**Comment by str4d** [comment] 2022-07-28 16:48
> I upgraded from ZecWallet from 1.8.1 (never seemed to finish catching up) to 1.8.2 and now I am getting the following message

This is not a crash (the node is just shutting down as a result of an error). It is also not something we can generally deal with automatically. What this error message (and the corresponding node shutdown) is saying is that somewhere between the state the wallet is currently in, and the state the node is currently in, there is missing block data. The fix for this is to run with `-rescan`, which resets the wallet state to not depend on that data.

I'm a little confused in that the block your wallet is depending on _is_ in the main chain however, so there might be a separate data synchronisation issue we need to deal with. We currently use a heuristic to figure out whether the node is ever going to download all the necessary data for the wallet, so that we can shut down instead of hanging indefinitely. It's possible that this heuristic is not complete enough, and so the wallet is exiting early when it might have been able to recover given enough time.

> I'm not sure if this is related, but I'm getting `Assertion failed: nd.witnessHeight == -1, file wallet/wallet.cpp, line 2655` now.

Now this _is_ a crash, but it is unrelated to the issue you originally opened. What did you do with your `zcashd` node / wallet in between the two errors?

**Comment by PRabahy** [comment] 2022-07-28 23:48
Between the 2 crashes, I don't think I did anything special. I probably launched zcashd a couple of times and tried to close it with ctrl+c (doesn't work). Usually I just click the x on the command prompt window that I use to run it.

**Comment by PRabahy** [comment] 2022-07-29 02:50
The assertion failed just happened a second time, so it looks like that is reproducible.

**Comment by wbaby** [comment] 2022-07-29 09:37
> 

The fix for this is to run with -rescan

Tried it, but can't solve the crash problem
version 5.0.0 doesn't crash.

**Comment by PRabahy** [comment] 2022-07-30 14:49
Ran with -rescan and it cleared out the assertion, but now I'm getting:
```
2022-07-30T02:25:13.050178Z  INFO ProcessNewBlock: main: UpdateTip: new best hash=000000000154a3535c020e3b0727c50f3e3588935083b0ee269fee727166717a height=1754741 bits=469898818 log2_work=59.313494 tx=11239775 date=2022-07-29 18:36:28 progress=0.999779 cache=125.4MiB(61277tx)
2022-07-30T02:25:13.308237Z  INFO ProcessNewBlock: main: UpdateTip: new best hash=00000000018a9ce1de1214a7e85d2ee28f89a63f471fcaac3b674fc37aa4eda5 height=1754742 bits=469892949 log2_work=59.313495 tx=11239778 date=2022-07-29 18:36:43 progress=0.999779 cache=125.4MiB(61278tx)
2022-07-30T02:25:13.531445Z ERROR main: *** operator(): The wallet's best block hash 0000000001ea6de9947f428aaa8f3369734c4f4aa2ceca5ace7635665195a4da was not detected in restored chain state. Giving up; please restart with `-rescan`.
2022-07-30T02:25:13.531470Z  INFO main: Error: Error: A fatal wallet synchronization error occurred, see debug.log for details
```

**Comment by PRabahy** [comment] 2022-07-31 13:57
After a few more restarts with a combination of -rescan and -exportdir it appears to be running stably. I'm still having an issue with Zecwallet Fullnode connecting (https://github.com/ZcashFoundation/zecwallet/issues/376), but I think that is probably an issue with the wallet. Should I close out this issue?

**Comment by wbaby** [comment] 2022-08-01 06:38
I found a workaround:
run zcashd -rescan
Then run zcashd normally
But it needs at least 32G memory, otherwise it will be crash because the memory is not enough

**Comment by str4d** [comment] 2022-08-01 13:22
> Ran with -rescan and it cleared out the assertion, but now I'm getting:
> 
> ```
> 2022-07-30T02:25:13.050178Z  INFO ProcessNewBlock: main: UpdateTip: new best hash=000000000154a3535c020e3b0727c50f3e3588935083b0ee269fee727166717a height=1754741 bits=469898818 log2_work=59.313494 tx=11239775 date=2022-07-29 18:36:28 progress=0.999779 cache=125.4MiB(61277tx)
> 2022-07-30T02:25:13.308237Z  INFO ProcessNewBlock: main: UpdateTip: new best hash=00000000018a9ce1de1214a7e85d2ee28f89a63f471fcaac3b674fc37aa4eda5 height=1754742 bits=469892949 log2_work=59.313495 tx=11239778 date=2022-07-29 18:36:43 progress=0.999779 cache=125.4MiB(61278tx)
> 2022-07-30T02:25:13.531445Z ERROR main: *** operator(): The wallet's best block hash 0000000001ea6de9947f428aaa8f3369734c4f4aa2ceca5ace7635665195a4da was not detected in restored chain state. Giving up; please restart with `-rescan`.
> 2022-07-30T02:25:13.531470Z  INFO main: Error: Error: A fatal wallet synchronization error occurred, see debug.log for deta
> ```

`0000000001ea6de9947f428aaa8f3369734c4f4aa2ceca5ace7635665195a4da` is [block 1754794 in the main chain](https://blockchair.com/zcash/block/1754794), but your node was only synced up to height 1754742. The code that gives rise to this error does the following:
- Fetches the "best block" known to the wallet.
- Waits for the node to exit Initial Block Download mode (which means it is within 24 hours of the current chain tip).
- Starts a 5 minute timer.
- 1️⃣ Waits for the wallet's "best block" to be known to the node (i.e. its header has arrived).
- 2️⃣ Waits for the wallet's "best block" to be no more than 100 blocks ahead of the current chain tip.
- If the 5 minute timer ends before both of the above checks are finished, prints the "giving up" error and shuts down the node.

2️⃣ can't be the cause because your chain tip was within 100 blocks. This suggests the problem was that your node was not able to synchronise blocks from the chain fast enough to catch up within 5 minutes. This also explains why the problem resolved itself after several restarts: each time a few more blocks were fetched, and eventually your node could catch up.

How many `UpdateTip` messages did your node have before that error (that is, how many blocks _did_ it manage to download and validate after it had finished starting up but before the timer ran out)?

**Comment by daira** [comment] 2022-08-01 14:38
I suggest changing the timeout to 20m.

**Comment by PRabahy** [comment] 2022-08-01 14:38
How many UpdateTip messages did your node have before that error? -> Lots! Its pretty much the same pattern back in the log until I hit:
```
2022-07-30T01:32:25.294083Z  INFO main: UpdateTip: new best hash=00000000008bfbbdd336d9ee03762c5b5df50dcc92f9c2ebfd1d6151a12cfff7 height=1752821 bits=469884608 log2_work=59.311162 tx=11219083 date=2022-07-28 02:26:37 progress=0.998665 cache=95.7MiB(52850tx)
2022-07-30T01:32:28.901632Z  INFO main: UpdateTip: new best hash=0000000000ff1bfd3a41a6049da5a25409de5e74553d7f6238bf438620890d2a height=1752822 bits=469884570 log2_work=59.311163 tx=11219101 date=2022-07-28 02:28:03 progress=0.998666 cache=95.7MiB(52851tx)
2022-07-30T01:32:32.568485Z  INFO main: UpdateTip: new best hash=00000000018c7beb65698b97d95094c4d49dc8002864f4be5121dfd53ff552dd height=1752823 bits=469885569 log2_work=59.311165 tx=11219128 date=2022-07-28 02:33:54 progress=0.998669 cache=95.8MiB(52863tx)
2022-07-30T01:32:36.302986Z  INFO main: UpdateTip: new best hash=00000000001d7083765f3ac62b10d46f9a2f2620bcda2a97ed410c68ff8c33af height=1752824 bits=469886704 log2_work=59.311166 tx=11219147 date=2022-07-28 02:34:25 progress=0.998669 cache=95.8MiB(52865tx)
2022-07-30T01:32:39.892382Z  INFO main: UpdateTip: new best hash=0000000000030c2351a5287765eda59b4a7051f5dc550c55d959505efa1a467e height=1752825 bits=469887306 log2_work=59.311167 tx=11219166 date=2022-07-28 02:35:44 progress=0.998669 cache=95.8MiB(52867tx)
2022-07-30T01:32:43.639100Z  INFO main: UpdateTip: new best hash=000000000059fb3eb4163373351c7a6d77b2effdaa067411643ee5a4900d3353 height=1752826 bits=469893362 log2_work=59.311168 tx=11219185 date=2022-07-28 02:36:27 progress=0.998670 cache=95.8MiB(52868tx)
2022-07-30T01:32:44.104146Z  INFO ProcessNewBlock: main: UpdateTip: new best hash=00000000012762d64cabfb0a050c039f6870fcf7152182b389de729b412eb5d4 height=1752827 bits=469896647 log2_work=59.311169 tx=11219186 date=2022-07-28 02:37:35 progress=0.998670 cache=95.8MiB(52869tx)
2022-07-30T01:32:47.867713Z  INFO ProcessNewBlock: main: UpdateTip: new best hash=0000000001660ab81d0a57b7e19bc553a6d399c20c5e2609ed9d85f1d392fb53 height=1752828 bits=469895265 log2_work=59.31117 tx=11219207 date=2022-07-28 02:39:01 progress=0.998671 cache=95.8MiB(52871tx)
2022-07-30T01:32:51.721441Z  INFO ProcessNewBlock: main: UpdateTip: new best hash=00000000021dd6c26d81c2ed91b809f61415a5d9e1600b7d70a514adcc5d7f01 height=1752829 bits=469904492 log2_work=59.311171 tx=11219229 date=2022-07-28 02:39:59 progress=0.998671 cache=95.8MiB(52872tx)
2022-07-30T01:32:51.843533Z  INFO ProcessNewBlock: main: Pre-allocating up to position 0x4000000 in blk00408.dat
```

In terms of line numbers, the error was on 73517 and the chunk of `UpdateTip` ended on 71471, so I would say roughly 2000 of those messages (there were some `Leaving block file` and `Pre-allocating up to position` mixed in).

**Comment by PRabahy** [comment] 2022-08-01 14:41
If I look in the log 5 minutes before it exits, I get:
```
2022-07-30T02:20:00.753622Z  INFO ProcessNewBlock: main: UpdateTip: new best hash=0000000000ed6f0a47757f1ebe650852fa67a3f91c2522b7233c79a80c485225 height=1754551 bits=469863117 log2_work=59.313266 tx=11237680 date=2022-07-29 14:28:44 progress=0.999665 cache=123.5MiB(60550tx)
2022-07-30T02:20:01.686103Z  INFO ProcessNewBlock: main: UpdateTip: new best hash=0000000000574db92bfd3423ada066cf78c4aca8e641320b972a0c7063ae9d48 height=1754552 bits=469865058 log2_work=59.313267 tx=11237685 date=2022-07-29 14:29:07 progress=0.999665 cache=123.5MiB(60551tx)
2022-07-30T02:20:02.354203Z  INFO ProcessNewBlock: main: UpdateTip: new best hash=00000000005d1db41201837b5cd89d735c4f6a773f6d3b3e626b9b5f95986acb height=1754553 bits=469865417 log2_work=59.313269 tx=11237693 date=2022-07-29 14:30:48 progress=0.999665 cache=123.5MiB(60551tx)
2022-07-30T02:20:02.575548Z  INFO ProcessNewBlock: main: UpdateTip: new best hash=0000000000e89e78631e4dbdd236321cba5e95b97f99b26a345136b91bb7f830 height=1754554 bits=469864636 log2_work=59.31327 tx=11237694 date=2022-07-29 14:32:22 progress=0.999666 cache=123.5MiB(60552tx)
2022-07-30T02:20:06.275064Z  INFO ProcessNewBlock: main: UpdateTip: new best hash=0000000000a5b9f0348e2ea37c984da89753fc9de734e4a567a2749579bd7c9b height=1754555 bits=469863356 log2_work=59.313272 tx=11237739 date=2022-07-29 14:42:24 progress=0.999671 cache=123.6MiB(60571tx)
2022-07-30T02:20:09.918821Z  INFO ProcessNewBlock: main: UpdateTip: new best hash=0000000000a827aa93942b5798216e88393cec41f92da159ccea7f8ebfdec0fe height=1754556 bits=469861916 log2_work=59.313273 tx=11237759 date=2022-07-29 14:43:31 progress=0.999671 cache=123.6MiB(60572tx)
2022-07-30T02:20:13.689381Z  INFO ProcessNewBlock: main: UpdateTip: new best hash=0000000000e3f64081b4ca13fb3ce80b62d0d7c6c89202bd4020761530f7e084 height=1754557 bits=469862794 log2_work=59.313275 tx=11237777 date=2022-07-29 14:43:37 progress=0.999671 cache=123.6MiB(60573tx)
2022-07-30T02:20:17.413196Z  INFO ProcessNewBlock: main: UpdateTip: new best hash=0000000000e42595ec0a7ec7f941f907eab9ac1b663a247006af590693e616af height=1754558 bits=469861863 log2_work=59.313276 tx=11237815 date=2022-07-29 14:46:13 progress=0.999673 cache=123.6MiB(60575tx)
2022-07-30T02:20:18.606117Z  INFO ProcessNewBlock: main: UpdateTip: new best hash=00000000004c3394b1a5226a1c878580c7440c0254af1da34d642a78ac3398ee height=1754559 bits=469861327 log2_work=59.313277 tx=11237823 date=2022-07-29 14:46:27 progress=0.999673 cache=123.7MiB(60583tx)
2022-07-30T02:20:20.014379Z  INFO ProcessNewBlock: main: UpdateTip: new best hash=000000000126776ba1fb85bf3ba903c014746ab1147374ed24ae327bb65783cc height=1754560 bits=469860552 log2_work=59.313279 tx=11237842 date=2022-07-29 14:48:45 progress=0.999674 cache=123.7MiB(60586tx)
2022-07-30T02:20:23.100162Z  INFO ProcessNewBlock: main: UpdateTip: new best hash=00000000016b89b660ed58084f5b164ae0019bea988738bef4bced440bcf0f1b height=1754561 bits=469871957 log2_work=59.31328 tx=11237867 date=2022-07-29 14:51:33 progress=0.999675 cache=123.7MiB(60592tx)
```
Should I see anything special around then?

**Comment by PRabahy** [comment] 2022-12-23 21:27
I just confirmed that this still happened with 5.3.0. It was syncing for about a day, crashed, and has been syncing for another hour after restarting it.

**Comment by str4d** [comment] 2023-01-09 20:56
Let's try changing the timeout from 5 minutes to 2 hours in the next release. We don't want to block indefinitely, but all that the timer prevents is the wallet from working, and there's a better chance of it working if we wait. (But on the flipside, there are reorg-related situations where no timeout will be sufficient, and the user just has to reindex.)

**Comment by daira** [comment] 2023-01-12 23:58
> Ran with -rescan and it cleared out the assertion, but now I'm getting:
> 
> ```
> 2022-07-30T02:25:13.050178Z  INFO ProcessNewBlock: main: UpdateTip: new best hash=000000000154a3535c020e3b0727c50f3e3588935083b0ee269fee727166717a height=1754741 bits=469898818 log2_work=59.313494 tx=11239775 date=2022-07-29 18:36:28 progress=0.999779 cache=125.4MiB(61277tx)
> 2022-07-30T02:25:13.308237Z  INFO ProcessNewBlock: main: UpdateTip: new best hash=00000000018a9ce1de1214a7e85d2ee28f89a63f471fcaac3b674fc37aa4eda5 height=1754742 bits=469892949 log2_work=59.313495 tx=11239778 date=2022-07-29 18:36:43 progress=0.999779 cache=125.4MiB(61278tx)
> 2022-07-30T02:25:13.531445Z ERROR main: *** operator(): The wallet's best block hash 0000000001ea6de9947f428aaa8f3369734c4f4aa2ceca5ace7635665195a4da was not detected in restored chain state. Giving up; please restart with `-rescan`.
> 2022-07-30T02:25:13.531470Z  INFO main: Error: Error: A fatal wallet synchronization error occurred, see debug.log for details
> ```

@PRabahy On the node that was experiencing this error, can you try with the branch on #6347 please?

**Comment by PRabahy** [comment] 2023-01-13 00:31
Maybe, is there easy-ish instructions to compile on Windows? I usually just use the one built into Zecwallet Fullnode.

**Closed** 2023-01-13 01:02 UTC

**Comment by daira** [comment] 2023-01-14 19:38
First three steps in #4622.
